# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _CustomerDataManagement(_Saas):
    _type = "cdm"
    _icon_dir = "resources/saas/cdm"


class Segment(_CustomerDataManagement):
    _icon = "segment.png"


# Aliases
