# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _CustomerDataPlatform(_Saas):
    _type = "cdm"
    _icon_dir = "resources/saas/cdp"


class Segment(_CustomerDataPlatform):
    _icon = "segment.png"


class RudderStack(_CustomerDataPlatform):
    _icon = "rudderstack.png"


# Aliases
