# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Chat(_Saas):
    _type = "chat"
    _icon_dir = "resources/saas/chat"


class Slack(_Chat):
    _icon = "slack.png"


class Telegram(_Chat):
    _icon = "telegram.png"


# Aliases
