# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _CustomerRelationshipManagement(_Saas):
    _type = "crm"
    _icon_dir = "resources/saas/crm"


class Pipedrive(_CustomerRelationshipManagement):
    _icon = "pipedrive.png"


# Aliases
