# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _ElasticCloud(_Saas):
    _type = "elasticcloud"
    _icon_dir = "resources/saas/elasticcloud"


class Cloud(_ElasticCloud):
    _icon = "cloud.png"


# Aliases
