# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Git(_Saas):
    _type = "git"
    _icon_dir = "resources/saas/git"


class Bitbucket(_Git):
    _icon = "bitbucket.png"


class Github(_Git):
    _icon = "github.png"


class Gitlab(_Git):
    _icon = "gitlab.png"


# Aliases
