# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Issues(_Saas):
    _type = "issues"
    _icon_dir = "resources/saas/issues"


class ZenHub(_Issues):
    _icon = "zenhub.png"


# Aliases
