# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Office365(_Saas):
    _type = "office365"
    _icon_dir = "resources/saas/office365"


class Access(_Office365):
    _icon = "access.png"


class Excel(_Office365):
    _icon = "excel.png"


class Exchange(_Office365):
    _icon = "exchange.png"


class Forms(_Office365):
    _icon = "forms.png"


class Kaizala(_Office365):
    _icon = "kaizala.png"


class Office(_Office365):
    _icon = "office.png"


class Onedrive(_Office365):
    _icon = "onedrive.png"


class Onenote(_Office365):
    _icon = "onenote.png"


class Outlook(_Office365):
    _icon = "outlook.png"


class Planner(_Office365):
    _icon = "planner.png"


class Powerpoint(_Office365):
    _icon = "powerpoint.png"


class Project(_Office365):
    _icon = "project.png"


class Publisher(_Office365):
    _icon = "publisher.png"


class Sharepoint(_Office365):
    _icon = "sharepoint.png"


class Skype(_Office365):
    _icon = "skype.png"


class Stream(_Office365):
    _icon = "stream.png"


class Sway(_Office365):
    _icon = "sway.png"


class Teams(_Office365):
    _icon = "teams.png"


class Todo(_Office365):
    _icon = "todo.png"


class Visio(_Office365):
    _icon = "visio.png"


class Word(_Office365):
    _icon = "word.png"


class Yammer(_Office365):
    _icon = "yammer.png"


# Aliases
