# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Saas(_Saas):
    _type = "saas"
    _icon_dir = "resources/saas/saas"


class Saas(_Saas):
    _icon = "saas.png"


# Aliases
