# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Search(_Saas):
    _type = "search"
    _icon_dir = "resources/saas/search"


class Algolia(_Search):
    _icon = "algolia.png"


# Aliases
