# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Security(_Saas):
    _type = "alerting"
    _icon_dir = "resources/saas/security"


class Sonarqube(_Security):
    _icon = "sonarqube.png"


# Aliases
