# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Security(_Saas):
    _type = "security"
    _icon_dir = "resources/saas/security"


class Endpoint(_Security):
    _icon = "endpoint.png"


class Security(_Security):
    _icon = "security.png"


class Siem(_Security):
    _icon = "siem.png"


# Aliases
