# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Volcengine


class _Application(_Volcengine):
    _type = "application"
    _icon_dir = "resources/volcengine/application"


class ApiGateway(_Application):
    _icon = "api-gateway.png"


class CloudSearch(_Application):
    _icon = "cloud-search.png"


class TorchLogService(_Application):
    _icon = "torch-log-service.png"


# Aliases

APIG = ApiGateway
TLS = TorchLogService
