# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Volcengine


class _Compute(_Volcengine):
    _type = "compute"
    _icon_dir = "resources/volcengine/compute"


class AutoScaling(_Compute):
    _icon = "auto-scaling.png"


class ContainerRegistry(_Compute):
    _icon = "container-registry.png"


class ElasticComputeService(_Compute):
    _icon = "elastic-compute-service.png"


class FunctionAsAService(_Compute):
    _icon = "function-as-a-service.png"


class MicroservicesEngine(_Compute):
    _icon = "microservices-engine.png"


class VolcengineKubernetesEngine(_Compute):
    _icon = "volcengine-kubernetes-engine.png"


# Aliases

AS = AutoScaling
CR = ContainerRegistry
ECS = ElasticComputeService
MSE = MicroservicesEngine
VKE = VolcengineKubernetesEngine
FaaS = FunctionAsAService
