# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Volcengine


class _Database(_Volcengine):
    _type = "database"
    _icon_dir = "resources/volcengine/database"


class Hbase(_Database):
    _icon = "hbase.png"


class Mongodb(_Database):
    _icon = "mongodb.png"


class Mysql(_Database):
    _icon = "mysql.png"


class Postgresql(_Database):
    _icon = "postgresql.png"


class Redis(_Database):
    _icon = "redis.png"


# Aliases
