# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Volcengine


class _Integration(_Volcengine):
    _type = "integration"
    _icon_dir = "resources/volcengine/integration"


class Kafka(_Integration):
    _icon = "kafka.png"


class Rabbitmq(_Integration):
    _icon = "rabbitmq.png"


class Rocketmq(_Integration):
    _icon = "rocketmq.png"


# Aliases
