# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Volcengine


class _Network(_Volcengine):
    _type = "network"
    _icon_dir = "resources/volcengine/network"


class Cdn(_Network):
    _icon = "cdn.png"


class ClassicLoadBalancer(_Network):
    _icon = "classic-load-balancer.png"


class CloudEnterpriseNetwork(_Network):
    _icon = "cloud-enterprise-network.png"


class ElasticIpAddress(_Network):
    _icon = "elastic-ip-address.png"


class NatGateway(_Network):
    _icon = "nat-gateway.png"


class VirtualPrivateCloud(_Network):
    _icon = "virtual-private-cloud.png"


class Vpn(_Network):
    _icon = "vpn.png"


# Aliases

CEN = CloudEnterpriseNetwork
EIP = ElasticIpAddress
NAT = NatGateway
VPC = VirtualPrivateCloud
CLB = ClassicLoadBalancer
