# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Volcengine


class _Security(_Volcengine):
    _type = "security"
    _icon_dir = "resources/volcengine/security"


class BastionHost(_Security):
    _icon = "bastion-host.png"


class CloudFirewall(_Security):
    _icon = "cloud-firewall.png"


class WebApplicationFirewall(_Security):
    _icon = "web-application-firewall.png"


# Aliases

WAF = WebApplicationFirewall
