# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Volcengine


class _Storage(_Volcengine):
    _type = "storage"
    _icon_dir = "resources/volcengine/storage"


class ElasticBlockStorage(_Storage):
    _icon = "elastic-block-storage.png"


class ElasticFileStorage(_Storage):
    _icon = "elastic-file-storage.png"


class FileNas(_Storage):
    _icon = "file-nas.png"


class TorchObjectStorage(_Storage):
    _icon = "torch-object-storage.png"


# Aliases

TOS = TorchObjectStorage
EBS = ElasticBlockStorage
EFS = ElasticFileStorage
