# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Volcengine


class _Web(_Volcengine):
    _type = "web"
    _icon_dir = "resources/volcengine/web"


class Dns(_Web):
    _icon = "dns.png"


class Domain(_Web):
    _icon = "domain.png"


# Aliases
