# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _DigitalOcean


class _DigitalOcean(_DigitalOcean):
    _type = "digitalocean"
    _icon_dir = "resources/digitalocean/digitalocean"


class DigitalOcean(_DigitalOcean):
    _icon = "digitalocean.png"


# Aliases
