# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Snowflake


class _Bugworkload(_Snowflake):
    _type = "bugworkload"
    _icon_dir = "resources/snowflake/bugworkload"


class AiMl(_Bugworkload):
    _icon = "ai-ml.png"


class Applications(_Bugworkload):
    _icon = "applications.png"


class Collaboration(_Bugworkload):
    _icon = "collaboration.png"


class Cybersecurity(_Bugworkload):
    _icon = "cybersecurity.png"


class DataEngineering(_Bugworkload):
    _icon = "data-engineering.png"


class DataLake(_Bugworkload):
    _icon = "data-lake.png"


class DataWarehouse(_Bugworkload):
    _icon = "data-warehouse.png"


class Unistore(_Bugworkload):
    _icon = "unistore.png"


# Aliases
