# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Snowflake


class _Workload(_Snowflake):
    _type = "workload"
    _icon_dir = "resources/snowflake/workload"


class AiMl(_Workload):
    _icon = "ai-ml.png"


class Applications(_Workload):
    _icon = "applications.png"


class Collaboration(_Workload):
    _icon = "collaboration.png"


class Cybersecurity(_Workload):
    _icon = "cybersecurity.png"


class DataEngineering(_Workload):
    _icon = "data-engineering.png"


class DataLake(_Workload):
    _icon = "data-lake.png"


class DataWarehouse(_Workload):
    _icon = "data-warehouse.png"


class Unistore(_Workload):
    _icon = "unistore.png"


# Aliases
