# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Aci


class _Fabricnode(_Aci):
    _type = "fabricnode"
    _icon_dir = "resources/aci/fabricnode"


class Apic_Blue(_Fabricnode):
    _icon = "apic_blue.png"


class Apic_Brown(_Fabricnode):
    _icon = "apic_brown.png"


class Apic_Cyan(_Fabricnode):
    _icon = "apic_cyan.png"


class Apic_Darkblue(_Fabricnode):
    _icon = "apic_darkblue.png"


class Apic_Darkyellow(_Fabricnode):
    _icon = "apic_darkyellow.png"


class Apic_Gray(_Fabricnode):
    _icon = "apic_gray.png"


class Apic_Green(_Fabricnode):
    _icon = "apic_green.png"


class Apic_Orange(_Fabricnode):
    _icon = "apic_orange.png"


class Apic_Red(_Fabricnode):
    _icon = "apic_red.png"


class Apic_Yellow(_Fabricnode):
    _icon = "apic_yellow.png"


class Leaf_Blue(_Fabricnode):
    _icon = "leaf_blue.png"


class Leaf_Brown(_Fabricnode):
    _icon = "leaf_brown.png"


class Leaf_Cyan(_Fabricnode):
    _icon = "leaf_cyan.png"


class Leaf_Darkblue(_Fabricnode):
    _icon = "leaf_darkblue.png"


class Leaf_Darkyellow(_Fabricnode):
    _icon = "leaf_darkyellow.png"


class Leaf_Gray(_Fabricnode):
    _icon = "leaf_gray.png"


class Leaf_Orange(_Fabricnode):
    _icon = "leaf_orange.png"


class Leaf_Red(_Fabricnode):
    _icon = "leaf_red.png"


class Leaf_Yellow(_Fabricnode):
    _icon = "leaf_yellow.png"


class Spine_Blue(_Fabricnode):
    _icon = "spine_blue.png"


class Spine_Brown(_Fabricnode):
    _icon = "spine_brown.png"


class Spine_Cyan(_Fabricnode):
    _icon = "spine_cyan.png"


class Spine_Darkblue(_Fabricnode):
    _icon = "spine_darkblue.png"


class Spine_Darkyellow(_Fabricnode):
    _icon = "spine_darkyellow.png"


class Spine_Gray(_Fabricnode):
    _icon = "spine_gray.png"


class Spine_Green(_Fabricnode):
    _icon = "spine_green.png"


class Spine_Orange(_Fabricnode):
    _icon = "spine_orange.png"


class Spine_Red(_Fabricnode):
    _icon = "spine_red.png"


class Spine_Yellow(_Fabricnode):
    _icon = "spine_yellow.png"


# Aliases

apic_blue = apic
leaf_blue = leaf
spine_blue = spine
