# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Aci


class _Logical(_Aci):
    _type = "logical"
    _icon_dir = "resources/aci/logical"


class Contract(_Logical):
    _icon = "contract.png"


class Epg(_Logical):
    _icon = "epg.png"


class Epg_Microseg(_Logical):
    _icon = "epg_microseg.png"


class L2Out(_Logical):
    _icon = "l2out.png"


class L3Out(_Logical):
    _icon = "l3out.png"


class Vrf(_Logical):
    _icon = "vrf.png"


class Vzany(_Logical):
    _icon = "vzany.png"


# Aliases
