# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Splunk


class _Cluster(_Splunk):
    _type = "cluster"
    _icon_dir = "resources/splunk/cluster"

class app(_Cluster):
	_icon = "app.png"

class Deployer(_Cluster):
	_icon = "deployer.png"

class es(_Cluster):
	_icon = "es.png"

class forwarder(_Cluster):
	_icon = "forwarder.png"

class hec(_Cluster):
	_icon = "hec.png"

class license_master(_Cluster):
	_icon = "license-master.png"

class master_cluster_node(_Cluster):
	_icon = "master-cluster-node.png"

class router(_Cluster):
	_icon = "router.png"

class sh_cluster(_Cluster):
	_icon = "sh-cluster.png"

class systems_linux(_Cluster):
	_icon = "systems-linux.png"

class bucket(_Cluster):
	_icon = "bucket.png"

class deployment_server(_Cluster):
	_icon = "deployment-server.png"

class es_server(_Cluster):
	_icon = "es-server.png"

class heavy_forwader(_Cluster):
	_icon = "heavy-forwader.png"

class indexer(_Cluster):
	_icon = "indexer.png"

class license_server(_Cluster):
	_icon = "license-server.png"

class people(_Cluster):
	_icon = "people.png"

class search_head(_Cluster):
	_icon = "search-head.png"

class splunk_cloud(_Cluster):
	_icon = "splunk-cloud.png"

class systems(_Cluster):
	_icon = "systems.png"

class datastores(_Cluster):
	_icon = "datastores.png"

class desktop(_Cluster):
	_icon = "desktop.png"

class firewall(_Cluster):
	_icon = "firewall.png"

class heavy_forwarders(_Cluster):
	_icon = "heavy-forwarders.png"

class laptop(_Cluster):
	_icon = "laptop.png"

class log_file(_Cluster):
	_icon = "log-file.png"

class person(_Cluster):
	_icon = "person.png"

class search(_Cluster):
	_icon = "search.png"

class splunk_instance(_Cluster):
	_icon = "splunk-instance.png"

class systems_windows(_Cluster):
	_icon = "systems-windows.png"