# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _AlibabaCloud


class _AlibabaCloud(_AlibabaCloud):
    _type = "alibabacloud"
    _icon_dir = "resources/alibabacloud/alibabacloud"


class AlibabaCloud(_AlibabaCloud):
    _icon = "alibabacloud.png"


# Aliases
