# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Kubernetes


class _Chaos(_Kubernetes):
    _type = "chaos"
    _icon_dir = "resources/kubernetes/chaos"


class ChaosMesh(_Chaos):
    _icon = "chaos-mesh.png"


class LitmusChaos(_Chaos):
    _icon = "litmus-chaos.png"


# Aliases
