# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Kubernetes


class _Dns(_Kubernetes):
    _type = "dns"
    _icon_dir = "resources/kubernetes/dns"


class ExternalDns(_Dns):
    _icon = "external-dns.png"


# Aliases
