# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Kubernetes


class _Packaging(_Kubernetes):
    _type = "packaging"
    _icon_dir = "resources/kubernetes/packaging"


class Helm(_Packaging):
    _icon = "helm.png"


class Krew(_Packaging):
    _icon = "krew.png"


class Kustomize(_Packaging):
    _icon = "kustomize.png"


# Aliases
