# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Kubernetes


class _Storage(_Kubernetes):
    _type = "storage"
    _icon_dir = "resources/kubernetes/storage"


class Openebs(_Storage):
    _icon = "openebs.png"


class Rook(_Storage):
    _icon = "rook.png"


# Aliases
