# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _K8S


class _Dns(_K8S):
    _type = "dns"
    _icon_dir = "resources/k8s/dns"


class ExternalDns(_Dns):
    _icon = "external-dns.png"


# Aliases
