# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _K8S


class _K8S(_K8S):
    _type = "k8s"
    _icon_dir = "resources/k8s/k8s"


class K8S(_K8S):
    _icon = "k8s.png"


# Aliases
