# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _K8S


class _Packaging(_K8S):
    _type = "packaging"
    _icon_dir = "resources/k8s/packaging"


class Helm(_Packaging):
    _icon = "helm.png"


class Krew(_Packaging):
    _icon = "krew.png"


class Kustomize(_Packaging):
    _icon = "kustomize.png"


# Aliases
