# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Elastic


class _Agent(_Elastic):
    _type = "agent"
    _icon_dir = "resources/elastic/agent"


class Agent(_Agent):
    _icon = "agent.png"


class Endpoint(_Agent):
    _icon = "endpoint.png"


class Fleet(_Agent):
    _icon = "fleet.png"


class Integrations(_Agent):
    _icon = "integrations.png"


# Aliases
