# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Elastic


class _Elastic(_Elastic):
    _type = "elastic"
    _icon_dir = "resources/elastic/elastic"


class Elastic(_Elastic):
    _icon = "elastic.png"


# Aliases
