# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Camunda


class _Automate(_Camunda):
    _type = "automate"
    _icon_dir = "resources/camunda/automate"


class Decision(_Automate):
    _icon = "decision.png"


class Forms(_Automate):
    _icon = "forms.png"


class Operate(_Automate):
    _icon = "operate.png"


class Tasklist(_Automate):
    _icon = "tasklist.png"


class Workflow(_Automate):
    _icon = "workflow.png"


# Aliases
