# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Camunda


class _Logo(_Camunda):
    _type = "logo"
    _icon_dir = "resources/camunda/logo"


class Dark(_Logo):
    _icon = "dark.png"


class Light(_Logo):
    _icon = "light.png"


class Orange(_Logo):
    _icon = "orange.png"


# Aliases
