# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Camunda


class _Monitor(_Camunda):
    _type = "monitor"
    _icon_dir = "resources/camunda/monitor"


class Optimize(_Monitor):
    _icon = "optimize.png"


# Aliases
