# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OpenStack


class _OpenStack(_OpenStack):
    _type = "openstack"
    _icon_dir = "resources/openstack/openstack"


class OpenStack(_OpenStack):
    _icon = "openstack.png"


# Aliases
