# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Confluent


class _Streaming(_Confluent):
    _type = "streaming"
    _icon_dir = "resources/confluent/streaming"


class Confluent(_Streaming):
    _icon = "confluent.png"


class Ksql(_Streaming):
    _icon = "ksql.png"


# Aliases
