# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _AWS


class _AWS(_AWS):
    _type = "aws"
    _icon_dir = "resources/aws/aws"


class AWS(_AWS):
    _icon = "aws.png"


# Aliases
