# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Huaweicloud


class _Ai_Analytics(_Huaweicloud):
    _type = "ai_analytics"
    _icon_dir = "resources/huaweicloud/ai_analytics"


class AIS(_Ai_Analytics):
    _icon = "ais.png"


class Campus(_Ai_Analytics):
    _icon = "campus.png"


class CDM(_Ai_Analytics):
    _icon = "cdm.png"


class CloudTable(_Ai_Analytics):
    _icon = "cloud-table.png"


class CS(_Ai_Analytics):
    _icon = "cs.png"


class DataAccess(_Ai_Analytics):
    _icon = "data-access.png"


class DataArts(_Ai_Analytics):
    _icon = "data-arts.png"


class DGC(_Ai_Analytics):
    _icon = "dgc.png"


class DLI(_Ai_Analytics):
    _icon = "dli.png"


class DWS(_Ai_Analytics):
    _icon = "dws.png"


class GES(_Ai_Analytics):
    _icon = "ges.png"


class Hilens(_Ai_Analytics):
    _icon = "hilens.png"


class Image(_Ai_Analytics):
    _icon = "image.png"


class Imagetagging(_Ai_Analytics):
    _icon = "imagetagging.png"


class Industriai(_Ai_Analytics):
    _icon = "industriai.png"


class Log(_Ai_Analytics):
    _icon = "log.png"


class Logistics(_Ai_Analytics):
    _icon = "logistics.png"


class MLS(_Ai_Analytics):
    _icon = "mls.png"


class ModelArts(_Ai_Analytics):
    _icon = "model-arts.png"


class MRS(_Ai_Analytics):
    _icon = "mrs.png"


class NLP(_Ai_Analytics):
    _icon = "nlp.png"


class Roc(_Ai_Analytics):
    _icon = "roc.png"


class Traffic(_Ai_Analytics):
    _icon = "traffic.png"


# Aliases

MA = ModelArts
MapReduceService = MRS
ArificalIntelligenceService = AIS
CloudStreamingService = CS
DataLakeInsight = DLI
CloudDataMigrationService = CDM
NaturalLanguageProcessingService = NLP
MachineLearningService = MLS
DataWarehouseService = DWS
