# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Huaweicloud


class _Application(_Huaweicloud):
    _type = "application"
    _icon_dir = "resources/huaweicloud/application"


class CAE(_Application):
    _icon = "cae.png"


class CSE(_Application):
    _icon = "cse.png"


class DMS(_Application):
    _icon = "dms.png"


class ECPC(_Application):
    _icon = "ecpc.png"


class FunctionStage(_Application):
    _icon = "function-stage.png"


class Memcached(_Application):
    _icon = "memcached.png"


class ServiceStage(_Application):
    _icon = "service-stage.png"


class SMN(_Application):
    _icon = "smn.png"


# Aliases
