# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Huaweicloud


class _Blockchain(_Huaweicloud):
    _type = "blockchain"
    _icon_dir = "resources/huaweicloud/blockchain"


class BCS(_Blockchain):
    _icon = "bcs.png"


# Aliases

BlockChainService = BCS
