# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Huaweicloud


class _Communication(_Huaweicloud):
    _type = "communication"
    _icon_dir = "resources/huaweicloud/communication"


class CloudIpcc(_Communication):
    _icon = "cloud-ipcc.png"


class CloudPbx(_Communication):
    _icon = "cloud-pbx.png"


class IM(_Communication):
    _icon = "im.png"


class MSGSMS(_Communication):
    _icon = "msgsms.png"


class VoiceCall(_Communication):
    _icon = "voice-call.png"


# Aliases
