# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Huaweicloud


class _Compute(_Huaweicloud):
    _type = "compute"
    _icon_dir = "resources/huaweicloud/compute"


class AutoScaling(_Compute):
    _icon = "auto-scaling.png"


class BareMetalServer(_Compute):
    _icon = "bare-metal-server.png"


class CloudContainerEngine(_Compute):
    _icon = "cloud-container-engine.png"


class DedicatedCloud(_Compute):
    _icon = "dedicated-cloud.png"


class DedicatedHost(_Compute):
    _icon = "dedicated-host.png"


class ElasticComputeService(_Compute):
    _icon = "elastic-compute-service.png"


class ImageService(_Compute):
    _icon = "image-service.png"


# Aliases

AS = AutoScaling
BMS = BareMetalServer
CCE = CloudContainerEngine
DeH = DedicatedHost
DeC = DedicatedCloud
ECS = ElasticComputeService
IMS = ImageService
