# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Huaweicloud


class _Container(_Huaweicloud):
    _type = "container"
    _icon_dir = "resources/huaweicloud/container"


class AOS(_Container):
    _icon = "aos.png"


class CCE(_Container):
    _icon = "cce.png"


class CCI(_Container):
    _icon = "cci.png"


class SWR(_Container):
    _icon = "swr.png"


# Aliases

ApplicationOrchestrationService = AOS
CloudContainerEngine = CCE
CloudContainerInstance = CCI
SoftwareRepository = SWR
