# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Huaweicloud


class _Edge(_Huaweicloud):
    _type = "edge"
    _icon_dir = "resources/huaweicloud/edge"


class CDN(_Edge):
    _icon = "cdn.png"


class IEC(_Edge):
    _icon = "iec.png"


class IEF(_Edge):
    _icon = "ief.png"


class IES(_Edge):
    _icon = "ies.png"


class WSA(_Edge):
    _icon = "wsa.png"


# Aliases

IntelligentEdgeFabric = IEF
IntelligentEdgeSite = IES
WholeSiteAcceleration = WSA
IntelligentEdgeCloud = IEC
