# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Huaweicloud


class _Iot(_Huaweicloud):
    _type = "iot"
    _icon_dir = "resources/huaweicloud/iot"


class GSL(_Iot):
    _icon = "gsl.png"


class IotAnalytics(_Iot):
    _icon = "iot-analytics.png"


class IotDeviceAccess(_Iot):
    _icon = "iot-device-access.png"


class IotMessageQueue(_Iot):
    _icon = "iot-message-queue.png"


class IotPlatform(_Iot):
    _icon = "iot-platform.png"


class IotStage(_Iot):
    _icon = "iot-stage.png"


class IotStudio(_Iot):
    _icon = "iot-studio.png"


# Aliases
