# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Huaweicloud


class _Security(_Huaweicloud):
    _type = "security"
    _icon_dir = "resources/huaweicloud/security"


class AAD(_Security):
    _icon = "aad.png"


class AAG(_Security):
    _icon = "aag.png"


class AntiDdos(_Security):
    _icon = "anti-ddos.png"


class ARS(_Security):
    _icon = "ars.png"


class DBSS(_Security):
    _icon = "dbss.png"


class HIDS(_Security):
    _icon = "hids.png"


class HSS(_Security):
    _icon = "hss.png"


class HVD(_Security):
    _icon = "hvd.png"


class HWAF(_Security):
    _icon = "hwaf.png"


class KMS(_Security):
    _icon = "kms.png"


class PTS(_Security):
    _icon = "pts.png"


class SAS(_Security):
    _icon = "sas.png"


class SCA(_Security):
    _icon = "sca.png"


class SCS(_Security):
    _icon = "scs.png"


class SSA(_Security):
    _icon = "ssa.png"


class WAF(_Security):
    _icon = "waf.png"


class WTP(_Security):
    _icon = "wtp.png"


# Aliases
