# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Huaweicloud


class _Storage(_Huaweicloud):
    _type = "storage"
    _icon_dir = "resources/huaweicloud/storage"


class CDN(_Storage):
    _icon = "cdn.png"


class CSBS(_Storage):
    _icon = "csbs.png"


class DES(_Storage):
    _icon = "des.png"


class DESS(_Storage):
    _icon = "dess.png"


class DSS(_Storage):
    _icon = "dss.png"


class EVS(_Storage):
    _icon = "evs.png"


class OBS(_Storage):
    _icon = "obs.png"


class SFS(_Storage):
    _icon = "sfs.png"


class VBS(_Storage):
    _icon = "vbs.png"


# Aliases

ObjectStorageService = OBS
ContentDeliveryNetwork = CDN
ElasticVolumeService = EVS
StorageFileSystem = SFS
CloudServerBackupService = CSBS
DataExpressService = DES
DedicatedEnterpriseStorageService = DESS
VolumeBackupService = VBS
DedicatedStorageService = DSS
