# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Huaweicloud


class _Video(_Huaweicloud):
    _type = "video"
    _icon_dir = "resources/huaweicloud/video"


class LIVE(_Video):
    _icon = "live.png"


class MPC(_Video):
    _icon = "mpc.png"


class RTC(_Video):
    _icon = "rtc.png"


class VIS(_Video):
    _icon = "vis.png"


class VOD(_Video):
    _icon = "vod.png"


# Aliases
