# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Analytics(_IBM):
    _type = "analytics"
    _icon_dir = "resources/ibm/analytics"


class AccountScore(_Analytics):
    _icon = "account-score.png"


class AnalyticsEngine(_Analytics):
    _icon = "analytics-engine.png"


class Cognos(_Analytics):
    _icon = "cognos.png"


class Match360(_Analytics):
    _icon = "match-360.png"


class Powerlytics(_Analytics):
    _icon = "powerlytics.png"


class Streaming(_Analytics):
    _icon = "streaming.png"


# Aliases
