# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Blockchain(_IBM):
    _type = "blockchain"
    _icon_dir = "resources/ibm/blockchain"


class Blockchain(_Blockchain):
    _icon = "blockchain.png"


# Aliases
