# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Compute(_IBM):
    _type = "compute"
    _icon_dir = "resources/ibm/compute"


class Autoscale(_Compute):
    _icon = "autoscale.png"


class BareMetal(_Compute):
    _icon = "bare-metal.png"


class Citrix(_Compute):
    _icon = "citrix.png"


class CloudFoundry(_Compute):
    _icon = "cloud-foundry.png"


class CodeEngine(_Compute):
    _icon = "code-engine.png"


class DedicatedHost(_Compute):
    _icon = "dedicated-host.png"


class Dizzion(_Compute):
    _icon = "dizzion.png"


class Functions(_Compute):
    _icon = "functions.png"


class HpVirtualServers(_Compute):
    _icon = "hp-virtual-servers.png"


class Hsm(_Compute):
    _icon = "hsm.png"


class PowerSystems(_Compute):
    _icon = "power-systems.png"


class Satellite(_Compute):
    _icon = "satellite.png"


class Skytap(_Compute):
    _icon = "skytap.png"


class VirtualServer(_Compute):
    _icon = "virtual-server.png"


class Vmware(_Compute):
    _icon = "vmware.png"


class VpcVirtualServer(_Compute):
    _icon = "vpc-virtual-server.png"


# Aliases
