# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Container(_IBM):
    _type = "container"
    _icon_dir = "resources/ibm/container"


class CodeEngine(_Container):
    _icon = "code-engine.png"


class Kubernets(_Container):
    _icon = "kubernets.png"


class Openshift(_Container):
    _icon = "openshift.png"


class Registry(_Container):
    _icon = "registry.png"


# Aliases
