# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Ibm


class _Containers(_Ibm):
    _type = "containers"
    _icon_dir = "resources/ibm/containers"


class CodeEngine(_Containers):
    _icon = "code-engine.png"


class Kubernets(_Containers):
    _icon = "kubernets.png"


class Openshift(_Containers):
    _icon = "openshift.png"


class Registry(_Containers):
    _icon = "registry.png"


# Aliases
