# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Database(_IBM):
    _type = "database"
    _icon_dir = "resources/ibm/database"


class Cloudant(_Database):
    _icon = "cloudant.png"


class ComposeEnterprise(_Database):
    _icon = "compose-enterprise.png"


class ComposeJanusgraph(_Database):
    _icon = "compose-janusgraph.png"


class ComposeMysql(_Database):
    _icon = "compose-mysql.png"


class ComposeRethinkdb(_Database):
    _icon = "compose-rethinkdb.png"


class ComposeScylladb(_Database):
    _icon = "compose-scylladb.png"


class Datastax(_Database):
    _icon = "datastax.png"


class Db2Warehouse(_Database):
    _icon = "db2-warehouse.png"


class Db2(_Database):
    _icon = "db2.png"


class Edb(_Database):
    _icon = "edb.png"


class Elasticsearch(_Database):
    _icon = "elasticsearch.png"


class Etcd(_Database):
    _icon = "etcd.png"


class HyperProtectDbaas(_Database):
    _icon = "hyper-protect-dbaas.png"


class Influx(_Database):
    _icon = "influx.png"


class Informix(_Database):
    _icon = "informix.png"


class Match(_Database):
    _icon = "match.png"


class Mongodb(_Database):
    _icon = "mongodb.png"


class Portworx(_Database):
    _icon = "portworx.png"


class Postgresql(_Database):
    _icon = "postgresql.png"


class Rabbitmq(_Database):
    _icon = "rabbitmq.png"


class Redis(_Database):
    _icon = "redis.png"


class SqlQuery(_Database):
    _icon = "sql-query.png"


# Aliases
