# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Devtools(_IBM):
    _type = "devtools"
    _icon_dir = "resources/ibm/devtools"


class Accern(_Devtools):
    _icon = "accern.png"


class Alloy(_Devtools):
    _icon = "alloy.png"


class ApiGateway(_Devtools):
    _icon = "api-gateway.png"


class AppConfiguration(_Devtools):
    _icon = "app-configuration.png"


class Bondevalue(_Devtools):
    _icon = "bondevalue.png"


class ContinuousDelivery(_Devtools):
    _icon = "continuous-delivery.png"


class Difitek(_Devtools):
    _icon = "difitek.png"


class DomainNameRegistration(_Devtools):
    _icon = "domain-name-registration.png"


class Dwolla(_Devtools):
    _icon = "dwolla.png"


class Esri(_Devtools):
    _icon = "esri.png"


class GeoWs(_Devtools):
    _icon = "geo-ws.png"


class Hazardhub(_Devtools):
    _icon = "hazardhub.png"


class HealthScore(_Devtools):
    _icon = "health-score.png"


class Hydrogen(_Devtools):
    _icon = "hydrogen.png"


class Morningstar(_Devtools):
    _icon = "morningstar.png"


class NaturalLanguageGeneration(_Devtools):
    _icon = "natural-language-generation.png"


class Nexmo(_Devtools):
    _icon = "nexmo.png"


class Powerlytics(_Devtools):
    _icon = "powerlytics.png"


class Quovo(_Devtools):
    _icon = "quovo.png"


class Rainbow(_Devtools):
    _icon = "rainbow.png"


class Relsci(_Devtools):
    _icon = "relsci.png"


class RiskEngine(_Devtools):
    _icon = "risk-engine.png"


class Schematics(_Devtools):
    _icon = "schematics.png"


class Sendgrid(_Devtools):
    _icon = "sendgrid.png"


class Sizeup(_Devtools):
    _icon = "sizeup.png"


class Splice(_Devtools):
    _icon = "splice.png"


class Strands(_Devtools):
    _icon = "strands.png"


class Toolchains(_Devtools):
    _icon = "toolchains.png"


class TotumRisk(_Devtools):
    _icon = "totum-risk.png"


class Tradeit(_Devtools):
    _icon = "tradeit.png"


class Twilio(_Devtools):
    _icon = "twilio.png"


class Ucloud(_Devtools):
    _icon = "ucloud.png"


class Wealthengine(_Devtools):
    _icon = "wealthengine.png"


class WireAccountVerificationService(_Devtools):
    _icon = "wire-account-verification-service.png"


class Xignite(_Devtools):
    _icon = "xignite.png"


class Ylabs(_Devtools):
    _icon = "ylabs.png"


class Yodlee(_Devtools):
    _icon = "yodlee.png"


# Aliases
