# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _General(_IBM):
    _type = "general"
    _icon_dir = "resources/ibm/general"


class Cloudservices(_General):
    _icon = "CloudServices.png"


class Enterprise(_General):
    _icon = "Enterprise.png"


class Enterprise2(_General):
    _icon = "Enterprise2.png"


class Internet(_General):
    _icon = "Internet.png"


class Browser(_General):
    _icon = "browser.png"


class CloudMessaging(_General):
    _icon = "cloud-messaging.png"


class Cloudant(_General):
    _icon = "cloudant.png"


class CognitiveServices(_General):
    _icon = "cognitive-services.png"


class DataSecurity(_General):
    _icon = "data-security.png"


class Device(_General):
    _icon = "device.png"


class GovernanceRiskCompliance(_General):
    _icon = "governance-risk-compliance.png"


class IBMPublicCloud(_General):
    _icon = "ibm-public-cloud.png"


class IdentityAccessManagement(_General):
    _icon = "identity-access-management.png"


class IdentityProvider(_General):
    _icon = "identity-provider.png"


class InfrastructureSecurity(_General):
    _icon = "infrastructure-security.png"


class IntegratedDigitalExperiences(_General):
    _icon = "integrated-digital-experiences.png"


class IotCloud(_General):
    _icon = "iot-cloud.png"


class MicroservicesApplication(_General):
    _icon = "microservices-application.png"


class MicroservicesMesh(_General):
    _icon = "microservices-mesh.png"


class MonitoringLogging(_General):
    _icon = "monitoring-logging.png"


class Monitoring(_General):
    _icon = "monitoring.png"


class PhysicalEntity(_General):
    _icon = "physical-entity.png"


class Sensor(_General):
    _icon = "sensor.png"


class ServiceDiscoveryConfiguration(_General):
    _icon = "service-discovery-configuration.png"


class TransformationConnectivity(_General):
    _icon = "transformation-connectivity.png"


class User(_General):
    _icon = "user.png"


# Aliases
