# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _IBM(_IBM):
    _type = "ibm"
    _icon_dir = "resources/ibm/ibm"


class IBM(_IBM):
    _icon = "ibm.png"


# Aliases
