# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Integration(_IBM):
    _type = "integration"
    _icon_dir = "resources/ibm/integration"


class ApiConnect(_Integration):
    _icon = "api-connect.png"


class AppConnect(_Integration):
    _icon = "app-connect.png"


class EventStreams(_Integration):
    _icon = "event-streams.png"


class Lift(_Integration):
    _icon = "lift.png"


class Mq(_Integration):
    _icon = "mq.png"


class RocketMainframe(_Integration):
    _icon = "rocket-mainframe.png"


class SecureGateway(_Integration):
    _icon = "secure-gateway.png"


class SimpleCloudIo(_Integration):
    _icon = "simple-cloud-io.png"


# Aliases
