# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Ibm


class _Iot(_Ibm):
    _type = "iot"
    _icon_dir = "resources/ibm/iot"


class BoschRollouts(_Iot):
    _icon = "bosch-rollouts.png"


class CarDiagnostic(_Iot):
    _icon = "car-diagnostic.png"


class DataPlans(_Iot):
    _icon = "data-plans.png"


class Flow(_Iot):
    _icon = "flow.png"


class IotPlatform(_Iot):
    _icon = "iot-platform.png"


class Portworx(_Iot):
    _icon = "portworx.png"


class Skyhook(_Iot):
    _icon = "skyhook.png"


class UnificationEngine(_Iot):
    _icon = "unification-engine.png"


# Aliases
