# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Logging(_IBM):
    _type = "logging"
    _icon_dir = "resources/ibm/logging"


class ActivityTracker(_Logging):
    _icon = "activity-tracker.png"


class LogAnalysis(_Logging):
    _icon = "log-analysis.png"


class Monitoring(_Logging):
    _icon = "monitoring.png"


# Aliases
