# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Migration(_IBM):
    _type = "migration"
    _icon_dir = "resources/ibm/migration"


class CloudMigration(_Migration):
    _icon = "cloud-migration.png"


# Aliases
