# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Ml(_IBM):
    _type = "ml"
    _icon_dir = "resources/ibm/ml"


class Annotator(_Ml):
    _icon = "annotator.png"


class KnowledgeStudio(_Ml):
    _icon = "knowledge-studio.png"


class LanguageTranslator(_Ml):
    _icon = "language-translator.png"


class MachineLearning(_Ml):
    _icon = "machine-learning.png"


class Match360(_Ml):
    _icon = "match-360.png"


class NaturalLanguageClassifier(_Ml):
    _icon = "natural-language-classifier.png"


class NaturalLanguageUnderstanding(_Ml):
    _icon = "natural-language-understanding.png"


class PersonalityInsights(_Ml):
    _icon = "personality-insights.png"


class SpeechToText(_Ml):
    _icon = "speech-to-text.png"


class TextToSpeech(_Ml):
    _icon = "text-to-speech.png"


class ToneAnalyzer(_Ml):
    _icon = "tone-analyzer.png"


class WatsonAssistant(_Ml):
    _icon = "watson-assistant.png"


class WatsonDiscovery(_Ml):
    _icon = "watson-discovery.png"


class WatsonKnowledgeCatalog(_Ml):
    _icon = "watson-knowledge-catalog.png"


class WatsonOpenscale(_Ml):
    _icon = "watson-openscale.png"


class WatsonStudio(_Ml):
    _icon = "watson-studio.png"


# Aliases
