# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Mobile(_IBM):
    _type = "mobile"
    _icon_dir = "resources/ibm/mobile"


class B2T(_Mobile):
    _icon = "b2t.png"


class Bitbar(_Mobile):
    _icon = "bitbar.png"


class Match360(_Mobile):
    _icon = "match-360.png"


class Phunware(_Mobile):
    _icon = "phunware.png"


class PushNotifications(_Mobile):
    _icon = "push-notifications.png"


class Telstra(_Mobile):
    _icon = "telstra.png"


class Twilio(_Mobile):
    _icon = "twilio.png"


# Aliases
