# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Ibm


class _Monitoring(_Ibm):
    _type = "monitoring"
    _icon_dir = "resources/ibm/monitoring"


class ActivityTracker(_Monitoring):
    _icon = "activity-tracker.png"


class LogAnalysis(_Monitoring):
    _icon = "log-analysis.png"


class Monitoring(_Monitoring):
    _icon = "monitoring.png"


# Aliases
