# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Network(_IBM):
    _type = "network"
    _icon_dir = "resources/ibm/network"


class CDN(_Network):
    _icon = "cdn.png"


class Cis(_Network):
    _icon = "cis.png"


class DirectLinkConnect(_Network):
    _icon = "direct-link-connect.png"


class DirectLink(_Network):
    _icon = "direct-link.png"


class DNS(_Network):
    _icon = "dns.png"


class Firewall(_Network):
    _icon = "firewall.png"


class IpsecVPN(_Network):
    _icon = "ipsec-vpn.png"


class Lbaas(_Network):
    _icon = "lbaas.png"


class LocalLoadBalancing(_Network):
    _icon = "local-load-balancing.png"


class Subnets(_Network):
    _icon = "subnets.png"


class Transit(_Network):
    _icon = "transit.png"


class VirtualRouterAppliance(_Network):
    _icon = "virtual-router-appliance.png"


class Vlan(_Network):
    _icon = "vlan.png"


class VPCEndpoints(_Network):
    _icon = "vpc-endpoints.png"


class VPCFlowlogs(_Network):
    _icon = "vpc-flowlogs.png"


class VPC(_Network):
    _icon = "vpc.png"


class VPN(_Network):
    _icon = "vpn.png"


# Aliases
