# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Security(_IBM):
    _type = "security"
    _icon_dir = "resources/ibm/security"


class AppId(_Security):
    _icon = "app-id.png"


class CertificateManager(_Security):
    _icon = "certificate-manager.png"


class Contrast(_Security):
    _icon = "contrast.png"


class Crypto(_Security):
    _icon = "crypto.png"


class DataShield(_Security):
    _icon = "data-shield.png"


class Fusionauth(_Security):
    _icon = "fusionauth.png"


class Hsm(_Security):
    _icon = "hsm.png"


class KeyProtect(_Security):
    _icon = "key-protect.png"


class Neuvector(_Security):
    _icon = "neuvector.png"


class OpenBsd(_Security):
    _icon = "open-bsd.png"


class Raxak(_Security):
    _icon = "raxak.png"


class SecretsManager(_Security):
    _icon = "secrets-manager.png"


class SslCertificates(_Security):
    _icon = "ssl-certificates.png"


class Twilio(_Security):
    _icon = "twilio.png"


# Aliases
