# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Storage(_IBM):
    _type = "storage"
    _icon_dir = "resources/ibm/storage"


class Blockstorage(_Storage):
    _icon = "BlockStorage.png"


class Objectstorage(_Storage):
    _icon = "ObjectStorage.png"


# Aliases
