# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Firebase


class _Firebase(_Firebase):
    _type = "firebase"
    _icon_dir = "resources/firebase/firebase"


class Firebase(_Firebase):
    _icon = "firebase.png"


# Aliases
