# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Ai_Machine_Learning(_Azure):
    _type = "ai_machine_learning"
    _icon_dir = "resources/azure/ai_machine_learning"


class BotServices(_Ai_Machine_Learning):
    _icon = "bot-services.png"


class CognitiveServices(_Ai_Machine_Learning):
    _icon = "cognitive-services.png"


class MachineLearningStudioClassicWebServices(_Ai_Machine_Learning):
    _icon = "machine-learning-studio-classic-web-services.png"


class MachineLearningStudioWebServicePlans(_Ai_Machine_Learning):
    _icon = "machine-learning-studio-web-service-plans.png"


class MachineLearningStudioWorkspaces(_Ai_Machine_Learning):
    _icon = "machine-learning-studio-workspaces.png"


class TranslatorText(_Ai_Machine_Learning):
    _icon = "translator-text.png"


# Aliases
