# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Ai_Ml(_Azure):
    _type = "ai_ml"
    _icon_dir = "resources/azure/ai_ml"


class BotServices(_Ai_Ml):
    _icon = "bot-services.png"


class CognitiveServices(_Ai_Ml):
    _icon = "cognitive-services.png"


class MachineLearningStudioClassicWebServices(_Ai_Ml):
    _icon = "machine-learning-studio-classic-web-services.png"


class MachineLearningStudioWebServicePlans(_Ai_Ml):
    _icon = "machine-learning-studio-web-service-plans.png"


class MachineLearningStudioWorkspaces(_Ai_Ml):
    _icon = "machine-learning-studio-workspaces.png"


class TranslatorText(_Ai_Ml):
    _icon = "translator-text.png"


# Aliases
