# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _App_Services(_Azure):
    _type = "app_services"
    _icon_dir = "resources/azure/app_services"


class APIManagementServices(_App_Services):
    _icon = "api-management-services.png"


class AppServiceCertificates(_App_Services):
    _icon = "app-service-certificates.png"


class AppServiceDomains(_App_Services):
    _icon = "app-service-domains.png"


class AppServiceEnvironments(_App_Services):
    _icon = "app-service-environments.png"


class AppServicePlans(_App_Services):
    _icon = "app-service-plans.png"


class AppServices(_App_Services):
    _icon = "app-services.png"


class CDNProfiles(_App_Services):
    _icon = "cdn-profiles.png"


class NotificationHubs(_App_Services):
    _icon = "notification-hubs.png"


class SearchServices(_App_Services):
    _icon = "search-services.png"


# Aliases
