# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Application(_Azure):
    _type = "application"
    _icon_dir = "resources/azure/application"


class AdvancedTools(_Application):
    _icon = "advanced-tools.png"


class APIConnection(_Application):
    _icon = "api-connection.png"


class APIDefinition(_Application):
    _icon = "api-definition.png"


class APIManagementAPI(_Application):
    _icon = "api-management-api.png"


class APIManagementBackend(_Application):
    _icon = "api-management-backend.png"


class APIManagementExternalCache(_Application):
    _icon = "api-management-external-cache.png"


class APIManagementIdentity(_Application):
    _icon = "api-management-identity.png"


class APIManagementManagedIdentity(_Application):
    _icon = "api-management-managed-identity.png"


class APIManagementNamedValue(_Application):
    _icon = "api-management-named-value.png"


class APIManagementOauth20AndOpenidConnect(_Application):
    _icon = "api-management-oauth-20-and-openid-connect.png"


class APIManagementPowerPlatform(_Application):
    _icon = "api-management-power-platform.png"


class APIManagementPricingTier(_Application):
    _icon = "api-management-pricing-tier.png"


class APIManagementProduct(_Application):
    _icon = "api-management-product.png"


class APIPlayground(_Application):
    _icon = "api-playground.png"


class AppConsole(_Application):
    _icon = "app-console.png"


class AppEvent(_Application):
    _icon = "app-event.png"


class AppFunction(_Application):
    _icon = "app-function.png"


class AppLogStream(_Application):
    _icon = "app-log-stream.png"


class AppMetric(_Application):
    _icon = "app-metric.png"


class AppProperty(_Application):
    _icon = "app-property.png"


class AppProxy(_Application):
    _icon = "app-proxy.png"


class AppScaleOut(_Application):
    _icon = "app-scale-out.png"


class AppScaleUp(_Application):
    _icon = "app-scale-up.png"


class AppServiceAdvancedTools(_Application):
    _icon = "app-service-advanced-tools.png"


class AppServiceAdvisor(_Application):
    _icon = "app-service-advisor.png"


class AppServiceAPIDefinition(_Application):
    _icon = "app-service-api-definition.png"


class AppServiceAPIManagement(_Application):
    _icon = "app-service-api-management.png"


class AppServiceAuthentication(_Application):
    _icon = "app-service-authentication.png"


class AppServiceBackup(_Application):
    _icon = "app-service-backup.png"


class AppServiceCloneApp(_Application):
    _icon = "app-service-clone-app.png"


class AppServiceConnector(_Application):
    _icon = "app-service-connector.png"


class AppServiceConsole(_Application):
    _icon = "app-service-console.png"


class AppServiceCustomDomain(_Application):
    _icon = "app-service-custom-domain.png"


class AppServiceDeploymentSlot(_Application):
    _icon = "app-service-deployment-slot.png"


class AppServiceEditor(_Application):
    _icon = "app-service-editor.png"


class AppServiceEvent(_Application):
    _icon = "app-service-event.png"


class AppServiceExportTemplate(_Application):
    _icon = "app-service-export-template.png"


class AppServiceExtension(_Application):
    _icon = "app-service-extension.png"


class AppServiceHealthCheck(_Application):
    _icon = "app-service-health-check.png"


class AppServiceIdentity(_Application):
    _icon = "app-service-identity.png"


class AppServiceInsights(_Application):
    _icon = "app-service-insights.png"


class AppServiceLogStream(_Application):
    _icon = "app-service-log-stream.png"


class AppServiceLog(_Application):
    _icon = "app-service-log.png"


class AppServiceLogs(_Application):
    _icon = "app-service-logs.png"


class AppServiceManagement(_Application):
    _icon = "app-service-management.png"


class AppServiceMysqlInApp(_Application):
    _icon = "app-service-mysql-in-app.png"


class AppServiceNetworking(_Application):
    _icon = "app-service-networking.png"


class AppServiceProcessExplorer(_Application):
    _icon = "app-service-process-explorer.png"


class AppServiceQuickstart(_Application):
    _icon = "app-service-quickstart.png"


class AppServiceQuota(_Application):
    _icon = "app-service-quota.png"


class AppServiceResetPublishProfile(_Application):
    _icon = "app-service-reset-publish-profile.png"


class AppServiceScaleOut(_Application):
    _icon = "app-service-scale-out.png"


class AppServiceScaleUp(_Application):
    _icon = "app-service-scale-up.png"


class AppServiceSecurity(_Application):
    _icon = "app-service-security.png"


class AppServiceStart(_Application):
    _icon = "app-service-start.png"


class AppServiceStop(_Application):
    _icon = "app-service-stop.png"


class AppServiceWebjob(_Application):
    _icon = "app-service-webjob.png"


class AppTask(_Application):
    _icon = "app-task.png"


class ApplicationConfiguration(_Application):
    _icon = "application-configuration.png"


class ApplicationGroup(_Application):
    _icon = "application-group.png"


class ApplicationProxy(_Application):
    _icon = "application-proxy.png"


class ApplicationRegistration(_Application):
    _icon = "application-registration.png"


class ApplicationSecurityGroup(_Application):
    _icon = "application-security-group.png"


class ApplicationServiceAdvisor(_Application):
    _icon = "application-service-advisor.png"


class ApplicationServiceAPIDefinition(_Application):
    _icon = "application-service-api-definition.png"


class ApplicationServiceAuthentication(_Application):
    _icon = "application-service-authentication.png"


class ApplicationServiceCertificate(_Application):
    _icon = "application-service-certificate.png"


class ApplicationServiceCloneApp(_Application):
    _icon = "application-service-clone-app.png"


class ApplicationServiceConsole(_Application):
    _icon = "application-service-console.png"


class ApplicationServiceDeploymentSlot(_Application):
    _icon = "application-service-deployment-slot.png"


class ApplicationServiceDomain(_Application):
    _icon = "application-service-domain.png"


class ApplicationServiceEditor(_Application):
    _icon = "application-service-editor.png"


class ApplicationServiceEnvironment(_Application):
    _icon = "application-service-environment.png"


class ApplicationServiceEvent(_Application):
    _icon = "application-service-event.png"


class ApplicationServiceHealthCheck(_Application):
    _icon = "application-service-health-check.png"


class ApplicationServiceLogStream(_Application):
    _icon = "application-service-log-stream.png"


class ApplicationServiceLog(_Application):
    _icon = "application-service-log.png"


class ApplicationServiceMysqlInApp(_Application):
    _icon = "application-service-mysql-in-app.png"


class ApplicationServiceNetworking(_Application):
    _icon = "application-service-networking.png"


class ApplicationServicePlan(_Application):
    _icon = "application-service-plan.png"


class ApplicationServiceProcessExplorer(_Application):
    _icon = "application-service-process-explorer.png"


class ApplicationServiceQuota(_Application):
    _icon = "application-service-quota.png"


class ApplicationServiceWebjob(_Application):
    _icon = "application-service-webjob.png"


class ApplicationService(_Application):
    _icon = "application-service.png"


class AzureAPIForFhir(_Application):
    _icon = "azure-api-for-fhir.png"


class AzureMapsAccount(_Application):
    _icon = "azure-maps-account.png"


class ChaosExperimentTarget(_Application):
    _icon = "chaos-experiment-target.png"


class ChaosExperiment(_Application):
    _icon = "chaos-experiment.png"


class ChaosStudio(_Application):
    _icon = "chaos-studio.png"


class ClientApplication(_Application):
    _icon = "client-application.png"


class CloudtestAccount(_Application):
    _icon = "cloudtest-account.png"


class CloudtestImage(_Application):
    _icon = "cloudtest-image.png"


class ContainerApp(_Application):
    _icon = "container-app.png"


class Cors(_Application):
    _icon = "cors.png"


class DicomService(_Application):
    _icon = "dicom-service.png"


class EnterpriseApplication(_Application):
    _icon = "enterprise-application.png"


class EventGridDomain(_Application):
    _icon = "event-grid-domain.png"


class EventGridInputOutput(_Application):
    _icon = "event-grid-input-output.png"


class EventGridPartnerTopic(_Application):
    _icon = "event-grid-partner-topic.png"


class EventGridSubscription(_Application):
    _icon = "event-grid-subscription.png"


class EventGridSystemTopic(_Application):
    _icon = "event-grid-system-topic.png"


class EventGridTopic(_Application):
    _icon = "event-grid-topic.png"


class EventHubCluster(_Application):
    _icon = "event-hub-cluster.png"


class EventHubEvent(_Application):
    _icon = "event-hub-event.png"


class EventHubNetworking(_Application):
    _icon = "event-hub-networking.png"


class EventHubScale(_Application):
    _icon = "event-hub-scale.png"


class EventHubSchemaRegistry(_Application):
    _icon = "event-hub-schema-registry.png"


class EventHub(_Application):
    _icon = "event-hub.png"


class FhirService(_Application):
    _icon = "fhir-service.png"


class FluidRelay(_Application):
    _icon = "fluid-relay.png"


class Ftp(_Application):
    _icon = "ftp.png"


class FunctionAppAdvancedTool(_Application):
    _icon = "function-app-advanced-tool.png"


class FunctionAppAPIDefinition(_Application):
    _icon = "function-app-api-definition.png"


class FunctionAppAPIManagement(_Application):
    _icon = "function-app-api-management.png"


class FunctionAppAuthentication(_Application):
    _icon = "function-app-authentication.png"


class FunctionAppCors(_Application):
    _icon = "function-app-cors.png"


class FunctionAppDeploymentSlot(_Application):
    _icon = "function-app-deployment-slot.png"


class FunctionAppExtension(_Application):
    _icon = "function-app-extension.png"


class FunctionAppFile(_Application):
    _icon = "function-app-file.png"


class FunctionAppFunction(_Application):
    _icon = "function-app-function.png"


class FunctionAppProperties(_Application):
    _icon = "function-app-properties.png"


class FunctionAppProxy(_Application):
    _icon = "function-app-proxy.png"


class FunctionAppScaleOut(_Application):
    _icon = "function-app-scale-out.png"


class FunctionAppServiceEditor(_Application):
    _icon = "function-app-service-editor.png"


class FunctionApp(_Application):
    _icon = "function-app.png"


class GenomicsAccount(_Application):
    _icon = "genomics-account.png"


class IntegrationServiceEnvironment(_Application):
    _icon = "integration-service-environment.png"


class LivedataPlane(_Application):
    _icon = "livedata-plane.png"


class LogicAppCustomConnecton(_Application):
    _icon = "logic-app-custom-connecton.png"


class LogicApp(_Application):
    _icon = "logic-app.png"


class ManagedApplicationCenter(_Application):
    _icon = "managed-application-center.png"


class ManagedApplication(_Application):
    _icon = "managed-application.png"


class MedtechService(_Application):
    _icon = "medtech-service.png"


class MeshApplication(_Application):
    _icon = "mesh-application.png"


class NotificationHub(_Application):
    _icon = "notification-hub.png"


class OpenSupplyChainPlatform(_Application):
    _icon = "open-supply-chain-platform.png"


class ScalingPlan(_Application):
    _icon = "scaling-plan.png"


class SendgridAccount(_Application):
    _icon = "sendgrid-account.png"


class ServiceEndpointPolicy(_Application):
    _icon = "service-endpoint-policy.png"


class ServiceFabricManagedCluster(_Application):
    _icon = "service-fabric-managed-cluster.png"


class ServicesHubConnector(_Application):
    _icon = "services-hub-connector.png"


class Signalr(_Application):
    _icon = "signalr.png"


class StaticWebApp(_Application):
    _icon = "static-web-app.png"


class StaticWebFolder(_Application):
    _icon = "static-web-folder.png"


class StreamAnalyticsCluster(_Application):
    _icon = "stream-analytics-cluster.png"


class StreamAnalyticsJob(_Application):
    _icon = "stream-analytics-job.png"


class WebAppFile(_Application):
    _icon = "web-app-file.png"


class WebHook(_Application):
    _icon = "web-hook.png"


class WebPubsubService(_Application):
    _icon = "web-pubsub-service.png"


class WebSocket(_Application):
    _icon = "web-socket.png"


# Aliases
