# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Appservices(_Azure):
    _type = "appservices"
    _icon_dir = "resources/azure/appservices"


class AppServiceCertificates(_Appservices):
    _icon = "app-service-certificates.png"


class AppServiceDomains(_Appservices):
    _icon = "app-service-domains.png"


class AppServiceEnvironments(_Appservices):
    _icon = "app-service-environments.png"


class AppServicePlans(_Appservices):
    _icon = "app-service-plans.png"


class AppServices(_Appservices):
    _icon = "app-services.png"


class CDNProfiles(_Appservices):
    _icon = "cdn-profiles.png"


class CognitiveSearch(_Appservices):
    _icon = "cognitive-search.png"


class NotificationHubs(_Appservices):
    _icon = "notification-hubs.png"


# Aliases
