# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Azure_Vmware(_Azure):
    _type = "azure_vmware"
    _icon_dir = "resources/azure/azure_vmware"


class Avs(_Azure_Vmware):
    _icon = "avs.png"


# Aliases
