# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Azure_Stack(_Azure):
    _type = "azure_stack"
    _icon_dir = "resources/azure/azure_stack"


class Capacity(_Azure_Stack):
    _icon = "capacity.png"


class InfrastructureBackup(_Azure_Stack):
    _icon = "infrastructure-backup.png"


class MultiTenancy(_Azure_Stack):
    _icon = "multi-tenancy.png"


class Offers(_Azure_Stack):
    _icon = "offers.png"


class Plans(_Azure_Stack):
    _icon = "plans.png"


class Stack(_Azure_Stack):
    _icon = "stack.png"


class Updates(_Azure_Stack):
    _icon = "updates.png"


class UserSubscriptions(_Azure_Stack):
    _icon = "user-subscriptions.png"


# Aliases
