# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Azure_Ecosystem(_Azure):
    _type = "azure_ecosystem"
    _icon_dir = "resources/azure/azure_ecosystem"


class Applens(_Azure_Ecosystem):
    _icon = "applens.png"


class CollaborativeService(_Azure_Ecosystem):
    _icon = "collaborative-service.png"


class HybridCenter(_Azure_Ecosystem):
    _icon = "hybrid-center.png"


# Aliases
