# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Azure(_Azure):
    _type = "azure"
    _icon_dir = "resources/azure/azure"


class Azure(_Azure):
    _icon = "azure.png"


# Aliases
