# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Azure_Vmware_Solution(_Azure):
    _type = "azure_vmware_solution"
    _icon_dir = "resources/azure/azure_vmware_solution"


class Avs(_Azure_Vmware_Solution):
    _icon = "avs.png"


# Aliases
