# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Compute(_Azure):
    _type = "compute"
    _icon_dir = "resources/azure/compute"


class AppServices(_Compute):
    _icon = "app-services.png"


class AutomanagedVM(_Compute):
    _icon = "automanaged-vm.png"


class AvailabilitySets(_Compute):
    _icon = "availability-sets.png"


class BatchAccounts(_Compute):
    _icon = "batch-accounts.png"


class CloudServicesClassic(_Compute):
    _icon = "cloud-services-classic.png"


class ContainerInstances(_Compute):
    _icon = "container-instances.png"


class ContainerServicesDeprecated(_Compute):
    _icon = "container-services-deprecated.png"


class DiskEncryptionSets(_Compute):
    _icon = "disk-encryption-sets.png"


class DisksClassic(_Compute):
    _icon = "disks-classic.png"


class DisksSnapshots(_Compute):
    _icon = "disks-snapshots.png"


class Disks(_Compute):
    _icon = "disks.png"


class FunctionApps(_Compute):
    _icon = "function-apps.png"


class ImageDefinitions(_Compute):
    _icon = "image-definitions.png"


class ImageVersions(_Compute):
    _icon = "image-versions.png"


class Images(_Compute):
    _icon = "images.png"


class KubernetesServices(_Compute):
    _icon = "kubernetes-services.png"


class MeshApplications(_Compute):
    _icon = "mesh-applications.png"


class OsImagesClassic(_Compute):
    _icon = "os-images-classic.png"


class ServiceFabricClusters(_Compute):
    _icon = "service-fabric-clusters.png"


class SharedImageGalleries(_Compute):
    _icon = "shared-image-galleries.png"


class SpringCloud(_Compute):
    _icon = "spring-cloud.png"


class VirtualMachine(_Compute):
    _icon = "virtual-machine.png"


class VirtualMachinesClassic(_Compute):
    _icon = "virtual-machines-classic.png"


class VMImagesClassic(_Compute):
    _icon = "vm-images-classic.png"


class VMScaleSets(_Compute):
    _icon = "vm-scale-sets.png"


class Workspaces(_Compute):
    _icon = "workspaces.png"


# Aliases

ACR = ContainerRegistries
AKS = KubernetesServices
VMSS = VMScaleSet
