# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Containers(_Azure):
    _type = "containers"
    _icon_dir = "resources/azure/containers"


class AppServices(_Containers):
    _icon = "app-services.png"


class AzureRedHatOpenshift(_Containers):
    _icon = "azure-red-hat-openshift.png"


class BatchAccounts(_Containers):
    _icon = "batch-accounts.png"


class ContainerInstances(_Containers):
    _icon = "container-instances.png"


class ContainerRegistries(_Containers):
    _icon = "container-registries.png"


class KubernetesServices(_Containers):
    _icon = "kubernetes-services.png"


class ServiceFabricClusters(_Containers):
    _icon = "service-fabric-clusters.png"


# Aliases
