# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Data(_Azure):
    _type = "data"
    _icon_dir = "resources/azure/data"


class AnalysisService(_Data):
    _icon = "analysis-service.png"


class ApacheSparkConfiguration(_Data):
    _icon = "apache-spark-configuration.png"


class ApacheSparkPackage(_Data):
    _icon = "apache-spark-package.png"


class ApacheSparkPauseSetting(_Data):
    _icon = "apache-spark-pause-setting.png"


class ApacheSparkPool(_Data):
    _icon = "apache-spark-pool.png"


class ApacheSparkScaleSetting(_Data):
    _icon = "apache-spark-scale-setting.png"


class AzureBatchAccount(_Data):
    _icon = "azure-batch-account.png"


class AzureBatch(_Data):
    _icon = "azure-batch.png"


class AzureCosmosDbCognitiveSearch(_Data):
    _icon = "azure-cosmos-db-cognitive-search.png"


class AzureCosmosDbCors(_Data):
    _icon = "azure-cosmos-db-cors.png"


class AzureCosmosDbDedicatedGateway(_Data):
    _icon = "azure-cosmos-db-dedicated-gateway.png"


class AzureCosmosDbDocumentExplorer(_Data):
    _icon = "azure-cosmos-db-document-explorer.png"


class AzureCosmosDbFeature(_Data):
    _icon = "azure-cosmos-db-feature.png"


class AzureCosmosDbFirewallAndVnet(_Data):
    _icon = "azure-cosmos-db-firewall-and-vnet.png"


class AzureCosmosDbNotification(_Data):
    _icon = "azure-cosmos-db-notification.png"


class AzureCosmosDbQueryExplorer(_Data):
    _icon = "azure-cosmos-db-query-explorer.png"


class AzureCosmosDbReplication(_Data):
    _icon = "azure-cosmos-db-replication.png"


class AzureCosmosDbScriptExplorer(_Data):
    _icon = "azure-cosmos-db-script-explorer.png"


class AzureCosmosDbSynapseLink(_Data):
    _icon = "azure-cosmos-db-synapse-link.png"


class AzureCosmosDb(_Data):
    _icon = "azure-cosmos-db.png"


class AzureDataExplorerCluster(_Data):
    _icon = "azure-data-explorer-cluster.png"


class AzureDatabaseForMariadb(_Data):
    _icon = "azure-database-for-mariadb.png"


class AzureDatabaseForMysql(_Data):
    _icon = "azure-database-for-mysql.png"


class AzureDatabaseForPostgresqlGroup(_Data):
    _icon = "azure-database-for-postgresql-group.png"


class AzureDatabaseForPostgresql(_Data):
    _icon = "azure-database-for-postgresql.png"


class AzureDatabricks(_Data):
    _icon = "azure-databricks.png"


class AzureIntegrationRuntime(_Data):
    _icon = "azure-integration-runtime.png"


class AzureManagedInstanceForApacheCassandra(_Data):
    _icon = "azure-managed-instance-for-apache-cassandra.png"


class AzureMediaServices(_Data):
    _icon = "azure-media-services.png"


class AzureSynapseAnalyticsDedicatedSQLPool(_Data):
    _icon = "azure-synapse-analytics-dedicated-sql-pool.png"


class AzureSynapseAnalyticsPipeline(_Data):
    _icon = "azure-synapse-analytics-pipeline.png"


class AzureSynapseAnalyticsPrivateLinkHub(_Data):
    _icon = "azure-synapse-analytics-private-link-hub.png"


class AzureSynapseAnalyticsServerlessSQLPool(_Data):
    _icon = "azure-synapse-analytics-serverless-sql-pool.png"


class AzureSynapseAnalyticsSparkPool(_Data):
    _icon = "azure-synapse-analytics-spark-pool.png"


class AzureSynapseAnalytics(_Data):
    _icon = "azure-synapse-analytics.png"


class DataAndStorage(_Data):
    _icon = "data-and-storage.png"


class DataCollectionDataSource(_Data):
    _icon = "data-collection-data-source.png"


class DataCollectionRule(_Data):
    _icon = "data-collection-rule.png"


class DataFactory(_Data):
    _icon = "data-factory.png"


class DataLakeAnalytics(_Data):
    _icon = "data-lake-analytics.png"


class DataLakeStorageGen1(_Data):
    _icon = "data-lake-storage-gen1.png"


class DataLakeStorageGen2(_Data):
    _icon = "data-lake-storage-gen2.png"


class DataLake(_Data):
    _icon = "data-lake.png"


class DataShareInvitation(_Data):
    _icon = "data-share-invitation.png"


class DataTransfer(_Data):
    _icon = "data-transfer.png"


class DiskAccess(_Data):
    _icon = "disk-access.png"


class ElasticJobAgent(_Data):
    _icon = "elastic-job-agent.png"


class Elasticsearch(_Data):
    _icon = "elasticsearch.png"


class HdinsightCluster(_Data):
    _icon = "hdinsight-cluster.png"


class HpcCache(_Data):
    _icon = "hpc-cache.png"


class ImportExportJob(_Data):
    _icon = "import-export-job.png"


class IntegrationRuntime(_Data):
    _icon = "integration-runtime.png"


class LinkedIntegrationRuntime(_Data):
    _icon = "linked-integration-runtime.png"


class ManagedDatabase(_Data):
    _icon = "managed-database.png"


class OpenDataset(_Data):
    _icon = "open-dataset.png"


class PurviewAccount(_Data):
    _icon = "purview-account.png"


class SAPHANAOnAzure(_Data):
    _icon = "sap-hana-on-azure.png"


class ServiceBusQueue(_Data):
    _icon = "service-bus-queue.png"


class ServiceBusTopic(_Data):
    _icon = "service-bus-topic.png"


class ServiceBus(_Data):
    _icon = "service-bus.png"


class SharedIntegrationRuntime(_Data):
    _icon = "shared-integration-runtime.png"


class Snowflake(_Data):
    _icon = "snowflake.png"


class SQLDataWarehouse(_Data):
    _icon = "sql-data-warehouse.png"


class SQLDatabaseAuditing(_Data):
    _icon = "sql-database-auditing.png"


class SQLDatabaseAutomaticTuning(_Data):
    _icon = "sql-database-automatic-tuning.png"


class SQLDatabaseAzureDataStudio(_Data):
    _icon = "sql-database-azure-data-studio.png"


class SQLDatabaseConnectionString(_Data):
    _icon = "sql-database-connection-string.png"


class SQLDatabaseDataDiscoveryAndClassification(_Data):
    _icon = "sql-database-data-discovery-and-classification.png"


class SQLDatabaseDynamicDataMasking(_Data):
    _icon = "sql-database-dynamic-data-masking.png"


class SQLDatabaseEdge(_Data):
    _icon = "sql-database-edge.png"


class SQLDatabaseExport(_Data):
    _icon = "sql-database-export.png"


class SQLDatabaseLedger(_Data):
    _icon = "sql-database-ledger.png"


class SQLDatabasePerformanceOverview(_Data):
    _icon = "sql-database-performance-overview.png"


class SQLDatabasePerformanceRecommendation(_Data):
    _icon = "sql-database-performance-recommendation.png"


class SQLDatabaseQueryEditor(_Data):
    _icon = "sql-database-query-editor.png"


class SQLDatabaseQueryPerformanceInsight(_Data):
    _icon = "sql-database-query-performance-insight.png"


class SQLDatabaseRestore(_Data):
    _icon = "sql-database-restore.png"


class SQLDatabaseSync(_Data):
    _icon = "sql-database-sync.png"


class SQLDatabaseTransparentDataEncryption(_Data):
    _icon = "sql-database-transparent-data-encryption.png"


class SQLDatabase(_Data):
    _icon = "sql-database.png"


class SQLElasticJobAgent(_Data):
    _icon = "sql-elastic-job-agent.png"


class SQLElasticPool(_Data):
    _icon = "sql-elastic-pool.png"


class SQLInstancePool(_Data):
    _icon = "sql-instance-pool.png"


class SQLManagedInstance(_Data):
    _icon = "sql-managed-instance.png"


class SQLServerAuditing(_Data):
    _icon = "sql-server-auditing.png"


class SQLServerAutomaticTuning(_Data):
    _icon = "sql-server-automatic-tuning.png"


class SQLServerFailoverGroup(_Data):
    _icon = "sql-server-failover-group.png"


class SQLServerFirewallsAndVnet(_Data):
    _icon = "sql-server-firewalls-and-vnet.png"


class SQLServerIdentity(_Data):
    _icon = "sql-server-identity.png"


class SQLServerImportExport(_Data):
    _icon = "sql-server-import-export.png"


class SQLServerRecommendation(_Data):
    _icon = "sql-server-recommendation.png"


class SQLServerRegistry(_Data):
    _icon = "sql-server-registry.png"


class SQLServer(_Data):
    _icon = "sql-server.png"


class SsisIntegrationRuntime(_Data):
    _icon = "ssis-integration-runtime.png"


class StorsimpleDeviceManager(_Data):
    _icon = "storsimple-device-manager.png"


class TimeSeriesInsightsEnvironment(_Data):
    _icon = "time-series-insights-environment.png"


class TimeSeriesInsightsEventSource(_Data):
    _icon = "time-series-insights-event-source.png"


class TimeSeriesInsightsReferenceDataSet(_Data):
    _icon = "time-series-insights-reference-data-set.png"


class VideoAnalyzerForMedia(_Data):
    _icon = "video-analyzer-for-media.png"


class VideoAnalyzer(_Data):
    _icon = "video-analyzer.png"


# Aliases
