# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Databases(_Azure):
    _type = "databases"
    _icon_dir = "resources/azure/databases"


class CacheRedis(_Databases):
    _icon = "cache-redis.png"


class CosmosDb(_Databases):
    _icon = "cosmos-db.png"


class DataExplorerClusters(_Databases):
    _icon = "data-explorer-clusters.png"


class DataFactory(_Databases):
    _icon = "data-factory.png"


class DatabaseMariadbServer(_Databases):
    _icon = "database-mariadb-server.png"


class DatabaseMigrationServices(_Databases):
    _icon = "database-migration-services.png"


class DatabaseMysqlServer(_Databases):
    _icon = "database-mysql-server.png"


class DatabasePostgresqlServer(_Databases):
    _icon = "database-postgresql-server.png"


class ElasticJobAgents(_Databases):
    _icon = "elastic-job-agents.png"


class InstancePools(_Databases):
    _icon = "instance-pools.png"


class ManagedDatabase(_Databases):
    _icon = "managed-database.png"


class SQLDataWarehouses(_Databases):
    _icon = "sql-data-warehouses.png"


class SQLDatabase(_Databases):
    _icon = "sql-database.png"


class SQLElasticPools(_Databases):
    _icon = "sql-elastic-pools.png"


class SQLManagedInstance(_Databases):
    _icon = "sql-managed-instance.png"


class SQLServerStretchDatabases(_Databases):
    _icon = "sql-server-stretch-databases.png"


class SQLServer(_Databases):
    _icon = "sql-server.png"


class SQLVM(_Databases):
    _icon = "sql-vm.png"


class SQL(_Databases):
    _icon = "sql.png"


class SsisLiftAndShiftIr(_Databases):
    _icon = "ssis-lift-and-shift-ir.png"


class SynapseAnalytics(_Databases):
    _icon = "synapse-analytics.png"


class VirtualClusters(_Databases):
    _icon = "virtual-clusters.png"


# Aliases
