# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Deployment(_Azure):
    _type = "deployment"
    _icon_dir = "resources/azure/deployment"


class Ansible(_Deployment):
    _icon = "ansible.png"


class ArmTemplate(_Deployment):
    _icon = "arm-template.png"


class AzureArtifact(_Deployment):
    _icon = "azure-artifact.png"


class AzureBoard(_Deployment):
    _icon = "azure-board.png"


class AzureDevOps(_Deployment):
    _icon = "azure-dev-ops.png"


class AzurePipelines(_Deployment):
    _icon = "azure-pipelines.png"


class AzureRepo(_Deployment):
    _icon = "azure-repo.png"


class Backlog(_Deployment):
    _icon = "backlog.png"


class Bicep(_Deployment):
    _icon = "bicep.png"


class Blueprint(_Deployment):
    _icon = "blueprint.png"


class Chef(_Deployment):
    _icon = "chef.png"


class Commit(_Deployment):
    _icon = "commit.png"


class ConfluentOrganisation(_Deployment):
    _icon = "confluent-organisation.png"


class Controller(_Deployment):
    _icon = "controller.png"


class CustomTemplate(_Deployment):
    _icon = "custom-template.png"


class DeploymentScript(_Deployment):
    _icon = "deployment-script.png"


class Deployment(_Deployment):
    _icon = "deployment.png"


class DevopsStarter(_Deployment):
    _icon = "devops-starter.png"


class ExportTemplate(_Deployment):
    _icon = "export-template.png"


class Github(_Deployment):
    _icon = "github.png"


class IntegrationAccount(_Deployment):
    _icon = "integration-account.png"


class Java(_Deployment):
    _icon = "java.png"


class Jenkins(_Deployment):
    _icon = "jenkins.png"


class Kafka(_Deployment):
    _icon = "kafka.png"


class NodeJs(_Deployment):
    _icon = "node-js.png"


class OneesCloudtestAccount(_Deployment):
    _icon = "onees-cloudtest-account.png"


class OneesCloudtestImage(_Deployment):
    _icon = "onees-cloudtest-image.png"


class OneesHostedPool(_Deployment):
    _icon = "onees-hosted-pool.png"


class Onees(_Deployment):
    _icon = "onees.png"


class OpenshiftCluster(_Deployment):
    _icon = "openshift-cluster.png"


class Powershell(_Deployment):
    _icon = "powershell.png"


class Python(_Deployment):
    _icon = "python.png"


class Repository(_Deployment):
    _icon = "repository.png"


class Rest(_Deployment):
    _icon = "rest.png"


class Rollout(_Deployment):
    _icon = "rollout.png"


class Slack(_Deployment):
    _icon = "slack.png"


class TemplateSpec(_Deployment):
    _icon = "template-spec.png"


class Template(_Deployment):
    _icon = "template.png"


class Terraform(_Deployment):
    _icon = "terraform.png"


class Trello(_Deployment):
    _icon = "trello.png"


class VisualStudioCode(_Deployment):
    _icon = "visual-studio-code.png"


class VisualStudio(_Deployment):
    _icon = "visual-studio.png"


# Aliases
