# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Dynamics365(_Azure):
    _type = "dynamics365"
    _icon_dir = "resources/azure/dynamics365"


class ApplicationBusinessCentral(_Dynamics365):
    _icon = "application-business-central.png"


class ApplicationCommerce(_Dynamics365):
    _icon = "application-commerce.png"


class ApplicationConnectedStore(_Dynamics365):
    _icon = "application-connected-store.png"


class ApplicationCoreHr(_Dynamics365):
    _icon = "application-core-hr.png"


class ApplicationCustomerInsights(_Dynamics365):
    _icon = "application-customer-insights.png"


class ApplicationCustomerServiceInsights(_Dynamics365):
    _icon = "application-customer-service-insights.png"


class ApplicationCustomerService(_Dynamics365):
    _icon = "application-customer-service.png"


class ApplicationCustomerVoice(_Dynamics365):
    _icon = "application-customer-voice.png"


class ApplicationFieldService(_Dynamics365):
    _icon = "application-field-service.png"


class ApplicationFinanceAndOperations(_Dynamics365):
    _icon = "application-finance-and-operations.png"


class ApplicationFinance(_Dynamics365):
    _icon = "application-finance.png"


class ApplicationFraudProtection(_Dynamics365):
    _icon = "application-fraud-protection.png"


class ApplicationIntelligentOrderManagement(_Dynamics365):
    _icon = "application-intelligent-order-management.png"


class ApplicationMarketInsights(_Dynamics365):
    _icon = "application-market-insights.png"


class ApplicationMarketing(_Dynamics365):
    _icon = "application-marketing.png"


class ApplicationProductInsights(_Dynamics365):
    _icon = "application-product-insights.png"


class ApplicationProjectOperations(_Dynamics365):
    _icon = "application-project-operations.png"


class ApplicationProjectServiceAutomation(_Dynamics365):
    _icon = "application-project-service-automation.png"


class ApplicationProjectTimesheet(_Dynamics365):
    _icon = "application-project-timesheet.png"


class ApplicationReturnToSchool(_Dynamics365):
    _icon = "application-return-to-school.png"


class ApplicationReturnToWork(_Dynamics365):
    _icon = "application-return-to-work.png"


class ApplicationSalesInsights(_Dynamics365):
    _icon = "application-sales-insights.png"


class ApplicationSales(_Dynamics365):
    _icon = "application-sales.png"


class ApplicationScmWarehousing(_Dynamics365):
    _icon = "application-scm-warehousing.png"


class ApplicationSupplyChainManagement(_Dynamics365):
    _icon = "application-supply-chain-management.png"


class ApplicationSustainabilityCalculator(_Dynamics365):
    _icon = "application-sustainability-calculator.png"


class ApplicationTalentAttract(_Dynamics365):
    _icon = "application-talent-attract.png"


class ApplicationTalentOnboard(_Dynamics365):
    _icon = "application-talent-onboard.png"


class ApplicationTalent(_Dynamics365):
    _icon = "application-talent.png"


class Dynamics365(_Dynamics365):
    _icon = "dynamics-365.png"


class MixedRealityGuide(_Dynamics365):
    _icon = "mixed-reality-guide.png"


class MixedRealityImportTool(_Dynamics365):
    _icon = "mixed-reality-import-tool.png"


class MixedRealityLayout(_Dynamics365):
    _icon = "mixed-reality-layout.png"


class MixedRealityPortal(_Dynamics365):
    _icon = "mixed-reality-portal.png"


class MixedRealityProductVisualise(_Dynamics365):
    _icon = "mixed-reality-product-visualise.png"


class MixedRealityRemoteAssist(_Dynamics365):
    _icon = "mixed-reality-remote-assist.png"


class MixedRealityVoiceAssistant(_Dynamics365):
    _icon = "mixed-reality-voice-assistant.png"


# Aliases
