# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Endpoint(_Azure):
    _type = "endpoint"
    _icon_dir = "resources/azure/endpoint"


class AzureAttestation(_Endpoint):
    _icon = "azure-attestation.png"


class EndpointSecurity(_Endpoint):
    _icon = "endpoint-security.png"


class IntuneAppProtection(_Endpoint):
    _icon = "intune-app-protection.png"


class IntuneDeviceCompliance(_Endpoint):
    _icon = "intune-device-compliance.png"


class IntuneDeviceConfiguration(_Endpoint):
    _icon = "intune-device-configuration.png"


class IntuneDeviceEnrolment(_Endpoint):
    _icon = "intune-device-enrolment.png"


class IntuneDeviceSecurity(_Endpoint):
    _icon = "intune-device-security.png"


class IntuneDevice(_Endpoint):
    _icon = "intune-device.png"


class IntuneExchangeAccess(_Endpoint):
    _icon = "intune-exchange-access.png"


class IntuneExchangeOnPremisesAccess(_Endpoint):
    _icon = "intune-exchange-on-premises-access.png"


class IntuneManagedDesktop(_Endpoint):
    _icon = "intune-managed-desktop.png"


class IntuneSecurityBaseline(_Endpoint):
    _icon = "intune-security-baseline.png"


class IntuneSoftwareUpdate(_Endpoint):
    _icon = "intune-software-update.png"


class IntuneTenantStatus(_Endpoint):
    _icon = "intune-tenant-status.png"


class Intune(_Endpoint):
    _icon = "intune.png"


class MobileApplication(_Endpoint):
    _icon = "mobile-application.png"


class MobilityMdmAndMam(_Endpoint):
    _icon = "mobility-mdm-and-mam.png"


class UniversalPrintService(_Endpoint):
    _icon = "universal-print-service.png"


# Aliases
