# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _General(_Azure):
    _type = "general"
    _icon_dir = "resources/azure/general"


class AllResources(_General):
    _icon = "all-resources.png"


class Developertools(_General):
    _icon = "developertools.png"


class HelpSupport(_General):
    _icon = "help-support.png"


class Home(_General):
    _icon = "home.png"


class Information(_General):
    _icon = "information.png"


class ManagementGroups(_General):
    _icon = "management-groups.png"


class Marketplace(_General):
    _icon = "marketplace.png"


class QuickStartCenter(_General):
    _icon = "quick-start-center.png"


class Recent(_General):
    _icon = "recent.png"


class Reservations(_General):
    _icon = "reservations.png"


class ResourceGroups(_General):
    _icon = "resource-groups.png"


class Resource(_General):
    _icon = "resource.png"


class ServiceHealth(_General):
    _icon = "service-health.png"


class SharedDashboard(_General):
    _icon = "shared-dashboard.png"


class Subscriptions(_General):
    _icon = "subscriptions.png"


class SupportRequests(_General):
    _icon = "support-requests.png"


class Support(_General):
    _icon = "support.png"


class Tag(_General):
    _icon = "tag.png"


class Tags(_General):
    _icon = "tags.png"


class Templates(_General):
    _icon = "templates.png"


class TwoUserIcon(_General):
    _icon = "two-user-icon.png"


class UserHealthIcon(_General):
    _icon = "user-health-icon.png"


class UserIcon(_General):
    _icon = "user-icon.png"


class UserPrivacy(_General):
    _icon = "user-privacy.png"


class UserResource(_General):
    _icon = "user-resource.png"


# Aliases
