# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Generic(_Azure):
    _type = "generic"
    _icon_dir = "resources/azure/generic"


class AllResources(_Generic):
    _icon = "all-resources.png"


class AzureBestPractices(_Generic):
    _icon = "azure-best-practices.png"


class AzureLegacy(_Generic):
    _icon = "azure-legacy.png"


class Azure(_Generic):
    _icon = "azure.png"


class CompanyBranding(_Generic):
    _icon = "company-branding.png"


class Configuration(_Generic):
    _icon = "configuration.png"


class CustomerLockboxForMicrosoftAzure(_Generic):
    _icon = "customer-lockbox-for-microsoft-azure.png"


class Ebook(_Generic):
    _icon = "ebook.png"


class Education(_Generic):
    _icon = "education.png"


class FreeServices(_Generic):
    _icon = "free-services.png"


class HelpAndSupport(_Generic):
    _icon = "help-and-support.png"


class License(_Generic):
    _icon = "license.png"


class MaintenanceConfiguration(_Generic):
    _icon = "maintenance-configuration.png"


class Marketplace(_Generic):
    _icon = "marketplace.png"


class OperationalExcellence(_Generic):
    _icon = "operational-excellence.png"


class PlatformService(_Generic):
    _icon = "platform-service.png"


class PreviewFeature(_Generic):
    _icon = "preview-feature.png"


class Property(_Generic):
    _icon = "property.png"


class QuickstartCenter(_Generic):
    _icon = "quickstart-center.png"


class Recent(_Generic):
    _icon = "recent.png"


class ResourceExplorer(_Generic):
    _icon = "resource-explorer.png"


class ResourceGraphExplorer(_Generic):
    _icon = "resource-graph-explorer.png"


class ResourceGraphQuery(_Generic):
    _icon = "resource-graph-query.png"


class ResourceHealth(_Generic):
    _icon = "resource-health.png"


class ServiceCatalogManagedApplicationDefinition(_Generic):
    _icon = "service-catalog-managed-application-definition.png"


class ServiceHealth(_Generic):
    _icon = "service-health.png"


class SoftwareAsAService(_Generic):
    _icon = "software-as-a-service.png"


class Sync(_Generic):
    _icon = "sync.png"


class TenantStatus(_Generic):
    _icon = "tenant-status.png"


class Tick(_Generic):
    _icon = "tick.png"


class UserPrivacy(_Generic):
    _icon = "user-privacy.png"


class VirtualAssistant(_Generic):
    _icon = "virtual-assistant.png"


class Warning(_Generic):
    _icon = "warning.png"


# Aliases
