# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Integration(_Azure):
    _type = "integration"
    _icon_dir = "resources/azure/integration"


class APIForFhir(_Integration):
    _icon = "api-for-fhir.png"


class APIManagementServices(_Integration):
    _icon = "api-management-services.png"


class DataCatalog(_Integration):
    _icon = "data-catalog.png"


class EventGridDomains(_Integration):
    _icon = "event-grid-domains.png"


class EventGridSubscriptions(_Integration):
    _icon = "event-grid-subscriptions.png"


class EventGridTopics(_Integration):
    _icon = "event-grid-topics.png"


class IntegrationAccounts(_Integration):
    _icon = "integration-accounts.png"


class LogicApps(_Integration):
    _icon = "logic-apps.png"


class PartnerTopic(_Integration):
    _icon = "partner-topic.png"


class Relays(_Integration):
    _icon = "relays.png"


class SoftwareAsAService(_Integration):
    _icon = "software-as-a-service.png"


class SQLDataWarehouses(_Integration):
    _icon = "sql-data-warehouses.png"


class SystemTopic(_Integration):
    _icon = "system-topic.png"


# Aliases
