# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Intune(_Azure):
    _type = "intune"
    _icon_dir = "resources/azure/intune"


class ADRolesAndAdministrators(_Intune):
    _icon = "ad-roles-and-administrators.png"


class DeviceSecurityApple(_Intune):
    _icon = "device-security-apple.png"


class DeviceSecurityGoogle(_Intune):
    _icon = "device-security-google.png"


class DeviceSecurityWindows(_Intune):
    _icon = "device-security-windows.png"


class IntuneForEducation(_Intune):
    _icon = "intune-for-education.png"


class Intune(_Intune):
    _icon = "intune.png"


# Aliases
