# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Management_Governance(_Azure):
    _type = "management_governance"
    _icon_dir = "resources/azure/management_governance"


class ActivityLog(_Management_Governance):
    _icon = "activity-log.png"


class Advisor(_Management_Governance):
    _icon = "advisor.png"


class Alerts(_Management_Governance):
    _icon = "alerts.png"


class ApplicationInsights(_Management_Governance):
    _icon = "application-insights.png"


class Arc(_Management_Governance):
    _icon = "arc.png"


class AutomationAccounts(_Management_Governance):
    _icon = "automation-accounts.png"


class Blueprints(_Management_Governance):
    _icon = "blueprints.png"


class Compliance(_Management_Governance):
    _icon = "compliance.png"


class CostManagementAndBilling(_Management_Governance):
    _icon = "cost-management-and-billing.png"


class DiagnosticsSettings(_Management_Governance):
    _icon = "diagnostics-settings.png"


class Education(_Management_Governance):
    _icon = "education.png"


class Lighthouse(_Management_Governance):
    _icon = "lighthouse.png"


class LogAnalyticsWorkspaces(_Management_Governance):
    _icon = "log-analytics-workspaces.png"


class Machinesazurearc(_Management_Governance):
    _icon = "machinesazurearc.png"


class ManagedApplicationsCenter(_Management_Governance):
    _icon = "managed-applications-center.png"


class Metrics(_Management_Governance):
    _icon = "metrics.png"


class Monitor(_Management_Governance):
    _icon = "monitor.png"


class MyCustomers(_Management_Governance):
    _icon = "my-customers.png"


class OperationLogClassic(_Management_Governance):
    _icon = "operation-log-classic.png"


class Policy(_Management_Governance):
    _icon = "policy.png"


class RecoveryServicesVaults(_Management_Governance):
    _icon = "recovery-services-vaults.png"


class ResourceGraphExplorer(_Management_Governance):
    _icon = "resource-graph-explorer.png"


class ServiceProviders(_Management_Governance):
    _icon = "service-providers.png"


class Solutions(_Management_Governance):
    _icon = "solutions.png"


class UserPrivacy(_Management_Governance):
    _icon = "user-privacy.png"


# Aliases
