# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Management(_Azure):
    _type = "management"
    _icon_dir = "resources/azure/management"


class Policy(_Management):
    _icon = "policy.png"


# Aliases
