# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Menu(_Azure):
    _type = "menu"
    _icon_dir = "resources/azure/menu"


class Keys(_Menu):
    _icon = "keys.png"


# Aliases
