# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Migration(_Azure):
    _type = "migration"
    _icon_dir = "resources/azure/migration"


class AzureDatabaseMigrationServices(_Migration):
    _icon = "azure-database-migration-services.png"


# Aliases
