# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Migrate(_Azure):
    _type = "migrate"
    _icon_dir = "resources/azure/migrate"


class CostManagementAndBilling(_Migrate):
    _icon = "cost-management-and-billing.png"


class DataBoxEdge(_Migrate):
    _icon = "data-box-edge.png"


class DataBox(_Migrate):
    _icon = "data-box.png"


class Migrate(_Migrate):
    _icon = "migrate.png"


class RecoveryServicesVaults(_Migrate):
    _icon = "recovery-services-vaults.png"


# Aliases
