# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Mobile(_Azure):
    _type = "mobile"
    _icon_dir = "resources/azure/mobile"


class AppServices(_Mobile):
    _icon = "app-services.png"


class NotificationHubs(_Mobile):
    _icon = "notification-hubs.png"


class PowerPlatform(_Mobile):
    _icon = "power-platform.png"


# Aliases
