# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Monitor(_Azure):
    _type = "monitor"
    _icon_dir = "resources/azure/monitor"


class ChangeAnalysis(_Monitor):
    _icon = "change-analysis.png"


class Logs(_Monitor):
    _icon = "logs.png"


class Metrics(_Monitor):
    _icon = "metrics.png"


class Monitor(_Monitor):
    _icon = "monitor.png"


# Aliases
