# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Monitor(_Azure):
    _type = "monitor"
    _icon_dir = "resources/azure/monitor"


class ActivityLog(_Monitor):
    _icon = "activity-log.png"


class ApplicationInsights(_Monitor):
    _icon = "application-insights.png"


class AutoScale(_Monitor):
    _icon = "auto-scale.png"


class AzureMonitorsForSAPSolutions(_Monitor):
    _icon = "azure-monitors-for-sap-solutions.png"


class AzureWorkbooks(_Monitor):
    _icon = "azure-workbooks.png"


class ChangeAnalysis(_Monitor):
    _icon = "change-analysis.png"


class DiagnosticsSettings(_Monitor):
    _icon = "diagnostics-settings.png"


class LogAnalyticsWorkspaces(_Monitor):
    _icon = "log-analytics-workspaces.png"


class Logs(_Monitor):
    _icon = "logs.png"


class Metrics(_Monitor):
    _icon = "metrics.png"


class Monitor(_Monitor):
    _icon = "monitor.png"


class NetworkWatcher(_Monitor):
    _icon = "network-watcher.png"


# Aliases
