# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Monitor(_Azure):
    _type = "monitor"
    _icon_dir = "resources/azure/monitor"


class SAPAzureMonitor(_Monitor):
    _icon = "sap-azure-monitor.png"


# Aliases
