# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Networking(_Azure):
    _type = "networking"
    _icon_dir = "resources/azure/networking"


class ApplicationGateways(_Networking):
    _icon = "application-gateways.png"


class CDNProfiles(_Networking):
    _icon = "cdn-profiles.png"


class Connections(_Networking):
    _icon = "connections.png"


class DDOSProtectionPlans(_Networking):
    _icon = "ddos-protection-plans.png"


class DNSZones(_Networking):
    _icon = "dns-zones.png"


class ExpressrouteCircuits(_Networking):
    _icon = "expressroute-circuits.png"


class FirewallManager(_Networking):
    _icon = "firewall-manager.png"


class Firewalls(_Networking):
    _icon = "firewalls.png"


class FrontDoors(_Networking):
    _icon = "front-doors.png"


class IpGroups(_Networking):
    _icon = "ip-groups.png"


class LoadBalancers(_Networking):
    _icon = "load-balancers.png"


class LocalNetworkGateways(_Networking):
    _icon = "local-network-gateways.png"


class Nat(_Networking):
    _icon = "nat.png"


class NetworkInterfaces(_Networking):
    _icon = "network-interfaces.png"


class NetworkSecurityGroups(_Networking):
    _icon = "network-security-groups.png"


class NetworkWatcher(_Networking):
    _icon = "network-watcher.png"


class PrivateLinkService(_Networking):
    _icon = "private-link-service.png"


class PrivateLink(_Networking):
    _icon = "private-link.png"


class ProximityPlacementGroups(_Networking):
    _icon = "proximity-placement-groups.png"


class PublicIpAddressesClassic(_Networking):
    _icon = "public-ip-addresses-classic.png"


class PublicIpAddresses(_Networking):
    _icon = "public-ip-addresses.png"


class PublicIpPrefixes(_Networking):
    _icon = "public-ip-prefixes.png"


class ReservedIpAddressesClassic(_Networking):
    _icon = "reserved-ip-addresses-classic.png"


class RouteFilters(_Networking):
    _icon = "route-filters.png"


class RouteTables(_Networking):
    _icon = "route-tables.png"


class ServiceEndpointPolicies(_Networking):
    _icon = "service-endpoint-policies.png"


class TrafficManagerProfiles(_Networking):
    _icon = "traffic-manager-profiles.png"


class VirtualNetworkGateways(_Networking):
    _icon = "virtual-network-gateways.png"


class VirtualNetworksClassic(_Networking):
    _icon = "virtual-networks-classic.png"


class VirtualNetworks(_Networking):
    _icon = "virtual-networks.png"


class VirtualWans(_Networking):
    _icon = "virtual-wans.png"


class WebApplicationFirewallPolicieswaf(_Networking):
    _icon = "web-application-firewall-policieswaf.png"


# Aliases
