# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Networking(_Azure):
    _type = "networking"
    _icon_dir = "resources/azure/networking"


class ApplicationGatewayBackendHealth(_Networking):
    _icon = "application-gateway-backend-health.png"


class ApplicationGatewayBackendPool(_Networking):
    _icon = "application-gateway-backend-pool.png"


class ApplicationGatewayConfiguration(_Networking):
    _icon = "application-gateway-configuration.png"


class ApplicationGatewayFrontendIpConfiguration(_Networking):
    _icon = "application-gateway-frontend-ip-configuration.png"


class ApplicationGatewayHealthProbe(_Networking):
    _icon = "application-gateway-health-probe.png"


class ApplicationGatewayHttpSetting(_Networking):
    _icon = "application-gateway-http-setting.png"


class ApplicationGatewayListener(_Networking):
    _icon = "application-gateway-listener.png"


class ApplicationGatewayRule(_Networking):
    _icon = "application-gateway-rule.png"


class ApplicationGatewaySslSetting(_Networking):
    _icon = "application-gateway-ssl-setting.png"


class ApplicationGatewayWafCustomRule(_Networking):
    _icon = "application-gateway-waf-custom-rule.png"


class ApplicationGatewayWafManagedRule(_Networking):
    _icon = "application-gateway-waf-managed-rule.png"


class ApplicationGatewayWafPolicySetting(_Networking):
    _icon = "application-gateway-waf-policy-setting.png"


class ApplicationGatewayWaf(_Networking):
    _icon = "application-gateway-waf.png"


class ApplicationGateway(_Networking):
    _icon = "application-gateway.png"


class AzureCacheForRedis(_Networking):
    _icon = "azure-cache-for-redis.png"


class AzureFrontDoor(_Networking):
    _icon = "azure-front-door.png"


class Bastion(_Networking):
    _icon = "bastion.png"


class CDNCompression(_Networking):
    _icon = "cdn-compression.png"


class CDNCustomDomain(_Networking):
    _icon = "cdn-custom-domain.png"


class CDNGeoFiltering(_Networking):
    _icon = "cdn-geo-filtering.png"


class CDNOptimisation(_Networking):
    _icon = "cdn-optimisation.png"


class CDNOrigin(_Networking):
    _icon = "cdn-origin.png"


class CDNProfile(_Networking):
    _icon = "cdn-profile.png"


class CommunicationService(_Networking):
    _icon = "communication-service.png"


class ConnectedDevice(_Networking):
    _icon = "connected-device.png"


class DDOSProtectionPlan(_Networking):
    _icon = "ddos-protection-plan.png"


class DNSZonePrivate(_Networking):
    _icon = "dns-zone-private.png"


class DNSZonePublic(_Networking):
    _icon = "dns-zone-public.png"


class ExpressrouteAuthorisation(_Networking):
    _icon = "expressroute-authorisation.png"


class ExpressrouteCircuit(_Networking):
    _icon = "expressroute-circuit.png"


class ExpressrouteConnection(_Networking):
    _icon = "expressroute-connection.png"


class ExpressrouteDirect(_Networking):
    _icon = "expressroute-direct.png"


class ExpressrouteFilter(_Networking):
    _icon = "expressroute-filter.png"


class ExpressrouteHealth(_Networking):
    _icon = "expressroute-health.png"


class ExpressroutePeering(_Networking):
    _icon = "expressroute-peering.png"


class GeoReplication(_Networking):
    _icon = "geo-replication.png"


class HybridConnection(_Networking):
    _icon = "hybrid-connection.png"


class InternetAnalyzerProfile(_Networking):
    _icon = "internet-analyzer-profile.png"


class IpGroup(_Networking):
    _icon = "ip-group.png"


class LoadBalancerBackendFrontendIpConfiguration(_Networking):
    _icon = "load-balancer-backend-frontend-ip-configuration.png"


class LoadBalancerBackendLoadBalancingRule(_Networking):
    _icon = "load-balancer-backend-load-balancing-rule.png"


class LoadBalancerBackendOutboundRule(_Networking):
    _icon = "load-balancer-backend-outbound-rule.png"


class LoadBalancerBackendPool(_Networking):
    _icon = "load-balancer-backend-pool.png"


class LoadBalancerFrontendIpConfiguration(_Networking):
    _icon = "load-balancer-frontend-ip-configuration.png"


class LoadBalancerHealthProbe(_Networking):
    _icon = "load-balancer-health-probe.png"


class LoadBalancerInboundNatRule(_Networking):
    _icon = "load-balancer-inbound-nat-rule.png"


class LoadBalancer(_Networking):
    _icon = "load-balancer.png"


class LocalNetworkGateway(_Networking):
    _icon = "local-network-gateway.png"


class MobileNetworks(_Networking):
    _icon = "mobile-networks.png"


class NatGateway(_Networking):
    _icon = "nat-gateway.png"


class NetworkFunctionManagerDevice(_Networking):
    _icon = "network-function-manager-device.png"


class NetworkFunctionManagerNetworkFunction(_Networking):
    _icon = "network-function-manager-network-function.png"


class NetworkFunctionManagerVendor(_Networking):
    _icon = "network-function-manager-vendor.png"


class NetworkInterfaceEffectiveRoute(_Networking):
    _icon = "network-interface-effective-route.png"


class NetworkInterfaceEffectiveSecurityRule(_Networking):
    _icon = "network-interface-effective-security-rule.png"


class NetworkInterface(_Networking):
    _icon = "network-interface.png"


class NetworkManager(_Networking):
    _icon = "network-manager.png"


class NetworkSecurityGroupClassic(_Networking):
    _icon = "network-security-group-classic.png"


class NetworkSecurityGroupInboundRule(_Networking):
    _icon = "network-security-group-inbound-rule.png"


class NetworkSecurityGroupOutboundRule(_Networking):
    _icon = "network-security-group-outbound-rule.png"


class NetworkWatcher(_Networking):
    _icon = "network-watcher.png"


class Networking(_Networking):
    _icon = "networking.png"


class OnPremisesDataGateway(_Networking):
    _icon = "on-premises-data-gateway.png"


class PeeringService(_Networking):
    _icon = "peering-service.png"


class Peering(_Networking):
    _icon = "peering.png"


class PrivateEndpoint(_Networking):
    _icon = "private-endpoint.png"


class PrivateLink(_Networking):
    _icon = "private-link.png"


class PublicIpAddress(_Networking):
    _icon = "public-ip-address.png"


class PublicIpPrefix(_Networking):
    _icon = "public-ip-prefix.png"


class Relay(_Networking):
    _icon = "relay.png"


class ReservedIpAddressClassic(_Networking):
    _icon = "reserved-ip-address-classic.png"


class RouteFilter(_Networking):
    _icon = "route-filter.png"


class RouteServer(_Networking):
    _icon = "route-server.png"


class RouteTable(_Networking):
    _icon = "route-table.png"


class ServiceEndpoint(_Networking):
    _icon = "service-endpoint.png"


class TrafficManagerProfile(_Networking):
    _icon = "traffic-manager-profile.png"


class VirtualNetworkClassic(_Networking):
    _icon = "virtual-network-classic.png"


class VirtualNetworkFirewall(_Networking):
    _icon = "virtual-network-firewall.png"


class VirtualNetworkGateway(_Networking):
    _icon = "virtual-network-gateway.png"


class VirtualNetworkPeering(_Networking):
    _icon = "virtual-network-peering.png"


class VirtualNetwork(_Networking):
    _icon = "virtual-network.png"


class VirtualSubnet(_Networking):
    _icon = "virtual-subnet.png"


class VirtualWanGateway(_Networking):
    _icon = "virtual-wan-gateway.png"


class VirtualWan(_Networking):
    _icon = "virtual-wan.png"


# Aliases
