# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _New_Icons(_Azure):
    _type = "new_icons"
    _icon_dir = "resources/azure/new_icons"


class AcsSolutionsBuilder(_New_Icons):
    _icon = "acs-solutions-builder.png"


class APIProxy(_New_Icons):
    _icon = "api-proxy.png"


class Aquila(_New_Icons):
    _icon = "aquila.png"


class AvsVM(_New_Icons):
    _icon = "avs-vm.png"


class Azureattestation(_New_Icons):
    _icon = "azureattestation.png"


class Azurite(_New_Icons):
    _icon = "azurite.png"


class Ceres(_New_Icons):
    _icon = "ceres.png"


class ComplianceCenter(_New_Icons):
    _icon = "compliance-center.png"


class ConfidentialLedger(_New_Icons):
    _icon = "confidential-ledger.png"


class ConnectedCache(_New_Icons):
    _icon = "connected-cache.png"


class ConnectedVehiclePlatform(_New_Icons):
    _icon = "connected-vehicle-platform.png"


class ContainerAppEnvironments(_New_Icons):
    _icon = "container-app-environments.png"


class CustomIpPrefix(_New_Icons):
    _icon = "custom-ip-prefix.png"


class DashboardHub(_New_Icons):
    _icon = "dashboard-hub.png"


class DedicatedHsm(_New_Icons):
    _icon = "dedicated-hsm.png"


class EdgeHardwareCenter(_New_Icons):
    _icon = "edge-hardware-center.png"


class EdgeManagement(_New_Icons):
    _icon = "edge-management.png"


class ExchangeOnPremisesAccess(_New_Icons):
    _icon = "exchange-on-premises-access.png"


class Fiji(_New_Icons):
    _icon = "fiji.png"


class Grafana(_New_Icons):
    _icon = "grafana.png"


class HpcWorkbench(_New_Icons):
    _icon = "hpc-workbench.png"


class ImageDefinition(_New_Icons):
    _icon = "image-definition.png"


class ImageVersion(_New_Icons):
    _icon = "image-version.png"


class IntuneTrends(_New_Icons):
    _icon = "intune-trends.png"


class LoadTesting(_New_Icons):
    _icon = "load-testing.png"


class MarketplaceManagement(_New_Icons):
    _icon = "marketplace-management.png"


class MissionLandingZone(_New_Icons):
    _icon = "mission-landing-zone.png"


class ModularDataCenter(_New_Icons):
    _icon = "modular-data-center.png"


class MonitorDashboard(_New_Icons):
    _icon = "monitor-dashboard.png"


class NetworkManager(_New_Icons):
    _icon = "network-manager.png"


class PrivateMobileNetwork(_New_Icons):
    _icon = "private-mobile-network.png"


class ReservedCapacityGroups(_New_Icons):
    _icon = "reserved-capacity-groups.png"


class ReservedCapacity(_New_Icons):
    _icon = "reserved-capacity.png"


class SavingsPlan(_New_Icons):
    _icon = "savings-plan.png"


class SonicDash(_New_Icons):
    _icon = "sonic-dash.png"


class Sphere(_New_Icons):
    _icon = "sphere.png"


class StorageTasks(_New_Icons):
    _icon = "storage-tasks.png"


class SupportCenterBlue(_New_Icons):
    _icon = "support-center-blue.png"


class UpdateCenter(_New_Icons):
    _icon = "update-center.png"


class VMApplicationDefinition(_New_Icons):
    _icon = "vm-application-definition.png"


class VMApplicationVersion(_New_Icons):
    _icon = "vm-application-version.png"


class WebAppDatabase(_New_Icons):
    _icon = "web-app-database.png"


class WebJobs(_New_Icons):
    _icon = "web-jobs.png"


class WindowsNotificationServices(_New_Icons):
    _icon = "windows-notification-services.png"


class WorkerContainerApp(_New_Icons):
    _icon = "worker-container-app.png"


# Aliases
