# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _New_Icons(_Azure):
    _type = "new_icons"
    _icon_dir = "resources/azure/new_icons"


class Aquila(_New_Icons):
    _icon = "aquila.png"


class AvsVM(_New_Icons):
    _icon = "avs-vm.png"


class AzureSphere(_New_Icons):
    _icon = "azure-sphere.png"


class AzureSupportCenterBlue(_New_Icons):
    _icon = "azure-support-center-blue.png"


class Azureattestation(_New_Icons):
    _icon = "azureattestation.png"


class Azurite(_New_Icons):
    _icon = "azurite.png"


class Ceres(_New_Icons):
    _icon = "ceres.png"


class ComplianceCenter(_New_Icons):
    _icon = "compliance-center.png"


class ConnectedCache(_New_Icons):
    _icon = "connected-cache.png"


class ConnectedVehiclePlatform(_New_Icons):
    _icon = "connected-vehicle-platform.png"


class DashboardHub(_New_Icons):
    _icon = "dashboard-hub.png"


class DataCollectionRules(_New_Icons):
    _icon = "data-collection-rules.png"


class DedicatedHsm(_New_Icons):
    _icon = "dedicated-hsm.png"


class EdgeManagement(_New_Icons):
    _icon = "edge-management.png"


class ExchangeOnPremisesAccess(_New_Icons):
    _icon = "exchange-on-premises-access.png"


class Fiji(_New_Icons):
    _icon = "fiji.png"


class IntuneTrends(_New_Icons):
    _icon = "intune-trends.png"


class MarketplaceManagement(_New_Icons):
    _icon = "marketplace-management.png"


class MissionLandingZone(_New_Icons):
    _icon = "mission-landing-zone.png"


class ModularDataCenter(_New_Icons):
    _icon = "modular-data-center.png"


class ReservedCapacity(_New_Icons):
    _icon = "reserved-capacity.png"


class SonicDash(_New_Icons):
    _icon = "sonic-dash.png"


class StorageTasks(_New_Icons):
    _icon = "storage-tasks.png"


class WebAppDatabase(_New_Icons):
    _icon = "web-app-database.png"


class WebJobs(_New_Icons):
    _icon = "web-jobs.png"


class WindowsNotificationServices(_New_Icons):
    _icon = "windows-notification-services.png"


class WorkerContainerApp(_New_Icons):
    _icon = "worker-container-app.png"


# Aliases
