# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Office365(_Azure):
    _type = "office365"
    _icon_dir = "resources/azure/office365"


class O365Access(_Office365):
    _icon = "o365---access.png"


class O365APIDropbox(_Office365):
    _icon = "o365---api-dropbox.png"


class O365APIDynamicsCrm(_Office365):
    _icon = "o365---api-dynamics-crm.png"


class O365APIFacebook(_Office365):
    _icon = "o365---api-facebook.png"


class O365APIGoogleDrive(_Office365):
    _icon = "o365---api-google-drive.png"


class O365APIOffice365(_Office365):
    _icon = "o365---api-office-365.png"


class O365APISharepoint(_Office365):
    _icon = "o365---api-sharepoint.png"


class O365APISQL(_Office365):
    _icon = "o365---api-sql.png"


class O365APITwitter(_Office365):
    _icon = "o365---api-twitter.png"


class O365APIYammer(_Office365):
    _icon = "o365---api-yammer.png"


class O365Dataverse(_Office365):
    _icon = "o365---dataverse.png"


class O365Delve(_Office365):
    _icon = "o365---delve.png"


class O365Dynamics(_Office365):
    _icon = "o365---dynamics.png"


class O365Excel(_Office365):
    _icon = "o365---excel.png"


class O365Exchange(_Office365):
    _icon = "o365---exchange.png"


class O365Forms(_Office365):
    _icon = "o365---forms.png"


class O365List(_Office365):
    _icon = "o365---list.png"


class O365Onedrive(_Office365):
    _icon = "o365---onedrive.png"


class O365Onenote(_Office365):
    _icon = "o365---onenote.png"


class O365Outlook(_Office365):
    _icon = "o365---outlook.png"


class O365Planner(_Office365):
    _icon = "o365---planner.png"


class O365PowerAppVirtualAgent(_Office365):
    _icon = "o365---power-app-virtual-agent.png"


class O365PowerApp(_Office365):
    _icon = "o365---power-app.png"


class O365PowerAutomate(_Office365):
    _icon = "o365---power-automate.png"


class O365Powerpoint(_Office365):
    _icon = "o365---powerpoint.png"


class O365Project(_Office365):
    _icon = "o365---project.png"


class O365Publisher(_Office365):
    _icon = "o365---publisher.png"


class O365Sharepoint(_Office365):
    _icon = "o365---sharepoint.png"


class O365Stream(_Office365):
    _icon = "o365---stream.png"


class O365Sway(_Office365):
    _icon = "o365---sway.png"


class O365Teams(_Office365):
    _icon = "o365---teams.png"


class O365Visio(_Office365):
    _icon = "o365---visio.png"


class O365Yammer(_Office365):
    _icon = "o365---yammer.png"


class O365(_Office365):
    _icon = "o365.png"


# Aliases
