# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Other(_Azure):
    _type = "other"
    _icon_dir = "resources/azure/other"


class BackupCenter(_Other):
    _icon = "backup-center.png"


class Detonation(_Other):
    _icon = "detonation.png"


class ExpressrouteDirect(_Other):
    _icon = "expressroute-direct.png"


class InstancePools(_Other):
    _icon = "instance-pools.png"


class InternetAnalyzerProfiles(_Other):
    _icon = "internet-analyzer-profiles.png"


class LocalNetworkGateways(_Other):
    _icon = "local-network-gateways.png"


class PeeringService(_Other):
    _icon = "peering-service.png"


class ResourceMover(_Other):
    _icon = "resource-mover.png"


class SshKeys(_Other):
    _icon = "ssh-keys.png"


class TemplateSpecs(_Other):
    _icon = "template-specs.png"


class UniversalPrint(_Other):
    _icon = "universal-print.png"


class WindowsVirtualDesktop(_Other):
    _icon = "windows-virtual-desktop.png"


# Aliases
