# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Other(_Azure):
    _type = "other"
    _icon_dir = "resources/azure/other"


class BackupCenter(_Other):
    _icon = "backup-center.png"


class BareMetalInfrastructure(_Other):
    _icon = "bare-metal-infrastructure.png"


class ChaosStudio(_Other):
    _icon = "chaos-studio.png"


class CloudServicesExtendedSupport(_Other):
    _icon = "cloud-services-extended-support.png"


class CloudShell(_Other):
    _icon = "cloud-shell.png"


class CommunicationServices(_Other):
    _icon = "communication-services.png"


class DeviceUpdateIotHub(_Other):
    _icon = "device-update-iot-hub.png"


class DiskPool(_Other):
    _icon = "disk-pool.png"


class ExpressrouteDirect(_Other):
    _icon = "expressroute-direct.png"


class InstancePools(_Other):
    _icon = "instance-pools.png"


class InternetAnalyzerProfiles(_Other):
    _icon = "internet-analyzer-profiles.png"


class LoadTesting(_Other):
    _icon = "load-testing.png"


class LocalNetworkGateways(_Other):
    _icon = "local-network-gateways.png"


class ManagedInstanceApacheCassandra(_Other):
    _icon = "managed-instance-apache-cassandra.png"


class NetworkFunctionManager(_Other):
    _icon = "network-function-manager.png"


class OpenSupplyChainPlatform(_Other):
    _icon = "open-supply-chain-platform.png"


class Orbital(_Other):
    _icon = "orbital.png"


class PeeringService(_Other):
    _icon = "peering-service.png"


class Quotas(_Other):
    _icon = "quotas.png"


class ResourceMover(_Other):
    _icon = "resource-mover.png"


class Rtos(_Other):
    _icon = "rtos.png"


class SshKeys(_Other):
    _icon = "ssh-keys.png"


class TemplateSpecs(_Other):
    _icon = "template-specs.png"


class TestBase(_Other):
    _icon = "test-base.png"


class Wac(_Other):
    _icon = "wac.png"


class WindowsVirtualDesktop(_Other):
    _icon = "windows-virtual-desktop.png"


# Aliases
