# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Preview(_Azure):
    _type = "preview"
    _icon_dir = "resources/azure/preview"


class CloudShell(_Preview):
    _icon = "cloud-shell.png"


class IotEdge(_Preview):
    _icon = "iot-edge.png"


class PrivateLinkHub(_Preview):
    _icon = "private-link-hub.png"


class Rtos(_Preview):
    _icon = "rtos.png"


class Sphere(_Preview):
    _icon = "sphere.png"


class StaticApps(_Preview):
    _icon = "static-apps.png"


class TimeSeriesDataSets(_Preview):
    _icon = "time-series-data-sets.png"


class WebEnvironment(_Preview):
    _icon = "web-environment.png"


class Workbooks(_Preview):
    _icon = "workbooks.png"


# Aliases
