# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Security(_Azure):
    _type = "security"
    _icon_dir = "resources/azure/security"


class ApplicationSecurityGroups(_Security):
    _icon = "application-security-groups.png"


class ConditionalAccess(_Security):
    _icon = "conditional-access.png"


class Detonation(_Security):
    _icon = "detonation.png"


class Extendedsecurityupdates(_Security):
    _icon = "extendedsecurityupdates.png"


class KeyVaults(_Security):
    _icon = "key-vaults.png"


class MicrosoftDefenderForCloud(_Security):
    _icon = "microsoft-defender-for-cloud.png"


class MicrosoftDefender(_Security):
    _icon = "microsoft-defender.png"


class Sentinel(_Security):
    _icon = "sentinel.png"


# Aliases
