# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Storage(_Azure):
    _type = "storage"
    _icon_dir = "resources/azure/storage"


class DataBoxEdge(_Storage):
    _icon = "data-box-edge.png"


class DataBox(_Storage):
    _icon = "data-box.png"


class DataLakeStorageGen1(_Storage):
    _icon = "data-lake-storage-gen1.png"


class DataShareInvitations(_Storage):
    _icon = "data-share-invitations.png"


class DataShares(_Storage):
    _icon = "data-shares.png"


class HcpCache(_Storage):
    _icon = "hcp-cache.png"


class ImportExportJobs(_Storage):
    _icon = "import-export-jobs.png"


class NetappFiles(_Storage):
    _icon = "netapp-files.png"


class RecoveryServicesVaults(_Storage):
    _icon = "recovery-services-vaults.png"


class StackEdge(_Storage):
    _icon = "stack-edge.png"


class StorageAccountsClassic(_Storage):
    _icon = "storage-accounts-classic.png"


class StorageAccounts(_Storage):
    _icon = "storage-accounts.png"


class StorageSyncServices(_Storage):
    _icon = "storage-sync-services.png"


class StorsimpleDataManagers(_Storage):
    _icon = "storsimple-data-managers.png"


class StorsimpleDeviceManagers(_Storage):
    _icon = "storsimple-device-managers.png"


# Aliases
