# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Storage(_Azure):
    _type = "storage"
    _icon_dir = "resources/azure/storage"


class AzureDataboxGateway(_Storage):
    _icon = "azure-databox-gateway.png"


class AzureFileshares(_Storage):
    _icon = "azure-fileshares.png"


class AzureHcpCache(_Storage):
    _icon = "azure-hcp-cache.png"


class AzureNetappFiles(_Storage):
    _icon = "azure-netapp-files.png"


class AzureStackEdge(_Storage):
    _icon = "azure-stack-edge.png"


class DataBox(_Storage):
    _icon = "data-box.png"


class DataLakeStorageGen1(_Storage):
    _icon = "data-lake-storage-gen1.png"


class DataShareInvitations(_Storage):
    _icon = "data-share-invitations.png"


class DataShares(_Storage):
    _icon = "data-shares.png"


class ImportExportJobs(_Storage):
    _icon = "import-export-jobs.png"


class RecoveryServicesVaults(_Storage):
    _icon = "recovery-services-vaults.png"


class StorageAccountsClassic(_Storage):
    _icon = "storage-accounts-classic.png"


class StorageAccounts(_Storage):
    _icon = "storage-accounts.png"


class StorageExplorer(_Storage):
    _icon = "storage-explorer.png"


class StorageSyncServices(_Storage):
    _icon = "storage-sync-services.png"


class StorsimpleDataManagers(_Storage):
    _icon = "storsimple-data-managers.png"


# Aliases
