# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Workload(_Azure):
    _type = "workload"
    _icon_dir = "resources/azure/workload"


class ActiveDirectoryDomainServices(_Workload):
    _icon = "active-directory-domain-services.png"


class ActiveDirectoryFederationProxy(_Workload):
    _icon = "active-directory-federation-proxy.png"


class ActiveDirectoryFederationServices(_Workload):
    _icon = "active-directory-federation-services.png"


class ActiveDirectoryLightweightDirectoryServices(_Workload):
    _icon = "active-directory-lightweight-directory-services.png"


class ActiveDirectoryRightsManagementServer(_Workload):
    _icon = "active-directory-rights-management-server.png"


class ApplicationServer(_Workload):
    _icon = "application-server.png"


class AzureActiveDirectorySyncPrimary(_Workload):
    _icon = "azure-active-directory-sync-primary.png"


class AzureActiveDirectorySyncStandby(_Workload):
    _icon = "azure-active-directory-sync-standby.png"


class AzureFileSyncServer(_Workload):
    _icon = "azure-file-sync-server.png"


class CertificatationAuthorityEnrollmentWebService(_Workload):
    _icon = "certificatation-authority-enrollment-web-service.png"


class CertificationAuthorityOnlineResponder(_Workload):
    _icon = "certification-authority-online-responder.png"


class CertificationAuthorityPolicyWebService(_Workload):
    _icon = "certification-authority-policy-web-service.png"


class CertificationAuthorityStandalone(_Workload):
    _icon = "certification-authority-standalone.png"


class CertificationAuthorityWebEnrollment(_Workload):
    _icon = "certification-authority-web-enrollment.png"


class CertificationAuthority(_Workload):
    _icon = "certification-authority.png"


class DatabaseServerGeneric(_Workload):
    _icon = "database-server-generic.png"


class DatabaseServerSQL(_Workload):
    _icon = "database-server-sql.png"


class EnterpriseCertificationAuthorityOfflineRoot(_Workload):
    _icon = "enterprise-certification-authority-offline-root.png"


class EnterpriseCertificationAuthorityRoot(_Workload):
    _icon = "enterprise-certification-authority-root.png"


class EnterpriseCertificationAuthoritySubordinate(_Workload):
    _icon = "enterprise-certification-authority-subordinate.png"


class ExchangeClientAccessServer(_Workload):
    _icon = "exchange-client-access-server.png"


class ExchangeEdgeTransportServer(_Workload):
    _icon = "exchange-edge-transport-server.png"


class ExchangeHubTransportServer(_Workload):
    _icon = "exchange-hub-transport-server.png"


class ExchangeMailboxServer(_Workload):
    _icon = "exchange-mailbox-server.png"


class FileServer(_Workload):
    _icon = "file-server.png"


class FtpServer(_Workload):
    _icon = "ftp-server.png"


class GenericEmailServer(_Workload):
    _icon = "generic-email-server.png"


class NetworkDeviceEnrollmentService(_Workload):
    _icon = "network-device-enrollment-service.png"


class ProxyServer(_Workload):
    _icon = "proxy-server.png"


class ServerCluster(_Workload):
    _icon = "server-cluster.png"


class WebServer(_Workload):
    _icon = "web-server.png"


# Aliases
