# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _GIS


class _Cli(_GIS):
    _type = "cli"
    _icon_dir = "resources/gis/cli"


class Gdal(_Cli):
    _icon = "gdal.png"


# Aliases
