"""Deprecated backward-compatibility alias. NOT regenerated by autogen.sh.

This module shipped since #847, but its icon directory (resources/gis/cplusplus)
never did, so `diagrams.gis.cplusplus.Mapnik` always rendered a blank node.
The working node is `diagrams.gis.cli.Mapnik`; this alias keeps old imports
running and should be removed in the next major release.
"""

import warnings

from diagrams.gis.cli import Mapnik  # noqa: F401

warnings.warn(
    "diagrams.gis.cplusplus is deprecated and will be removed in a future release; "
    "import Mapnik from diagrams.gis.cli instead.",
    DeprecationWarning,
    stacklevel=2,
)
