# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _GIS


class _Database(_GIS):
    _type = "database"
    _icon_dir = "resources/gis/database"


class Postgis(_Database):
    _icon = "postgis.png"


# Aliases
