# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _GIS


class _Geocoding(_GIS):
    _type = "geocoding"
    _icon_dir = "resources/gis/geocoding"


class Addok(_Geocoding):
    _icon = "addok.png"


class Gisgraphy(_Geocoding):
    _icon = "gisgraphy.png"


class Nominatim(_Geocoding):
    _icon = "nominatim.png"


class Pelias(_Geocoding):
    _icon = "pelias.png"


# Aliases
