# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _GIS


class _Javascript(_GIS):
    _type = "javascript"
    _icon_dir = "resources/gis/javascript"


class Maplibre(_Javascript):
    _icon = "maplibre.png"


class OlExt(_Javascript):
    _icon = "ol-ext.png"


class Openlayers(_Javascript):
    _icon = "openlayers.png"


class Turfjs(_Javascript):
    _icon = "turfjs.png"


# Aliases
