# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _GIS


class _Python(_GIS):
    _type = "python"
    _icon_dir = "resources/gis/python"


class Geopandas(_Python):
    _icon = "geopandas.png"


class Pysal(_Python):
    _icon = "pysal.png"


# Aliases
