# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _GIS


class _Server(_GIS):
    _type = "server"
    _icon_dir = "resources/gis/server"


class Geoserver(_Server):
    _icon = "geoserver.png"


class Mapserver(_Server):
    _icon = "mapserver.png"


class QgisServer(_Server):
    _icon = "qgis-server.png"


# Aliases
