# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Compute(_OCI):
    _type = "compute"
    _icon_dir = "resources/oci/compute"


class BmWhite(_Compute):
    _icon = "bm-white.png"


class Bm(_Compute):
    _icon = "bm.png"


class ContainerWhite(_Compute):
    _icon = "container-white.png"


class Container(_Compute):
    _icon = "container.png"


class VmWhite(_Compute):
    _icon = "vm-white.png"


class Vm(_Compute):
    _icon = "vm.png"


# Aliases

VirtualMachine = Vm
VirtualMachineWhite = VmWhite
BareMetal = Bm
BareMetalWhite = BmWhite
