# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Compute(_OCI):
    _type = "compute"
    _icon_dir = "resources/oci/compute"


class Bm(_Compute):
    _icon = "bm.png"


class Container(_Compute):
    _icon = "container.png"


class Vm(_Compute):
    _icon = "vm.png"


# Aliases

VirtualMachine = Vm
BareMetal = Bm
