# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Connectivity(_OCI):
    _type = "connectivity"
    _icon_dir = "resources/oci/connectivity"


class BackboneGrey(_Connectivity):
    _icon = "backbone-grey.png"


class Backbone(_Connectivity):
    _icon = "backbone.png"


class CustomerdatacenterGrey(_Connectivity):
    _icon = "customerdatacenter-grey.png"


class Customerdatacenter(_Connectivity):
    _icon = "customerdatacenter.png"


class CustomerpremisesequipGrey(_Connectivity):
    _icon = "customerpremisesequip-grey.png"


class Customerpremisesequip(_Connectivity):
    _icon = "customerpremisesequip.png"


class FastconnectGrey(_Connectivity):
    _icon = "fastconnect-grey.png"


class Fastconnect(_Connectivity):
    _icon = "fastconnect.png"


class VpnGrey(_Connectivity):
    _icon = "vpn-grey.png"


class Vpn(_Connectivity):
    _icon = "vpn.png"


# Aliases
