# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Connectivity(_OCI):
    _type = "connectivity"
    _icon_dir = "resources/oci/connectivity"


class Backbone(_Connectivity):
    _icon = "backbone.png"


class CDN(_Connectivity):
    _icon = "cdn.png"


class CustomerDatacenter(_Connectivity):
    _icon = "customer-datacenter.png"


class CustomerPremise(_Connectivity):
    _icon = "customer-premise.png"


class Datacenter(_Connectivity):
    _icon = "datacenter.png"


class DisconnectedRegions(_Connectivity):
    _icon = "disconnected-regions.png"


class DNS(_Connectivity):
    _icon = "dns.png"


class FastConnect(_Connectivity):
    _icon = "fast-connect.png"


class LocalPeeringGateway(_Connectivity):
    _icon = "local-peering-gateway.png"


class NATGateway(_Connectivity):
    _icon = "nat-gateway.png"


class RemotePeeringGateway(_Connectivity):
    _icon = "remote-peering-gateway.png"


class ServiceConnectorHub(_Connectivity):
    _icon = "service-connector-hub.png"


class VPN(_Connectivity):
    _icon = "vpn.png"


# Aliases
