# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Connectivity(_OCI):
    _type = "connectivity"
    _icon_dir = "resources/oci/connectivity"


class BackboneWhite(_Connectivity):
    _icon = "backbone-white.png"


class Backbone(_Connectivity):
    _icon = "backbone.png"


class CustomerdatacenterWhite(_Connectivity):
    _icon = "customerdatacenter-white.png"


class Customerdatacenter(_Connectivity):
    _icon = "customerdatacenter.png"


class CustomerpremisesequipWhite(_Connectivity):
    _icon = "customerpremisesequip-white.png"


class Customerpremisesequip(_Connectivity):
    _icon = "customerpremisesequip.png"


class FastconnectWhite(_Connectivity):
    _icon = "fastconnect-white.png"


class Fastconnect(_Connectivity):
    _icon = "fastconnect.png"


class VpnWhite(_Connectivity):
    _icon = "vpn-white.png"


class Vpn(_Connectivity):
    _icon = "vpn.png"


# Aliases
