# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Devops(_OCI):
    _type = "devops"
    _icon_dir = "resources/oci/devops"


class Analytics(_Devops):
    _icon = "analytics.png"


class APIGateway(_Devops):
    _icon = "api-gateway.png"


class APIService(_Devops):
    _icon = "api-service.png"


class MarketPlace(_Devops):
    _icon = "market-place.png"


class ResourceMgmt(_Devops):
    _icon = "resource-mgmt.png"


# Aliases
