# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Edge(_OCI):
    _type = "edge"
    _icon_dir = "resources/oci/edge"


class Cdn(_Edge):
    _icon = "cdn.png"


class Dns(_Edge):
    _icon = "dns.png"


class Emaildelivery(_Edge):
    _icon = "emaildelivery.png"


class Waf(_Edge):
    _icon = "waf.png"


# Aliases
