# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Edge(_OCI):
    _type = "edge"
    _icon_dir = "resources/oci/edge"


class CdnWhite(_Edge):
    _icon = "cdn-white.png"


class Cdn(_Edge):
    _icon = "cdn.png"


class DnsWhite(_Edge):
    _icon = "dns-white.png"


class Dns(_Edge):
    _icon = "dns.png"


class EmaildeliveryWhite(_Edge):
    _icon = "emaildelivery-white.png"


class Emaildelivery(_Edge):
    _icon = "emaildelivery.png"


class WafWhite(_Edge):
    _icon = "waf-white.png"


class Waf(_Edge):
    _icon = "waf.png"


# Aliases
