# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Governance(_OCI):
    _type = "governance"
    _icon_dir = "resources/oci/governance"


class Audit(_Governance):
    _icon = "audit.png"


class Compartments(_Governance):
    _icon = "compartments.png"


class FlowLogs(_Governance):
    _icon = "flow-logs.png"


class Groups(_Governance):
    _icon = "groups.png"


class Logging(_Governance):
    _icon = "logging.png"


class OCID(_Governance):
    _icon = "ocid.png"


class Policies(_Governance):
    _icon = "policies.png"


class Tagging(_Governance):
    _icon = "tagging.png"


class User(_Governance):
    _icon = "user.png"


# Aliases
