# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Ml(_OCI):
    _type = "ml"
    _icon_dir = "resources/oci/ml"


class ArtificialIntelligence(_Ml):
    _icon = "artificial-intelligence.png"


class MachineLearning(_Ml):
    _icon = "machine-learning.png"


# Aliases
