# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Monitoring(_OCI):
    _type = "monitoring"
    _icon_dir = "resources/oci/monitoring"


class Alarm(_Monitoring):
    _icon = "alarm.png"


class Event(_Monitoring):
    _icon = "event.png"


class Healthcheck(_Monitoring):
    _icon = "healthcheck.png"


class Logging(_Monitoring):
    _icon = "logging.png"


class Notifications(_Monitoring):
    _icon = "notifications.png"


class Queuing(_Monitoring):
    _icon = "queuing.png"


class Search(_Monitoring):
    _icon = "search.png"


class Streaming(_Monitoring):
    _icon = "streaming.png"


class Telemetry(_Monitoring):
    _icon = "telemetry.png"


class Workflow(_Monitoring):
    _icon = "workflow.png"


# Aliases
