# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Monitoring(_OCI):
    _type = "monitoring"
    _icon_dir = "resources/oci/monitoring"


class AlarmWhite(_Monitoring):
    _icon = "alarm-white.png"


class Alarm(_Monitoring):
    _icon = "alarm.png"


class EventWhite(_Monitoring):
    _icon = "event-white.png"


class Event(_Monitoring):
    _icon = "event.png"


class HealthcheckWhite(_Monitoring):
    _icon = "healthcheck-white.png"


class Healthcheck(_Monitoring):
    _icon = "healthcheck.png"


class LoggingWhite(_Monitoring):
    _icon = "logging-white.png"


class Logging(_Monitoring):
    _icon = "logging.png"


class NotificationsWhite(_Monitoring):
    _icon = "notifications-white.png"


class Notifications(_Monitoring):
    _icon = "notifications.png"


class QueuingWhite(_Monitoring):
    _icon = "queuing-white.png"


class Queuing(_Monitoring):
    _icon = "queuing.png"


class SearchWhite(_Monitoring):
    _icon = "search-white.png"


class Search(_Monitoring):
    _icon = "search.png"


class StreamingWhite(_Monitoring):
    _icon = "streaming-white.png"


class Streaming(_Monitoring):
    _icon = "streaming.png"


class TelemetryWhite(_Monitoring):
    _icon = "telemetry-white.png"


class Telemetry(_Monitoring):
    _icon = "telemetry.png"


class WorkflowWhite(_Monitoring):
    _icon = "workflow-white.png"


class Workflow(_Monitoring):
    _icon = "workflow.png"


# Aliases
