# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Monitoring(_OCI):
    _type = "monitoring"
    _icon_dir = "resources/oci/monitoring"


class Alarm(_Monitoring):
    _icon = "alarm.png"


class Email(_Monitoring):
    _icon = "email.png"


class Events(_Monitoring):
    _icon = "events.png"


class HealthCheck(_Monitoring):
    _icon = "health-check.png"


class Notifications(_Monitoring):
    _icon = "notifications.png"


class Queue(_Monitoring):
    _icon = "queue.png"


class Search(_Monitoring):
    _icon = "search.png"


class Telemetry(_Monitoring):
    _icon = "telemetry.png"


class Workflow(_Monitoring):
    _icon = "workflow.png"


# Aliases
