# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Network(_OCI):
    _type = "network"
    _icon_dir = "resources/oci/network"


class CloudService(_Network):
    _icon = "cloud-service.png"


class Drg(_Network):
    _icon = "drg.png"


class Firewall(_Network):
    _icon = "firewall.png"


class InternetGateway(_Network):
    _icon = "internet-gateway.png"


class LoadBalancer(_Network):
    _icon = "load-balancer.png"


class RouteTable(_Network):
    _icon = "route-table.png"


class Router(_Network):
    _icon = "router.png"


class SecurityLists(_Network):
    _icon = "security-lists.png"


class ServiceGateway(_Network):
    _icon = "service-gateway.png"


class Switch(_Network):
    _icon = "switch.png"


class Vcn(_Network):
    _icon = "vcn.png"


# Aliases
