# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _OCI(_OCI):
    _type = "oci"
    _icon_dir = "resources/oci/oci"


class OCI(_OCI):
    _icon = "oci.png"


# Aliases
