# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Security(_OCI):
    _type = "security"
    _icon_dir = "resources/oci/security"


class Audit(_Security):
    _icon = "audit.png"


class Compartments(_Security):
    _icon = "compartments.png"


class Ddos(_Security):
    _icon = "ddos.png"


class Encryption(_Security):
    _icon = "encryption.png"


class Groups(_Security):
    _icon = "groups.png"


class IdAccess(_Security):
    _icon = "id-access.png"


class Keymgmt(_Security):
    _icon = "keymgmt.png"


class Ocid(_Security):
    _icon = "ocid.png"


class Policies(_Security):
    _icon = "policies.png"


class Tagging(_Security):
    _icon = "tagging.png"


# Aliases
