# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Storage(_OCI):
    _type = "storage"
    _icon_dir = "resources/oci/storage"


class BackupRestore(_Storage):
    _icon = "backup-restore.png"


class BlockStorageClone(_Storage):
    _icon = "block-storage-clone.png"


class BlockStorage(_Storage):
    _icon = "block-storage.png"


class Buckets(_Storage):
    _icon = "buckets.png"


class DataTransfer(_Storage):
    _icon = "data-transfer.png"


class ElasticPerformance(_Storage):
    _icon = "elastic-performance.png"


class FileStorage(_Storage):
    _icon = "file-storage.png"


class LocalStorage(_Storage):
    _icon = "local-storage.png"


class ObjectStorage(_Storage):
    _icon = "object-storage.png"


class PersistentVolume(_Storage):
    _icon = "persistent-volume.png"


class StorageGateway(_Storage):
    _icon = "storage-gateway.png"


# Aliases
