# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OCI


class _Storage(_OCI):
    _type = "storage"
    _icon_dir = "resources/oci/storage"


class Backuprestore(_Storage):
    _icon = "backuprestore.png"


class Blockstorage(_Storage):
    _icon = "blockstorage.png"


class Buckets(_Storage):
    _icon = "buckets.png"


class Datatransfer(_Storage):
    _icon = "datatransfer.png"


class Filestorage(_Storage):
    _icon = "filestorage.png"


class Objectstorage(_Storage):
    _icon = "objectstorage.png"


class Storagegateway(_Storage):
    _icon = "storagegateway.png"


# Aliases
