# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _GCP


class _GCP(_GCP):
    _type = "gcp"
    _icon_dir = "resources/gcp/gcp"


class GCP(_GCP):
    _icon = "gcp.png"


# Aliases
