# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _GCP


class _General(_GCP):
    _type = "general"
    _icon_dir = "resources/gcp/general"


class GoogleCloudPlatform(_General):
    _icon = "google-cloud-platform.png"


class GenericService(_General):
    _icon = "generic-service.png"
