# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _HashiCorp


class _Applications(_HashiCorp):
    _type = "applications"
    _icon_dir = "resources/hashicorp/applications"


class Nomad(_Applications):
    _icon = "nomad.png"


class Vagrant(_Applications):
    _icon = "vagrant.png"


class Waypoint(_Applications):
    _icon = "waypoint.png"


# Aliases
