# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _HashiCorp


class _Infrastructure(_HashiCorp):
    _type = "infrastructure"
    _icon_dir = "resources/hashicorp/infrastructure"


class Packer(_Infrastructure):
    _icon = "packer.png"


class Terraform(_Infrastructure):
    _icon = "terraform.png"


# Aliases
