# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _HashiCorp


class _Networking(_HashiCorp):
    _type = "networking"
    _icon_dir = "resources/hashicorp/networking"


class Consul(_Networking):
    _icon = "consul.png"


# Aliases
