# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _HashiCorp


class _Security(_HashiCorp):
    _type = "security"
    _icon_dir = "resources/hashicorp/security"


class Boundary(_Security):
    _icon = "boundary.png"


class Vault(_Security):
    _icon = "vault.png"


# Aliases
