# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Outscale


class _Outscale(_Outscale):
    _type = "outscale"
    _icon_dir = "resources/outscale/outscale"


class Outscale(_Outscale):
    _icon = "outscale.png"


# Aliases
