# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Programming


class _Containers(_Programming):
    _type = "containers"
    _icon_dir = "resources/programming/containers"


class Helm(_Containers):
    _icon = "helm.png"


class Krew(_Containers):
    _icon = "krew.png"


class Kustomize(_Containers):
    _icon = "kustomize.png"


# Aliases
