# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Programming


class _Telemetry(_Programming):
    _type = "telemetry"
    _icon_dir = "resources/programming/telemetry"


class Opencensus(_Telemetry):
    _icon = "opencensus.png"


class Openmetrics(_Telemetry):
    _icon = "openmetrics.png"


class Opentelemetry(_Telemetry):
    _icon = "opentelemetry.png"


class Opentracing(_Telemetry):
    _icon = "opentracing.png"


# Aliases
