# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Ai(_SAP):
    _type = "ai"
    _icon_dir = "resources/sap/ai"


class AiCore(_Ai):
    _icon = "ai-core.png"


class AiCore_Circle(_Ai):
    _icon = "ai-core_circle.png"


class BusinessEntityRecognition(_Ai):
    _icon = "business-entity-recognition.png"


class BusinessEntityRecognition_Circle(_Ai):
    _icon = "business-entity-recognition_circle.png"


class DataAttributeRecommendation(_Ai):
    _icon = "data-attribute-recommendation.png"


class DataAttributeRecommendation_Circle(_Ai):
    _icon = "data-attribute-recommendation_circle.png"


class DocumentClassification(_Ai):
    _icon = "document-classification.png"


class DocumentClassification_Circle(_Ai):
    _icon = "document-classification_circle.png"


class DocumentInformationExtraction(_Ai):
    _icon = "document-information-extraction.png"


class DocumentInformationExtraction_Circle(_Ai):
    _icon = "document-information-extraction_circle.png"


class InvoiceObjectRecommendation(_Ai):
    _icon = "invoice-object-recommendation.png"


class InvoiceObjectRecommendation_Circle(_Ai):
    _icon = "invoice-object-recommendation_circle.png"


class SAPConversationalAi(_Ai):
    _icon = "sap-conversational-ai.png"


class SAPConversationalAi_Circle(_Ai):
    _icon = "sap-conversational-ai_circle.png"


class SAPTranslationHub(_Ai):
    _icon = "sap-translation-hub.png"


class SAPTranslationHub_Circle(_Ai):
    _icon = "sap-translation-hub_circle.png"


class ServiceTicketIntelligence(_Ai):
    _icon = "service-ticket-intelligence.png"


class ServiceTicketIntelligence_Circle(_Ai):
    _icon = "service-ticket-intelligence_circle.png"


# Aliases
