# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _AI(_SAP):
    _type = "ai"
    _icon_dir = "resources/sap/ai"


class BusinessEntityRecognition(_AI):
    _icon = "business-entity-recognition.png"


class DataAttributeRecommendation(_AI):
    _icon = "data-attribute-recommendation.png"


class DocumentInformationExtraction(_AI):
    _icon = "document-information-extraction.png"


class InvoiceObjectRecommendation(_AI):
    _icon = "invoice-object-recommendation.png"


class PersonalizedRecommendation(_AI):
    _icon = "personalized-recommendation.png"


class SAPAILaunchpad(_AI):
    _icon = "sap-ai-launchpad.png"


class SAPDigitalAssistant(_AI):
    _icon = "sap-digital-assistant.png"


class SAPDocumentGrounding(_AI):
    _icon = "sap-document-grounding.png"


class SAPTranslationHub(_AI):
    _icon = "sap-translation-hub.png"


class ServiceTicketIntelligence(_AI):
    _icon = "service-ticket-intelligence.png"


# Aliases
