# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Ai(_SAP):
    _type = "ai"
    _icon_dir = "resources/sap/ai"


class BusinessEntityRecognition(_Ai):
    _icon = "business-entity-recognition.png"


class ConversationalAi(_Ai):
    _icon = "conversational-ai.png"


class DataAttributeRecommendation(_Ai):
    _icon = "data-attribute-recommendation.png"


class DocumentClassification(_Ai):
    _icon = "document-classification.png"


class DocumentInformationExtraction(_Ai):
    _icon = "document-information-extraction.png"


class InvoiceRecommendation(_Ai):
    _icon = "invoice-recommendation.png"


class PersonalizedRecommendation(_Ai):
    _icon = "personalized-recommendation.png"


class SAPAiLaunchpad(_Ai):
    _icon = "sap-ai-launchpad.png"


class SAPDigitalAssistantService(_Ai):
    _icon = "sap-digital-assistant-service.png"


class SAPDocumentTranslation(_Ai):
    _icon = "sap-document-translation.png"


class SAPTranslationHub(_Ai):
    _icon = "sap-translation-hub.png"


class ServiceTicketIntelligence(_Ai):
    _icon = "service-ticket-intelligence.png"


# Aliases
