# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Analytics(_SAP):
    _type = "analytics"
    _icon_dir = "resources/sap/analytics"


class SAPAnalyticsCloud(_Analytics):
    _icon = "sap-analytics-cloud.png"


class SAPAnalyticsCloud_Circle(_Analytics):
    _icon = "sap-analytics-cloud_circle.png"


# Aliases
