# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Analytics(_SAP):
    _type = "analytics"
    _icon_dir = "resources/sap/analytics"


class SAPAnalyticsCloudEmbeddedEdition(_Analytics):
    _icon = "sap-analytics-cloud-embedded-edition.png"


class SAPAnalyticsCloud(_Analytics):
    _icon = "sap-analytics-cloud.png"


class SAPDataIntelligence(_Analytics):
    _icon = "sap-data-intelligence.png"


class SAPDatasphere(_Analytics):
    _icon = "sap-datasphere.png"


class WebAnalytics(_Analytics):
    _icon = "web-analytics.png"


# Aliases
