# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _App_Dev_Automation(_SAP):
    _type = "app_dev_automation"
    _icon_dir = "resources/sap/app_dev_automation"


class ApplicationFrontendService(_App_Dev_Automation):
    _icon = "application-frontend-service.png"


class ExtensibilityServiceForSAPBTP(_App_Dev_Automation):
    _icon = "extensibility-service-for-sap-btp.png"


class Joule_Studio(_App_Dev_Automation):
    _icon = "joule_studio.png"


class SAPBtp_AbapEnvironment(_App_Dev_Automation):
    _icon = "sap-btp_abap-environment.png"


class SAPBuildApps(_App_Dev_Automation):
    _icon = "sap-build-apps.png"


class SAPBuildCode(_App_Dev_Automation):
    _icon = "sap-build-code.png"


class SAPBuildProcessAutomation(_App_Dev_Automation):
    _icon = "sap-build-process-automation.png"


class SAPBuildWorkZone(_App_Dev_Automation):
    _icon = "sap-build-work-zone.png"


class SAPBuildWorkZone_AdvancedEdition(_App_Dev_Automation):
    _icon = "sap-build-work-zone_advanced-edition.png"


class SAPBuild(_App_Dev_Automation):
    _icon = "sap-build.png"


class SAPBusinessApplicationStudio(_App_Dev_Automation):
    _icon = "sap-business-application-studio.png"


class SAPCloudApplicationProgrammingModel(_App_Dev_Automation):
    _icon = "sap-cloud-application-programming-model.png"


class SAPHtml5ApplicationRepositoryServiceForSAPBTP(_App_Dev_Automation):
    _icon = "sap-html5-application-repository-service-for-sap-btp.png"


class SAPMobileServices(_App_Dev_Automation):
    _icon = "sap-mobile-services.png"


class SAPTaskCenter(_App_Dev_Automation):
    _icon = "sap-task-center.png"


class SAPUiThemeDesigner(_App_Dev_Automation):
    _icon = "sap-ui-theme-designer.png"


class Ui5FlexibilityForKeyUsers(_App_Dev_Automation):
    _icon = "ui5-flexibility-for-key-users.png"


# Aliases
