# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Brands(_SAP):
    _type = "brands"
    _icon_dir = "resources/sap/brands"


class SAPAriba(_Brands):
    _icon = "sap-ariba.png"


class SAPBusinessNetwork(_Brands):
    _icon = "sap-business-network.png"


class SAPConcur(_Brands):
    _icon = "sap-concur.png"


class SAPCustomerExperience(_Brands):
    _icon = "sap-customer-experience.png"


class SAPLeanix(_Brands):
    _icon = "sap-leanix.png"


class SAPS4HANACloud(_Brands):
    _icon = "sap-s4hana-cloud.png"


class SAPS4HANA(_Brands):
    _icon = "sap-s4hana.png"


class SAPSignavio(_Brands):
    _icon = "sap-signavio.png"


class SAPSuccessfactors(_Brands):
    _icon = "sap-successfactors.png"


class SAP(_Brands):
    _icon = "sap.png"


# Aliases
