# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Connectivity(_SAP):
    _type = "connectivity"
    _icon_dir = "resources/sap/connectivity"


class Bandwidth(_Connectivity):
    _icon = "bandwidth.png"


class Connectivity(_Connectivity):
    _icon = "connectivity.png"


class Destination(_Connectivity):
    _icon = "destination.png"


class PrivateLinkService(_Connectivity):
    _icon = "private-link-service.png"


# Aliases
