# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Database_Datamanagement(_SAP):
    _type = "database_datamanagement"
    _icon_dir = "resources/sap/database_datamanagement"


class DataQualityServices(_Database_Datamanagement):
    _icon = "data-quality-services.png"


class MasterDataGovernance(_Database_Datamanagement):
    _icon = "master-data-governance.png"


class ObjectStore(_Database_Datamanagement):
    _icon = "object-store.png"


class SAPHANACloud(_Database_Datamanagement):
    _icon = "sap-hana-cloud.png"


class SAPHANAPersistenceServiceNeo(_Database_Datamanagement):
    _icon = "sap-hana-persistence-service-neo.png"


class SAPHANASpatialServices(_Database_Datamanagement):
    _icon = "sap-hana-spatial-services.png"


class SAPPersistenceServiceAse(_Database_Datamanagement):
    _icon = "sap-persistence-service-ase.png"


# Aliases
