# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Database_Datamanagement(_SAP):
    _type = "database_datamanagement"
    _icon_dir = "resources/sap/database_datamanagement"


class DataQualityServices(_Database_Datamanagement):
    _icon = "data-quality-services.png"


class DataQualityServices_Circle(_Database_Datamanagement):
    _icon = "data-quality-services_circle.png"


class Mongodb(_Database_Datamanagement):
    _icon = "mongodb.png"


class Mongodb_Circle(_Database_Datamanagement):
    _icon = "mongodb_circle.png"


class ObjectStore(_Database_Datamanagement):
    _icon = "object-store.png"


class ObjectStore_Circle(_Database_Datamanagement):
    _icon = "object-store_circle.png"


class Postgresql(_Database_Datamanagement):
    _icon = "postgresql.png"


class Redis(_Database_Datamanagement):
    _icon = "redis.png"


class SAPAseService(_Database_Datamanagement):
    _icon = "sap-ase-service.png"


class SAPAseService_Circle(_Database_Datamanagement):
    _icon = "sap-ase-service_circle.png"


class SAPHANAService(_Database_Datamanagement):
    _icon = "sap-hana-service.png"


class SAPHANAService_Circle(_Database_Datamanagement):
    _icon = "sap-hana-service_circle.png"


class SAPHANASpatialServices(_Database_Datamanagement):
    _icon = "sap-hana-spatial-services.png"


class SAPHANASpatialServices_Circle(_Database_Datamanagement):
    _icon = "sap-hana-spatial-services_circle.png"


# Aliases
