# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Development(_SAP):
    _type = "development"
    _icon_dir = "resources/sap/development"


class ApplicationAutoscaler(_Development):
    _icon = "application-autoscaler.png"


class ApplicationAutoscaler_Circle(_Development):
    _icon = "application-autoscaler_circle.png"


class BusinessApplicationStudio(_Development):
    _icon = "business-application-studio.png"


class BusinessApplicationStudio_Circle(_Development):
    _icon = "business-application-studio_circle.png"


class FeatureFlags(_Development):
    _icon = "feature-flags.png"


class FeatureFlags_Circle(_Development):
    _icon = "feature-flags_circle.png"


class RapidApplicationDevelopmentByMendix(_Development):
    _icon = "rapid-application-development-by-mendix.png"


class RapidApplicationDevelopmentByMendix_Circle(_Development):
    _icon = "rapid-application-development-by-mendix_circle.png"


class UsageDataManagement(_Development):
    _icon = "usage-data-management.png"


class UsageDataManagement_Circle(_Development):
    _icon = "usage-data-management_circle.png"


# Aliases
