# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Development(_SAP):
    _type = "development"
    _icon_dir = "resources/sap/development"


class ApplicationAutoscaler(_Development):
    _icon = "application-autoscaler.png"


class ApplicationLogging(_Development):
    _icon = "application-logging.png"


class BusinessApplicationStudio(_Development):
    _icon = "business-application-studio.png"


class FeatureFlagsService(_Development):
    _icon = "feature-flags-service.png"


class RapidApplicationDevelopmentByMendix(_Development):
    _icon = "rapid-application-development-by-mendix.png"


class SaasProvisioningService(_Development):
    _icon = "saas-provisioning-service.png"


class SAPBuildApps(_Development):
    _icon = "sap-build-apps.png"


class SAPBuildCode(_Development):
    _icon = "sap-build-code.png"


class Ui5FlexibilityForKeyUsers(_Development):
    _icon = "ui5-flexibility-for-key-users.png"


class UsageDataManagement(_Development):
    _icon = "usage-data-management.png"


# Aliases
