# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Devops(_SAP):
    _type = "devops"
    _icon_dir = "resources/sap/devops"


class AutomationPilot(_Devops):
    _icon = "automation-pilot.png"


class CloudManagementService(_Devops):
    _icon = "cloud-management-service.png"


class CloudTransportManagement(_Devops):
    _icon = "cloud-transport-management.png"


class ContentAgent(_Devops):
    _icon = "content-agent.png"


class ContinuousIntegrationAndDelivery(_Devops):
    _icon = "continuous-integration-and-delivery.png"


class JobSchedulingService(_Devops):
    _icon = "job-scheduling-service.png"


class MonitoringService(_Devops):
    _icon = "monitoring-service.png"


class SAPCloudAlmMemoryExt(_Devops):
    _icon = "sap-cloud-alm-memory-ext.png"


class SAPLandscapeManagementCloud(_Devops):
    _icon = "sap-landscape-management-cloud.png"


class SAPSolutionLifecycleManagement(_Devops):
    _icon = "sap-solution-lifecycle-management.png"


class ServiceManager(_Devops):
    _icon = "service-manager.png"


# Aliases
