# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Devops(_SAP):
    _type = "devops"
    _icon_dir = "resources/sap/devops"


class AlertNotification(_Devops):
    _icon = "alert-notification.png"


class AlertNotification_Circle(_Devops):
    _icon = "alert-notification_circle.png"


class ApplicationLogging(_Devops):
    _icon = "application-logging.png"


class ApplicationLogging_Circle(_Devops):
    _icon = "application-logging_circle.png"


class AutomationPilot(_Devops):
    _icon = "automation-pilot.png"


class AutomationPilot_Circle(_Devops):
    _icon = "automation-pilot_circle.png"


class Bandwidth(_Devops):
    _icon = "bandwidth.png"


class Bandwidth_Circle(_Devops):
    _icon = "bandwidth_circle.png"


class ContinuousIntegrationAndDelivery(_Devops):
    _icon = "continuous-integration-and-delivery.png"


class ContinuousIntegrationAndDelivery_Circle(_Devops):
    _icon = "continuous-integration-and-delivery_circle.png"


class Dynatrace(_Devops):
    _icon = "dynatrace.png"


class JobScheduler(_Devops):
    _icon = "job-scheduler.png"


class JobScheduler_Circle(_Devops):
    _icon = "job-scheduler_circle.png"


class Monitoring(_Devops):
    _icon = "monitoring.png"


class Monitoring_Circle(_Devops):
    _icon = "monitoring_circle.png"


class TransportManagement(_Devops):
    _icon = "transport-management.png"


class TransportManagement_Circle(_Devops):
    _icon = "transport-management_circle.png"


# Aliases
