# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Erp(_SAP):
    _type = "erp"
    _icon_dir = "resources/sap/erp"


class SAPS4HANACloud(_Erp):
    _icon = "sap-s4hana-cloud.png"


class SAPS4HANA(_Erp):
    _icon = "sap-s4hana.png"


# Aliases
