# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Extensions(_SAP):
    _type = "extensions"
    _icon_dir = "resources/sap/extensions"


class IntelligentIntercompanyReconciliation(_Extensions):
    _icon = "intelligent-intercompany-reconciliation.png"


class IntelligentIntercompanyReconciliation_Circled(_Extensions):
    _icon = "intelligent-intercompany-reconciliation_circled.png"


class IntelligentSituationAutomation(_Extensions):
    _icon = "intelligent-situation-automation.png"


class IntelligentSituationAutomation_Circled(_Extensions):
    _icon = "intelligent-situation-automation_circled.png"


class ResponsibilityManagementService(_Extensions):
    _icon = "responsibility-management-service.png"


class ResponsibilityManagementService_Circled(_Extensions):
    _icon = "responsibility-management-service_circled.png"


# Aliases
