# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Foundational(_SAP):
    _type = "foundational"
    _icon_dir = "resources/sap/foundational"


class ApplicationAutoscaler(_Foundational):
    _icon = "application-autoscaler.png"


class CloudConnector(_Foundational):
    _icon = "cloud-connector.png"


class CloudIntegrationAutomation(_Foundational):
    _icon = "cloud-integration-automation.png"


class CloudLogging(_Foundational):
    _icon = "cloud-logging.png"


class LandscapePortalForSAPS4HANACloudAbapEnvironment(_Foundational):
    _icon = "landscape-portal-for-sap-s4hana-cloud-abap-environment.png"


class Oauth20OnSAPBTP(_Foundational):
    _icon = "oauth-20-on-sap-btp.png"


class ObjectStoreOnSAPBTP(_Foundational):
    _icon = "object-store-on-sap-btp.png"


class SAPAlertNotificationServiceForSAPBTP(_Foundational):
    _icon = "sap-alert-notification-service-for-sap-btp.png"


class SAPApplicationLoggingServiceForSAPBTP(_Foundational):
    _icon = "sap-application-logging-service-for-sap-btp.png"


class SAPAuditLogService(_Foundational):
    _icon = "sap-audit-log-service.png"


class SAPAuthorizationManagement(_Foundational):
    _icon = "sap-authorization-management.png"


class SAPAutomationPilot(_Foundational):
    _icon = "sap-automation-pilot.png"


class SAPBTPCloudFoundryRuntime(_Foundational):
    _icon = "sap-btp-cloud-foundry-runtime.png"


class SAPBTPKymaRuntime(_Foundational):
    _icon = "sap-btp-kyma-runtime.png"


class SAPCloudIdentitySAPAuthorizationAndTrustManagementService(_Foundational):
    _icon = "sap-cloud-identity-sap-authorization-and-trust-management-service.png"


class SAPCloudIdentitySAPCredentialStore(_Foundational):
    _icon = "sap-cloud-identity-sap-credential-store.png"


class SAPCloudIdentitySAPCustomDomainService(_Foundational):
    _icon = "sap-cloud-identity-sap-custom-domain-service.png"


class SAPCloudIdentitySAPKeystoreService(_Foundational):
    _icon = "sap-cloud-identity-sap-keystore-service.png"


class SAPCloudIdentitySAPMalwareScanningService(_Foundational):
    _icon = "sap-cloud-identity-sap-malware-scanning-service.png"


class SAPCloudIdentityService(_Foundational):
    _icon = "sap-cloud-identity-service.png"


class SAPCloudManagementServiceForSAPBTP(_Foundational):
    _icon = "sap-cloud-management-service-for-sap-btp.png"


class SAPCloudTransportManagement(_Foundational):
    _icon = "sap-cloud-transport-management.png"


class SAPConnectivityService(_Foundational):
    _icon = "sap-connectivity-service.png"


class SAPContentAgentService(_Foundational):
    _icon = "sap-content-agent-service.png"


class SAPContinuousIntegrationAndDelivery(_Foundational):
    _icon = "sap-continuous-integration-and-delivery.png"


class SAPDataPrivacyIntegration(_Foundational):
    _icon = "sap-data-privacy-integration.png"


class SAPDataRetentionManager(_Foundational):
    _icon = "sap-data-retention-manager.png"


class SAPDestinationService(_Foundational):
    _icon = "sap-destination-service.png"


class SAPDocumentManagementService(_Foundational):
    _icon = "sap-document-management-service.png"


class SAPEventBrokerForSAPCloudApplications(_Foundational):
    _icon = "sap-event-broker-for-sap-cloud-applications.png"


class SAPIdentityAuthentication(_Foundational):
    _icon = "sap-identity-authentication.png"


class SAPIdentityDirectory(_Foundational):
    _icon = "sap-identity-directory.png"


class SAPIdentityProvisoning(_Foundational):
    _icon = "sap-identity-provisoning.png"


class SAPJobSchedulingService(_Foundational):
    _icon = "sap-job-scheduling-service.png"


class SAPMasterDataIntegration(_Foundational):
    _icon = "sap-master-data-integration.png"


class SAPMonitoringServiceForSAPBTP(_Foundational):
    _icon = "sap-monitoring-service-for-sap-btp.png"


class SAPPersonalDataManager(_Foundational):
    _icon = "sap-personal-data-manager.png"


class SAPPkiCertificateService(_Foundational):
    _icon = "sap-pki-certificate-service.png"


class SAPPrivateLinkService(_Foundational):
    _icon = "sap-private-link-service.png"


class SAPSecureLoginServiceForSAPGui(_Foundational):
    _icon = "sap-secure-login-service-for-sap-gui.png"


class SAPSoftwareAsAServiceProvisioningService(_Foundational):
    _icon = "sap-software-as-a-service-provisioning-service.png"


class SAPSolutionLifecycleManagementServiceForSAPBTP(_Foundational):
    _icon = "sap-solution-lifecycle-management-service-for-sap-btp.png"


class ServiceManager(_Foundational):
    _icon = "service-manager.png"


# Aliases
