# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Generic(_SAP):
    _type = "generic"
    _icon_dir = "resources/sap/generic"


class AdapterHighlight(_Generic):
    _icon = "adapter-highlight.png"


class AdapterNonSAP(_Generic):
    _icon = "adapter-non-sap.png"


class AdapterSAP(_Generic):
    _icon = "adapter-sap.png"


class AdminHighlight(_Generic):
    _icon = "admin-highlight.png"


class AdminNonSAP(_Generic):
    _icon = "admin-non-sap.png"


class AdminSAP(_Generic):
    _icon = "admin-sap.png"


class AIHighlight(_Generic):
    _icon = "ai-highlight.png"


class AINonSAP(_Generic):
    _icon = "ai-non-sap.png"


class AISAP(_Generic):
    _icon = "ai-sap.png"


class AlertHighlight(_Generic):
    _icon = "alert-highlight.png"


class AlertNonSAP(_Generic):
    _icon = "alert-non-sap.png"


class AlertSAP(_Generic):
    _icon = "alert-sap.png"


class APIHighlight(_Generic):
    _icon = "api-highlight.png"


class APINonSAP(_Generic):
    _icon = "api-non-sap.png"


class APISAP(_Generic):
    _icon = "api-sap.png"


class AppHighlight(_Generic):
    _icon = "app-highlight.png"


class AppNonSAP(_Generic):
    _icon = "app-non-sap.png"


class AppSAP(_Generic):
    _icon = "app-sap.png"


class BuildingHighlight(_Generic):
    _icon = "building-highlight.png"


class BuildingNonSAP(_Generic):
    _icon = "building-non-sap.png"


class BuildingSAP(_Generic):
    _icon = "building-sap.png"


class CloudConnectorHighlight(_Generic):
    _icon = "cloud-connector-highlight.png"


class CloudConnectorNonSAP(_Generic):
    _icon = "cloud-connector-non-sap.png"


class CloudConnectorSAP(_Generic):
    _icon = "cloud-connector-sap.png"


class CloudHighlight(_Generic):
    _icon = "cloud-highlight.png"


class CloudNonSAP(_Generic):
    _icon = "cloud-non-sap.png"


class CloudSAP(_Generic):
    _icon = "cloud-sap.png"


class CollisionHighlight(_Generic):
    _icon = "collision-highlight.png"


class CollisionNonSAP(_Generic):
    _icon = "collision-non-sap.png"


class CollisionSAP(_Generic):
    _icon = "collision-sap.png"


class DaHighlight(_Generic):
    _icon = "da-highlight.png"


class DaNonSAP(_Generic):
    _icon = "da-non-sap.png"


class DaSAP(_Generic):
    _icon = "da-sap.png"


class DeployHighlight(_Generic):
    _icon = "deploy-highlight.png"


class DeployNonSAP(_Generic):
    _icon = "deploy-non-sap.png"


class DeploySAP(_Generic):
    _icon = "deploy-sap.png"


class DesktopHighlight(_Generic):
    _icon = "desktop-highlight.png"


class DesktopNonSAP(_Generic):
    _icon = "desktop-non-sap.png"


class DesktopSAP(_Generic):
    _icon = "desktop-sap.png"


class DetailViewHighlight(_Generic):
    _icon = "detail-view-highlight.png"


class DetailViewNonSAP(_Generic):
    _icon = "detail-view-non-sap.png"


class DetailViewSAP(_Generic):
    _icon = "detail-view-sap.png"


class DevicesHighlight(_Generic):
    _icon = "devices-highlight.png"


class DevicesNonSAP(_Generic):
    _icon = "devices-non-sap.png"


class DevicesSAP(_Generic):
    _icon = "devices-sap.png"


class DocumentHighlight(_Generic):
    _icon = "document-highlight.png"


class DocumentNonSAP(_Generic):
    _icon = "document-non-sap.png"


class DocumentSAP(_Generic):
    _icon = "document-sap.png"


class DocumentsHighlight(_Generic):
    _icon = "documents-highlight.png"


class DocumentsNonSAP(_Generic):
    _icon = "documents-non-sap.png"


class DocumentsSAP(_Generic):
    _icon = "documents-sap.png"


class EventHighlight(_Generic):
    _icon = "event-highlight.png"


class EventNonSAP(_Generic):
    _icon = "event-non-sap.png"


class EventSAP(_Generic):
    _icon = "event-sap.png"


class FactoryHighlight(_Generic):
    _icon = "factory-highlight.png"


class FactoryNonSAP(_Generic):
    _icon = "factory-non-sap.png"


class FactorySAP(_Generic):
    _icon = "factory-sap.png"


class FeatureHighlight(_Generic):
    _icon = "feature-highlight.png"


class FeatureNonSAP(_Generic):
    _icon = "feature-non-sap.png"


class FeatureSAP(_Generic):
    _icon = "feature-sap.png"


class IndentHighlight(_Generic):
    _icon = "indent-highlight.png"


class IndentNonSAP(_Generic):
    _icon = "indent-non-sap.png"


class IndentSAP(_Generic):
    _icon = "indent-sap.png"


class InfoHighlight(_Generic):
    _icon = "info-highlight.png"


class InfoNonSAP(_Generic):
    _icon = "info-non-sap.png"


class InfoSAP(_Generic):
    _icon = "info-sap.png"


class InspectHighlight(_Generic):
    _icon = "inspect-highlight.png"


class InspectNonSAP(_Generic):
    _icon = "inspect-non-sap.png"


class InspectSAP(_Generic):
    _icon = "inspect-sap.png"


class KeyHighlight(_Generic):
    _icon = "key-highlight.png"


class KeyNonSAP(_Generic):
    _icon = "key-non-sap.png"


class KeySAP(_Generic):
    _icon = "key-sap.png"


class LinkHighlight(_Generic):
    _icon = "link-highlight.png"


class LinkNonSAP(_Generic):
    _icon = "link-non-sap.png"


class LinkSAP(_Generic):
    _icon = "link-sap.png"


class LockedHighlight(_Generic):
    _icon = "locked-highlight.png"


class LockedNonSAP(_Generic):
    _icon = "locked-non-sap.png"


class LockedSAP(_Generic):
    _icon = "locked-sap.png"


class MachineHighlight(_Generic):
    _icon = "machine-highlight.png"


class MachineNonSAP(_Generic):
    _icon = "machine-non-sap.png"


class MachineSAP(_Generic):
    _icon = "machine-sap.png"


class MessageHighlight(_Generic):
    _icon = "message-highlight.png"


class MessageNonSAP(_Generic):
    _icon = "message-non-sap.png"


class MessageSAP(_Generic):
    _icon = "message-sap.png"


class MobileHighlight(_Generic):
    _icon = "mobile-highlight.png"


class MobileNonSAP(_Generic):
    _icon = "mobile-non-sap.png"


class MobileSAP(_Generic):
    _icon = "mobile-sap.png"


class OnPremiseHighlight(_Generic):
    _icon = "on-premise-highlight.png"


class OnPremiseNonSAP(_Generic):
    _icon = "on-premise-non-sap.png"


class OnPremiseSAP(_Generic):
    _icon = "on-premise-sap.png"


class PaletteHighlight(_Generic):
    _icon = "palette-highlight.png"


class PaletteNonSAP(_Generic):
    _icon = "palette-non-sap.png"


class PaletteSAP(_Generic):
    _icon = "palette-sap.png"


class PaperPlaneHighlight(_Generic):
    _icon = "paper-plane-highlight.png"


class PaperPlaneNonSAP(_Generic):
    _icon = "paper-plane-non-sap.png"


class PaperPlaneSAP(_Generic):
    _icon = "paper-plane-sap.png"


class PermissionHighlight(_Generic):
    _icon = "permission-highlight.png"


class PermissionNonSAP(_Generic):
    _icon = "permission-non-sap.png"


class PermissionSAP(_Generic):
    _icon = "permission-sap.png"


class RestartHighlight(_Generic):
    _icon = "restart-highlight.png"


class RestartNonSAP(_Generic):
    _icon = "restart-non-sap.png"


class RestartSAP(_Generic):
    _icon = "restart-sap.png"


class SettingsHighlight(_Generic):
    _icon = "settings-highlight.png"


class SettingsNonSAP(_Generic):
    _icon = "settings-non-sap.png"


class SettingsSAP(_Generic):
    _icon = "settings-sap.png"


class SuccessHighlight(_Generic):
    _icon = "success-highlight.png"


class SuccessNonSAP(_Generic):
    _icon = "success-non-sap.png"


class SuccessSAP(_Generic):
    _icon = "success-sap.png"


class SynchronizeHighlight(_Generic):
    _icon = "synchronize-highlight.png"


class SynchronizeNonSAP(_Generic):
    _icon = "synchronize-non-sap.png"


class SynchronizeSAP(_Generic):
    _icon = "synchronize-sap.png"


class ThirdPartyHighlight(_Generic):
    _icon = "third-party-highlight.png"


class ThirdPartyNonSAP(_Generic):
    _icon = "third-party-non-sap.png"


class ThirdPartySAP(_Generic):
    _icon = "third-party-sap.png"


class TreeHighlight(_Generic):
    _icon = "tree-highlight.png"


class TreeNonSAP(_Generic):
    _icon = "tree-non-sap.png"


class TreeSAP(_Generic):
    _icon = "tree-sap.png"


class UserHighlight(_Generic):
    _icon = "user-highlight.png"


class UserNonSAP(_Generic):
    _icon = "user-non-sap.png"


class UserSAP(_Generic):
    _icon = "user-sap.png"


class WebHighlight(_Generic):
    _icon = "web-highlight.png"


class WebNonSAP(_Generic):
    _icon = "web-non-sap.png"


class WebSAP(_Generic):
    _icon = "web-sap.png"


# Aliases
