# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Generic(_SAP):
    _type = "generic"
    _icon_dir = "resources/sap/generic"


class Accelerated(_Generic):
    _icon = "accelerated.png"


class Accept(_Generic):
    _icon = "accept.png"


class ActionSettings(_Generic):
    _icon = "action-settings.png"


class Add(_Generic):
    _icon = "add.png"


class Alert(_Generic):
    _icon = "alert.png"


class Arobase(_Generic):
    _icon = "arobase.png"


class ArrowBottom(_Generic):
    _icon = "arrow-bottom.png"


class ArrowLeft(_Generic):
    _icon = "arrow-left.png"


class ArrowRight(_Generic):
    _icon = "arrow-right.png"


class ArrowTop(_Generic):
    _icon = "arrow-top.png"


class Background(_Generic):
    _icon = "background.png"


class BarChart(_Generic):
    _icon = "bar-chart.png"


class Block(_Generic):
    _icon = "block.png"


class BrokenLink(_Generic):
    _icon = "broken-link.png"


class Calendar(_Generic):
    _icon = "calendar.png"


class Camera(_Generic):
    _icon = "camera.png"


class Cart(_Generic):
    _icon = "cart.png"


class ChainLink(_Generic):
    _icon = "chain-link.png"


class Chalkboard(_Generic):
    _icon = "chalkboard.png"


class ChartTreeMap(_Generic):
    _icon = "chart-tree-map.png"


class Cloud(_Generic):
    _icon = "cloud.png"


class Compare(_Generic):
    _icon = "compare.png"


class Competitor(_Generic):
    _icon = "competitor.png"


class Complete(_Generic):
    _icon = "complete.png"


class CourseProgram(_Generic):
    _icon = "course-program.png"


class CreateEntryTime(_Generic):
    _icon = "create-entry-time.png"


class Create(_Generic):
    _icon = "create.png"


class Curriculum(_Generic):
    _icon = "curriculum.png"


class CustomerOrderEntry(_Generic):
    _icon = "customer-order-entry.png"


class DataStore(_Generic):
    _icon = "data-store.png"


class Database(_Generic):
    _icon = "database.png"


class Decline(_Generic):
    _icon = "decline.png"


class Delete(_Generic):
    _icon = "delete.png"


class DocumentText(_Generic):
    _icon = "document-text.png"


class Document(_Generic):
    _icon = "document.png"


class DownloadFromCloud(_Generic):
    _icon = "download-from-cloud.png"


class Download(_Generic):
    _icon = "download.png"


class ECare(_Generic):
    _icon = "e-care.png"


class ELearning(_Generic):
    _icon = "e-learning.png"


class Edit(_Generic):
    _icon = "edit.png"


class EmailRead(_Generic):
    _icon = "email-read.png"


class EnergySavingLightbulb(_Generic):
    _icon = "energy-saving-lightbulb.png"


class ExpenseReport(_Generic):
    _icon = "expense-report.png"


class Factory(_Generic):
    _icon = "factory.png"


class FamilyCare(_Generic):
    _icon = "family-care.png"


class Favorite(_Generic):
    _icon = "favorite.png"


class Feed(_Generic):
    _icon = "feed.png"


class Filter(_Generic):
    _icon = "filter.png"


class Folder(_Generic):
    _icon = "folder.png"


class Fresh(_Generic):
    _icon = "fresh.png"


class GanttBars(_Generic):
    _icon = "gantt-bars.png"


class Group(_Generic):
    _icon = "group.png"


class History(_Generic):
    _icon = "history.png"


class Home(_Generic):
    _icon = "home.png"


class InternetBrowser(_Generic):
    _icon = "internet-browser.png"


class Ipad(_Generic):
    _icon = "ipad.png"


class Iphone(_Generic):
    _icon = "iphone.png"


class ItHost(_Generic):
    _icon = "it-host.png"


class ItInstance(_Generic):
    _icon = "it-instance.png"


class ItSystem(_Generic):
    _icon = "it-system.png"


class KeyPair(_Generic):
    _icon = "key-pair.png"


class KeyUserSettings(_Generic):
    _icon = "key-user-settings.png"


class Laptop(_Generic):
    _icon = "laptop.png"


class LearningAssistant(_Generic):
    _icon = "learning-assistant.png"


class Legend(_Generic):
    _icon = "legend.png"


class Less(_Generic):
    _icon = "less.png"


class Lightbulb(_Generic):
    _icon = "lightbulb.png"


class Locked(_Generic):
    _icon = "locked.png"


class Log(_Generic):
    _icon = "log.png"


class Mail(_Generic):
    _icon = "mail.png"


class Map(_Generic):
    _icon = "map.png"


class Microphone(_Generic):
    _icon = "microphone.png"


class MySalesOrder(_Generic):
    _icon = "my-sales-order.png"


class OpenFolder(_Generic):
    _icon = "open-folder.png"


class OrgChart(_Generic):
    _icon = "org-chart.png"


class PdfAttachment(_Generic):
    _icon = "pdf-attachment.png"


class PersonPlaceholder(_Generic):
    _icon = "person-placeholder.png"


class Post(_Generic):
    _icon = "post.png"


class PrivateKey(_Generic):
    _icon = "private-key.png"


class Process(_Generic):
    _icon = "process.png"


class Product(_Generic):
    _icon = "product.png"


class PublicKey(_Generic):
    _icon = "public-key.png"


class PushpinOff(_Generic):
    _icon = "pushpin-off.png"


class Request(_Generic):
    _icon = "request.png"


class SAPLogoShape(_Generic):
    _icon = "sap-logo-shape.png"


class Save(_Generic):
    _icon = "save.png"


class Search(_Generic):
    _icon = "search.png"


class Settings(_Generic):
    _icon = "settings.png"


class Shelf(_Generic):
    _icon = "shelf.png"


class Shield(_Generic):
    _icon = "shield.png"


class Sort(_Generic):
    _icon = "sort.png"


class SoundLoud(_Generic):
    _icon = "sound-loud.png"


class Sound(_Generic):
    _icon = "sound.png"


class StatusCritical(_Generic):
    _icon = "status-critical.png"


class StatusInactive(_Generic):
    _icon = "status-inactive.png"


class StatusNegative(_Generic):
    _icon = "status-negative.png"


class StatusPositive(_Generic):
    _icon = "status-positive.png"


class SwitchClasses(_Generic):
    _icon = "switch-classes.png"


class Synchronize(_Generic):
    _icon = "synchronize.png"


class SysHelp(_Generic):
    _icon = "sys-help.png"


class SysMonitor(_Generic):
    _icon = "sys-monitor.png"


class SystemHANA(_Generic):
    _icon = "system-hana.png"


class Timesheet(_Generic):
    _icon = "timesheet.png"


class Tree(_Generic):
    _icon = "tree.png"


class Unfavorite(_Generic):
    _icon = "unfavorite.png"


class Unlocked(_Generic):
    _icon = "unlocked.png"


class UploadToCloud(_Generic):
    _icon = "upload-to-cloud.png"


class Upload(_Generic):
    _icon = "upload.png"


class Video(_Generic):
    _icon = "video.png"


class Wifi(_Generic):
    _icon = "wifi.png"


class World(_Generic):
    _icon = "world.png"


class Wrench(_Generic):
    _icon = "wrench.png"


# Aliases
