# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Integration_Suite(_SAP):
    _type = "integration_suite"
    _icon_dir = "resources/sap/integration_suite"


class AdvancedEventMesh(_Integration_Suite):
    _icon = "advanced-event-mesh.png"


class APIManagement(_Integration_Suite):
    _icon = "api-management.png"


class CloudIntegration(_Integration_Suite):
    _icon = "cloud-integration.png"


class DataSpaceIntegration(_Integration_Suite):
    _icon = "data-space-integration.png"


class EdgeIntegrationCell(_Integration_Suite):
    _icon = "edge-integration-cell.png"


class EventMesh(_Integration_Suite):
    _icon = "event-mesh.png"


class Graph(_Integration_Suite):
    _icon = "graph.png"


class IntegrationAdvisor(_Integration_Suite):
    _icon = "integration-advisor.png"


class IntegrationAssessment(_Integration_Suite):
    _icon = "integration-assessment.png"


class MigrationAssessment(_Integration_Suite):
    _icon = "migration-assessment.png"


class OpenConnectors(_Integration_Suite):
    _icon = "open-connectors.png"


class SAPAPIHubEnterprise(_Integration_Suite):
    _icon = "sap-api-hub-enterprise.png"


class SAPBusinessAccelerator_Hub(_Integration_Suite):
    _icon = "sap-business-accelerator-_hub.png"


class SAPIntegrationSuite(_Integration_Suite):
    _icon = "sap-integration-suite.png"


class TradingPartnerManagement(_Integration_Suite):
    _icon = "trading-partner-management.png"


# Aliases
