# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Integration(_SAP):
    _type = "integration"
    _icon_dir = "resources/sap/integration"


class APIManagement(_Integration):
    _icon = "api-management.png"


class APIManagement_Circle(_Integration):
    _icon = "api-management_circle.png"


class CloudConnector(_Integration):
    _icon = "cloud-connector.png"


class CloudConnector_Circle(_Integration):
    _icon = "cloud-connector_circle.png"


class Connectivity(_Integration):
    _icon = "connectivity.png"


class Connectivity_Circle(_Integration):
    _icon = "connectivity_circle.png"


class Destination(_Integration):
    _icon = "destination.png"


class Destination_Circle(_Integration):
    _icon = "destination_circle.png"


class EventMesh(_Integration):
    _icon = "event-mesh.png"


class EventMesh_Circle(_Integration):
    _icon = "event-mesh_circle.png"


class IntegrationAdvisor(_Integration):
    _icon = "integration-advisor.png"


class IntegrationAdvisor_Circle(_Integration):
    _icon = "integration-advisor_circle.png"


class IntegrationSuite(_Integration):
    _icon = "integration-suite.png"


class IntegrationSuite_Circle(_Integration):
    _icon = "integration-suite_circle.png"


class OpenConnectors(_Integration):
    _icon = "open-connectors.png"


class OpenConnectors_Circle(_Integration):
    _icon = "open-connectors_circle.png"


class ProcessIntegration(_Integration):
    _icon = "process-integration.png"


class ProcessIntegration_Circle(_Integration):
    _icon = "process-integration_circle.png"


class SAPDataIntelligence(_Integration):
    _icon = "sap-data-intelligence.png"


class SAPDataIntelligence_Circle(_Integration):
    _icon = "sap-data-intelligence_circle.png"


class SAPDataProvisioningAgent(_Integration):
    _icon = "sap-data-provisioning-agent.png"


class SAPDataProvisioningAgent_Circle(_Integration):
    _icon = "sap-data-provisioning-agent_circle.png"


# Aliases
