# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Integration(_SAP):
    _type = "integration"
    _icon_dir = "resources/sap/integration"


class AdvancedEventMesh(_Integration):
    _icon = "advanced-event-mesh.png"


class CloudIntegrationAutomation(_Integration):
    _icon = "cloud-integration-automation.png"


class CloudIntegrationForDataServices(_Integration):
    _icon = "cloud-integration-for-data-services.png"


class EventMesh(_Integration):
    _icon = "event-mesh.png"


class IntegrationSuite(_Integration):
    _icon = "integration-suite.png"


class MasterDataIntegration(_Integration):
    _icon = "master-data-integration.png"


class SAPDocumentAndReportingCompliance(_Integration):
    _icon = "sap-document-and-reporting-compliance.png"


class SAPEventBroker(_Integration):
    _icon = "sap-event-broker.png"


class SAPGraph(_Integration):
    _icon = "sap-graph.png"


# Aliases
