# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Lob_Industries(_SAP):
    _type = "lob_industries"
    _icon_dir = "resources/sap/lob_industries"


class SAPGreenToken(_Lob_Industries):
    _icon = "sap-green-token.png"


class SAPMarketRatesManagement(_Lob_Industries):
    _icon = "sap-market-rates-management.png"


class SAPVariantConfigurationAndPricing(_Lob_Industries):
    _icon = "sap-variant-configuration-and-pricing.png"


# Aliases
