# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Lob_Industries(_SAP):
    _type = "lob_industries"
    _icon_dir = "resources/sap/lob_industries"


class MarketRatesManagement(_Lob_Industries):
    _icon = "market-rates-management.png"


class MarketRatesManagement_Circle(_Lob_Industries):
    _icon = "market-rates-management_circle.png"


class OmnichannelPromotionPricing(_Lob_Industries):
    _icon = "omnichannel-promotion-pricing.png"


class OmnichannelPromotionPricing_Circle(_Lob_Industries):
    _icon = "omnichannel-promotion-pricing_circle.png"


class VariantConfigurationService(_Lob_Industries):
    _icon = "variant-configuration-service.png"


class VariantConfigurationService_Circle(_Lob_Industries):
    _icon = "variant-configuration-service_circle.png"


# Aliases
