# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Other(_SAP):
    _type = "other"
    _icon_dir = "resources/sap/other"


class CloudManagementService(_Other):
    _icon = "cloud-management-service.png"


class CloudManagementService_Circle(_Other):
    _icon = "cloud-management-service_circle.png"


class Placeholder(_Other):
    _icon = "placeholder.png"


class Placeholder_Circle(_Other):
    _icon = "placeholder_circle.png"


class SaasProvisioningService(_Other):
    _icon = "saas-provisioning-service.png"


class SaasProvisioningService_Circle(_Other):
    _icon = "saas-provisioning-service_circle.png"


class ServiceManager(_Other):
    _icon = "service-manager.png"


class ServiceManager_Circle(_Other):
    _icon = "service-manager_circle.png"


# Aliases
