# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Other(_SAP):
    _type = "other"
    _icon_dir = "resources/sap/other"


class DateAndTime(_Other):
    _icon = "date-and-time.png"


class IbanService(_Other):
    _icon = "iban-service.png"


class PlaceholderServiceName(_Other):
    _icon = "placeholder-service-name.png"


class PrintService(_Other):
    _icon = "print-service.png"


class SAPIot(_Other):
    _icon = "sap-iot.png"


class WorkCalendar(_Other):
    _icon = "work-calendar.png"


# Aliases
