# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Processautomation(_SAP):
    _type = "processautomation"
    _icon_dir = "resources/sap/processautomation"


class BusinessRules(_Processautomation):
    _icon = "business-rules.png"


class ProcessAutomation(_Processautomation):
    _icon = "process-automation.png"


class SAPBuildProcessAutomation(_Processautomation):
    _icon = "sap-build-process-automation.png"


class SAPIntelligentRpa(_Processautomation):
    _icon = "sap-intelligent-rpa.png"


class WorkflowManagement(_Processautomation):
    _icon = "workflow-management.png"


class WorkflowService(_Processautomation):
    _icon = "workflow-service.png"


# Aliases
