# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Processautomation(_SAP):
    _type = "processautomation"
    _icon_dir = "resources/sap/processautomation"


class SAPIntelligentRoboticProcessAutomation(_Processautomation):
    _icon = "sap-intelligent-robotic-process-automation.png"


class SAPIntelligentRoboticProcessAutomation_Circle(_Processautomation):
    _icon = "sap-intelligent-robotic-process-automation_circle.png"


class Workflow(_Processautomation):
    _icon = "workflow.png"


class Workflow_Circle(_Processautomation):
    _icon = "workflow_circle.png"


# Aliases
