# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Runtimes(_SAP):
    _type = "runtimes"
    _icon_dir = "resources/sap/runtimes"


class AbapEnvironment(_Runtimes):
    _icon = "abap-environment.png"


class AbapSolution(_Runtimes):
    _icon = "abap-solution.png"


class CloudFoundryRuntime(_Runtimes):
    _icon = "cloud-foundry-runtime.png"


class Html5AppRepository(_Runtimes):
    _icon = "html5-app-repository.png"


class KymaRuntime(_Runtimes):
    _icon = "kyma-runtime.png"


# Aliases
