# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Saas(_SAP):
    _type = "saas"
    _icon_dir = "resources/sap/saas"


class SAPAribaBlack(_Saas):
    _icon = "sap-ariba-black.png"


class SAPAriba(_Saas):
    _icon = "sap-ariba.png"


class SAPConcurBlack(_Saas):
    _icon = "sap-concur-black.png"


class SAPConcur(_Saas):
    _icon = "sap-concur.png"


class SAPFieldglassBlack(_Saas):
    _icon = "sap-fieldglass-black.png"


class SAPFieldglass(_Saas):
    _icon = "sap-fieldglass.png"


class SAPHealthBlack(_Saas):
    _icon = "sap-health-black.png"


class SAPHealth(_Saas):
    _icon = "sap-health.png"


class SAPSuccessfactorsBlack(_Saas):
    _icon = "sap-successfactors-black.png"


class SAPSuccessfactors(_Saas):
    _icon = "sap-successfactors.png"


# Aliases
