# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Security(_SAP):
    _type = "security"
    _icon_dir = "resources/sap/security"


class AuthorizationAndTrustManagement(_Security):
    _icon = "authorization-and-trust-management.png"


class AuthorizationAndTrustManagement_Circle(_Security):
    _icon = "authorization-and-trust-management_circle.png"


class CredentialStore(_Security):
    _icon = "credential-store.png"


class CredentialStore_Circle(_Security):
    _icon = "credential-store_circle.png"


class CustomDomain(_Security):
    _icon = "custom-domain.png"


class CustomDomain_Circle(_Security):
    _icon = "custom-domain_circle.png"


class DataPrivacyIntegration(_Security):
    _icon = "data-privacy-integration.png"


class DataPrivacyIntegration_Circle(_Security):
    _icon = "data-privacy-integration_circle.png"


class DataRetentionManager(_Security):
    _icon = "data-retention-manager.png"


class DataRetentionManager_Circle(_Security):
    _icon = "data-retention-manager_circle.png"


class IdentityAuthentication(_Security):
    _icon = "identity-authentication.png"


class IdentityAuthentication_Circle(_Security):
    _icon = "identity-authentication_circle.png"


class IdentityProvisioning(_Security):
    _icon = "identity-provisioning.png"


class IdentityProvisioning_Circle(_Security):
    _icon = "identity-provisioning_circle.png"


class KeystoreService(_Security):
    _icon = "keystore-service.png"


class KeystoreService_Circle(_Security):
    _icon = "keystore-service_circle.png"


class Oauth2(_Security):
    _icon = "oauth2.png"


class Oauth2_Circle(_Security):
    _icon = "oauth2_circle.png"


class PersonalDataManager(_Security):
    _icon = "personal-data-manager.png"


class PersonalDataManager_Circle(_Security):
    _icon = "personal-data-manager_circle.png"


# Aliases
