# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Security(_SAP):
    _type = "security"
    _icon_dir = "resources/sap/security"


class AuditLogService(_Security):
    _icon = "audit-log-service.png"


class AuthorizationAndTrustManagementService(_Security):
    _icon = "authorization-and-trust-management-service.png"


class CredentialStore(_Security):
    _icon = "credential-store.png"


class CustomDomain(_Security):
    _icon = "custom-domain.png"


class DataPrivacyIntegration(_Security):
    _icon = "data-privacy-integration.png"


class IdentityProvisioning(_Security):
    _icon = "identity-provisioning.png"


class KeystoreService(_Security):
    _icon = "keystore-service.png"


class MalwareScanning(_Security):
    _icon = "malware-scanning.png"


class Oauth2Service(_Security):
    _icon = "oauth2-service.png"


class SAPDataRetentionManager(_Security):
    _icon = "sap-data-retention-manager.png"


class SAPPersonalDataManager(_Security):
    _icon = "sap-personal-data-manager.png"


# Aliases
