# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Ux(_SAP):
    _type = "ux"
    _icon_dir = "resources/sap/ux"


class CloudPortalService(_Ux):
    _icon = "cloud-portal-service.png"


class DocumentManagementServiceApplication(_Ux):
    _icon = "document-management-service-application.png"


class LaunchpadService(_Ux):
    _icon = "launchpad-service.png"


class SAPBuildWorkZoneAdvancedEdition(_Ux):
    _icon = "sap-build-work-zone-advanced-edition.png"


class SAPBuildWorkZoneStandardEdition(_Ux):
    _icon = "sap-build-work-zone-standard-edition.png"


class SAPTaskCenter(_Ux):
    _icon = "sap-task-center.png"


# Aliases
