# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Ux(_SAP):
    _type = "ux"
    _icon_dir = "resources/sap/ux"


class DocumentManagementService(_Ux):
    _icon = "document-management-service.png"


class DocumentManagementService_Circle(_Ux):
    _icon = "document-management-service_circle.png"


class FormsByAdobe(_Ux):
    _icon = "forms-by-adobe.png"


class Launchpad(_Ux):
    _icon = "launchpad.png"


class Launchpad_Circle(_Ux):
    _icon = "launchpad_circle.png"


class Portal(_Ux):
    _icon = "portal.png"


class Portal_Circle(_Ux):
    _icon = "portal_circle.png"


class SAPWorkZone(_Ux):
    _icon = "sap-work-zone.png"


class SAPWorkZone_Circle(_Ux):
    _icon = "sap-work-zone_circle.png"


# Aliases
