# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _TencentCloud

class _Compute(_TencentCloud):
    _type = "compute"
    _icon_dir = "resources/tencentcloud/compute"


class AutoScaling(_Compute):
    _icon = "auto-scaling.png"
class CloudVirtualMachine(_Compute):
    _icon = "cloud-virtual-machine.png"
class Lighthouse(_Compute):
    _icon = "lighthouse.png"
class ServerlessCloudFunction(_Compute):
    _icon = "serverless-cloud-function.png"
class TencentIC(_Compute):
    _icon = "tencent-i-c.png"
class TencentKubernetesEngine(_Compute):
    _icon = "tencent-kubernetes-engine.png"
class TencentServiceFramework(_Compute):
    _icon = "tencent-service-framework.png"

# Aliases

AS = AutoScaling
CVM = CloudVirtualMachine
TKE = TencentKubernetesEngine
SCF = ServerlessCloudFunction
TIC = TencentIC
TSF = TencentServiceFramework
Lighthouse = Lighthouse