# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _TencentCloud


class _Container(_TencentCloud):
    _type = "container"
    _icon_dir = "resources/tencentcloud/container"


class TencentKubernetesEngine(_Container):
    _icon = "tencent-kubernetes-engine.png"


# Aliases

TKE = TencentKubernetesEngine
