# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _TencentCloud

class _Database(_TencentCloud):
    _type = "database"
    _icon_dir = "resources/tencentcloud/database"


class TencentMongodb(_Database):
    _icon = "tencent-mongodb.png"
class TencentMysql(_Database):
    _icon = "tencent-mysql.png"
class TencentPostgresql(_Database):
    _icon = "tencent-postgresql.png"
class TencentRedis(_Database):
    _icon = "tencent-redis.png"
class TencentSqlserver(_Database):
    _icon = "tencent-sqlserver.png"
class TencentTDsql(_Database):
    _icon = "tencent-t-dsql.png"

# Aliases

MySQL = TencentMysql
SQLServer = TencentSqlserver
PostgreSQL = TencentPostgresql
Redis = TencentRedis
MongoDB = TencentMongodb
TDSQL = TencentTDsql