# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _TencentCloud


class _Middleware(_TencentCloud):
    _type = "middleware"
    _icon_dir = "resources/tencentcloud/middleware"


class CloudMessageQueue(_Middleware):
    _icon = "cloud-message-queue.png"


# Aliases

CMQ = CloudMessageQueue
