# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _TencentCloud


class _Network(_TencentCloud):
    _type = "network"
    _icon_dir = "resources/tencentcloud/network"


class AnycastInternetAcceleration(_Network):
    _icon = "anycast-internet-acceleration.png"


class BandwidthPackage(_Network):
    _icon = "bandwidth-package.png"


class CloudConnectNetwork(_Network):
    _icon = "cloud-connect-network.png"


class CloudLoadBalancer(_Network):
    _icon = "cloud-load-balancer.png"


class DirectConnect(_Network):
    _icon = "direct-connect.png"


class ElasticNetworkInterface(_Network):
    _icon = "elastic-network-interface.png"


class FlowLogs(_Network):
    _icon = "flow-logs.png"


class NatGateway(_Network):
    _icon = "nat-gateway.png"


class PeeringConnection(_Network):
    _icon = "peering-connection.png"


class VirtualPrivateCloud(_Network):
    _icon = "virtual-private-cloud.png"


class VpnConnections(_Network):
    _icon = "vpn-connections.png"


# Aliases

VPC = VirtualPrivateCloud
CLB = CloudLoadBalancer
ENI = ElasticNetworkInterface
DC = DirectConnect
VPNConnections = VpnConnections
NATGateway = NatGateway
FL = FlowLogs
PC = PeeringConnection
AIA = AnycastInternetAcceleration
CCN = CloudConnectNetwork
BWP = BandwidthPackage
