# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _TencentCloud

class _Network(_TencentCloud):
    _type = "network"
    _icon_dir = "resources/tencentcloud/network"


class CloudConnectNetwork(_Network):
    _icon = "cloud-connect-network.png"
class CloudLoadBalancer(_Network):
    _icon = "cloud-load-balancer.png"
class ContentDeliveryNetwork(_Network):
    _icon = "content-delivery-network.png"
class ElasticIP(_Network):
    _icon = "elastic-i-p.png"
class NATGateway(_Network):
    _icon = "n-a-t-gateway.png"
class PeeringConnection(_Network):
    _icon = "peering-connection.png"
class VPNConnections(_Network):
    _icon = "v-p-n-connections.png"
class VirtualPrivateCloud(_Network):
    _icon = "virtual-private-cloud.png"

# Aliases

CLB = CloudLoadBalancer
CCN = CloudConnectNetwork
EIP = ElasticIP
VPC = VirtualPrivateCloud
NAT = NATGateway
VPN = VPNConnections
PC = PeeringConnection
CDN = ContentDeliveryNetwork