# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _TencentCloud


class _Serverless(_TencentCloud):
    _type = "serverless"
    _icon_dir = "resources/tencentcloud/serverless"


class ServerlessCloudFunction(_Serverless):
    _icon = "serverless-cloud-function.png"


# Aliases

SCF = ServerlessCloudFunction
