# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _TencentCloud

class _Storage(_TencentCloud):
    _type = "storage"
    _icon_dir = "resources/tencentcloud/storage"


class CloudFileStorage(_Storage):
    _icon = "cloud-file-storage.png"
class CloudHDFS(_Storage):
    _icon = "cloud-h-d-f-s.png"
class CloudObjectStorage(_Storage):
    _icon = "cloud-object-storage.png"
class CloudStorageGateway(_Storage):
    _icon = "cloud-storage-gateway.png"

# Aliases

CHDFS = CloudHDFS
CFS = CloudFileStorage
CSG = CloudStorageGateway
COS = CloudObjectStorage