# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _TencentCloud


class _Storage(_TencentCloud):
    _type = "storage"
    _icon_dir = "resources/tencentcloud/storage"


class CloudArchiveStorage(_Storage):
    _icon = "cloud-archive-storage.png"


class CloudBlockStorage(_Storage):
    _icon = "cloud-block-storage.png"


class CloudDataMigration(_Storage):
    _icon = "cloud-data-migration.png"


class CloudFileStorage(_Storage):
    _icon = "cloud-file-storage.png"


class CloudLogService(_Storage):
    _icon = "cloud-log-service.png"


class CloudObjectStorage(_Storage):
    _icon = "cloud-object-storage.png"


class CloudStorageGateway(_Storage):
    _icon = "cloud-storage-gateway.png"


# Aliases

CBS = CloudBlockStorage
COS = CloudObjectStorage
CSG = CloudStorageGateway
CDM = CloudDataMigration
CFS = CloudFileStorage
CLS = CloudLogService
CAS = CloudArchiveStorage
