# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Ceph(_OnPrem):
    _type = "ceph"
    _icon_dir = "resources/onprem/ceph"


class Ceph(_Ceph):
    _icon = "ceph.png"


# Aliases
