# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Certificates(_OnPrem):
    _type = "certificates"
    _icon_dir = "resources/onprem/certificates"


class Certmanager(_Certificates):
    _icon = "certmanager.png"


class Letsencrypt(_Certificates):
    _icon = "letsencrypt.png"


# Aliases
