# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Chaos(_OnPrem):
    _type = "chaos"
    _icon_dir = "resources/onprem/chaos"


class ChaosMesh(_Chaos):
    _icon = "chaos-mesh.png"


class LitmusChaos(_Chaos):
    _icon = "litmus-chaos.png"


# Aliases
