# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Data(_OnPrem):
    _type = "data"
    _icon_dir = "resources/onprem/data"


class Norikra(_Data):
    _icon = "norikra.png"


# Aliases
