# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Dns(_OnPrem):
    _type = "dns"
    _icon_dir = "resources/onprem/dns"


class ExternalDns(_Dns):
    _icon = "external-dns.png"


# Aliases
