# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Iac(_OnPrem):
    _type = "iac"
    _icon_dir = "resources/onprem/iac"


class Terraform(_Iac):
    _icon = "terraform.png"


# Aliases
