# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Monitoring(_OnPrem):
    _type = "monitoring"
    _icon_dir = "resources/onprem/monitoring"


class Datadog(_Monitoring):
    _icon = "datadog.png"


class Grafana(_Monitoring):
    _icon = "grafana.png"


class Prometheus(_Monitoring):
    _icon = "prometheus.png"


class RsaBlack(_Monitoring):
    _icon = "rsa-black.png"


class RsaEndpoint(_Monitoring):
    _icon = "rsa-endpoint.png"


class RsaLogs(_Monitoring):
    _icon = "rsa-logs.png"


class RsaNetwitness(_Monitoring):
    _icon = "rsa-netwitness.png"


class RsaPackets(_Monitoring):
    _icon = "rsa-packets.png"


class RsaPlatform(_Monitoring):
    _icon = "rsa-platform.png"


class RsaRed(_Monitoring):
    _icon = "rsa-red.png"


class Sentry(_Monitoring):
    _icon = "sentry.png"


class Splunk(_Monitoring):
    _icon = "splunk.png"


class Thanos(_Monitoring):
    _icon = "thanos.png"


# Aliases
