# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _OnPrem(_OnPrem):
    _type = "onprem"
    _icon_dir = "resources/onprem/onprem"


class OnPrem(_OnPrem):
    _icon = "onprem.png"


# Aliases
