# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Registry(_OnPrem):
    _type = "registry"
    _icon_dir = "resources/onprem/registry"


class Harbor(_Registry):
    _icon = "harbor.png"


class JFrog(_Registry):
    _icon = "jfrog.png"


# Aliases
