# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Account(_Scaleway):
    _type = "account"
    _icon_dir = "resources/scaleway/account"


class Accountexperience(_Account):
    _icon = "accountexperience.png"


# Aliases
