# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Ai(_Scaleway):
    _type = "ai"
    _icon_dir = "resources/scaleway/ai"


class Custombuiltclusters(_Ai):
    _icon = "custombuiltclusters.png"


class Distributeddatalab(_Ai):
    _icon = "distributeddatalab.png"


class Generativeapi(_Ai):
    _icon = "generativeapi.png"


class Inference(_Ai):
    _icon = "inference.png"


class Ondemandclusters(_Ai):
    _icon = "ondemandclusters.png"


# Aliases
