# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway

class _Ai(_Scaleway):
    _type = "ai"
    _icon_dir = "resources/scaleway/ai"


class CustomBuiltClusters(_Ai):
    _icon = "custom-built-clusters.png"
class DistributedDataLab(_Ai):
    _icon = "distributed-data-lab.png"
class GenerativeApi(_Ai):
    _icon = "generative-api.png"
class Inference(_Ai):
    _icon = "inference.png"
class OnDemandClusters(_Ai):
    _icon = "on-demand-clusters.png"

# Aliases
