# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Baremetal(_Scaleway):
    _type = "baremetal"
    _icon_dir = "resources/scaleway/baremetal"


class BaremetalAluminium(_Baremetal):
    _icon = "baremetal-aluminium.png"


class BaremetalBeryllium(_Baremetal):
    _icon = "baremetal-beryllium.png"


class BaremetalLithium(_Baremetal):
    _icon = "baremetal-lithium.png"


class BaremetalTitaniumOriginal(_Baremetal):
    _icon = "baremetal-titanium-original.png"


class Baremetal(_Baremetal):
    _icon = "baremetal.png"


class CoreServers(_Baremetal):
    _icon = "core-servers.png"


class DedicatedServers(_Baremetal):
    _icon = "dedicated-servers.png"


class MacminiM1(_Baremetal):
    _icon = "macmini-m1.png"


class ProServers(_Baremetal):
    _icon = "pro-servers.png"


class StartServers(_Baremetal):
    _icon = "start-servers.png"


class StoreServers(_Baremetal):
    _icon = "store-servers.png"


# Aliases
