# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway

class _Baremetal(_Scaleway):
    _type = "baremetal"
    _icon_dir = "resources/scaleway/baremetal"


class AdditionalDisks(_Baremetal):
    _icon = "additional-disks.png"
class CoreServers(_Baremetal):
    _icon = "core-servers.png"
class DediBackup(_Baremetal):
    _icon = "dedi-backup.png"
class DediRack(_Baremetal):
    _icon = "dedi-rack.png"
class DedicatedServers(_Baremetal):
    _icon = "dedicated-servers.png"
class ElasticMetalAluminium(_Baremetal):
    _icon = "elastic-metal-aluminium.png"
class ElasticMetalBeryllium(_Baremetal):
    _icon = "elastic-metal-beryllium.png"
class ElasticMetalIridium(_Baremetal):
    _icon = "elastic-metal-iridium.png"
class ElasticMetalLithium(_Baremetal):
    _icon = "elastic-metal-lithium.png"
class ElasticMetalRiscv(_Baremetal):
    _icon = "elastic-metal-riscv.png"
class ElasticMetalTitanium(_Baremetal):
    _icon = "elastic-metal-titanium.png"
class ElasticMetal(_Baremetal):
    _icon = "elastic-metal.png"
class GpuServers(_Baremetal):
    _icon = "gpu-servers.png"
class IpFailover(_Baremetal):
    _icon = "ip-failover.png"
class MacMiniM1(_Baremetal):
    _icon = "mac-mini-m1.png"
class MacMiniM2(_Baremetal):
    _icon = "mac-mini-m2.png"
class MacMiniM4(_Baremetal):
    _icon = "mac-mini-m4.png"
class MacMini(_Baremetal):
    _icon = "mac-mini.png"
class ProServers(_Baremetal):
    _icon = "pro-servers.png"
class RpnSan(_Baremetal):
    _icon = "rpn-san.png"
class RpnV1(_Baremetal):
    _icon = "rpn-v1.png"
class RpnV2(_Baremetal):
    _icon = "rpn-v2.png"
class Rpn(_Baremetal):
    _icon = "rpn.png"
class StartServers(_Baremetal):
    _icon = "start-servers.png"
class StoreServers(_Baremetal):
    _icon = "store-servers.png"
class VpsProServers(_Baremetal):
    _icon = "vps-pro-servers.png"
class VpsServers(_Baremetal):
    _icon = "vps-servers.png"
class VpsStartServers(_Baremetal):
    _icon = "vps-start-servers.png"

# Aliases
