# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Baremetal(_Scaleway):
    _type = "baremetal"
    _icon_dir = "resources/scaleway/baremetal"


class Additionaldisks(_Baremetal):
    _icon = "additionaldisks.png"


class Coreservers(_Baremetal):
    _icon = "coreservers.png"


class Dedibackup(_Baremetal):
    _icon = "dedibackup.png"


class Dedicatedservers(_Baremetal):
    _icon = "dedicatedservers.png"


class Dedirack(_Baremetal):
    _icon = "dedirack.png"


class Elasticmetal(_Baremetal):
    _icon = "elasticmetal.png"


class Elasticmetalaluminium(_Baremetal):
    _icon = "elasticmetalaluminium.png"


class Elasticmetalberyllium(_Baremetal):
    _icon = "elasticmetalberyllium.png"


class Elasticmetaliridium(_Baremetal):
    _icon = "elasticmetaliridium.png"


class Elasticmetallithium(_Baremetal):
    _icon = "elasticmetallithium.png"


class Elasticmetalriscv(_Baremetal):
    _icon = "elasticmetalriscv.png"


class Elasticmetaltitanium(_Baremetal):
    _icon = "elasticmetaltitanium.png"


class Gpuservers(_Baremetal):
    _icon = "gpuservers.png"


class Ipfailover(_Baremetal):
    _icon = "ipfailover.png"


class Macmini(_Baremetal):
    _icon = "macmini.png"


class Macminim1(_Baremetal):
    _icon = "macminim1.png"


class Macminim2(_Baremetal):
    _icon = "macminim2.png"


class Macminim4(_Baremetal):
    _icon = "macminim4.png"


class Proservers(_Baremetal):
    _icon = "proservers.png"


class Rpn(_Baremetal):
    _icon = "rpn.png"


class Rpnsan(_Baremetal):
    _icon = "rpnsan.png"


class Rpnv1(_Baremetal):
    _icon = "rpnv1.png"


class Rpnv2(_Baremetal):
    _icon = "rpnv2.png"


class Startservers(_Baremetal):
    _icon = "startservers.png"


class Storeservers(_Baremetal):
    _icon = "storeservers.png"


class Vpsproservers(_Baremetal):
    _icon = "vpsproservers.png"


class Vpsservers(_Baremetal):
    _icon = "vpsservers.png"


class Vpsstartservers(_Baremetal):
    _icon = "vpsstartservers.png"


# Aliases
