# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Billing(_Scaleway):
    _type = "billing"
    _icon_dir = "resources/scaleway/billing"


class Billing(_Billing):
    _icon = "billing.png"


class Cb(_Billing):
    _icon = "cb.png"


class Costmanager(_Billing):
    _icon = "costmanager.png"


class Savingsplans(_Billing):
    _icon = "savingsplans.png"


class Sepa(_Billing):
    _icon = "sepa.png"


class Verifycard(_Billing):
    _icon = "verifycard.png"


# Aliases
