# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway

class _Billing(_Scaleway):
    _type = "billing"
    _icon_dir = "resources/scaleway/billing"


class Billing(_Billing):
    _icon = "billing.png"
class Cb(_Billing):
    _icon = "cb.png"
class CostManager(_Billing):
    _icon = "cost-manager.png"
class SavingsPlans(_Billing):
    _icon = "savings-plans.png"
class Sepa(_Billing):
    _icon = "sepa.png"
class VerifyCard(_Billing):
    _icon = "verify-card.png"

# Aliases
