# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Compute(_Scaleway):
    _type = "compute"
    _icon_dir = "resources/scaleway/compute"


class ComputeDev(_Compute):
    _icon = "compute-dev.png"


class ComputeGp(_Compute):
    _icon = "compute-gp.png"


class ComputeGpu(_Compute):
    _icon = "compute-gpu.png"


class Functions(_Compute):
    _icon = "functions.png"


class KubernetesEngine(_Compute):
    _icon = "kubernetes-engine.png"


# Aliases

Kapsule = KubernetesEngine
