# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Compute(_Scaleway):
    _type = "compute"
    _icon_dir = "resources/scaleway/compute"


class BlockStorage(_Compute):
    _icon = "block-storage.png"


class InstanceDev(_Compute):
    _icon = "instance-dev.png"


class InstanceEnterprise(_Compute):
    _icon = "instance-enterprise.png"


class InstanceGp(_Compute):
    _icon = "instance-gp.png"


class InstanceGpu(_Compute):
    _icon = "instance-gpu.png"


class InstanceSrd(_Compute):
    _icon = "instance-srd.png"


class Instance(_Compute):
    _icon = "instance.png"


# Aliases
