# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway

class _Compute(_Scaleway):
    _type = "compute"
    _icon_dir = "resources/scaleway/compute"


class CloudInit(_Compute):
    _icon = "cloud-init.png"
class CostOptimizedInstances(_Compute):
    _icon = "cost-optimized-instances.png"
class GpuInstances(_Compute):
    _icon = "gpu-instances.png"
class Images(_Compute):
    _icon = "images.png"
class InstanceScalingGroups(_Compute):
    _icon = "instance-scaling-groups.png"
class Instances(_Compute):
    _icon = "instances.png"
class LearningInstances(_Compute):
    _icon = "learning-instances.png"
class LocalStorage(_Compute):
    _icon = "local-storage.png"
class PlacementGroup(_Compute):
    _icon = "placement-group.png"
class ProductionOptimizedInstances(_Compute):
    _icon = "production-optimized-instances.png"
class SecurityGroup(_Compute):
    _icon = "security-group.png"
class Snapshots(_Compute):
    _icon = "snapshots.png"
class WorkloadOptimizedInstances(_Compute):
    _icon = "workload-optimized-instances.png"

# Aliases
