# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Containers(_Scaleway):
    _type = "containers"
    _icon_dir = "resources/scaleway/containers"


class Applicationlibrary(_Containers):
    _icon = "applicationlibrary.png"


class Containerregistry(_Containers):
    _icon = "containerregistry.png"


class Dedicatedcontrolplane(_Containers):
    _icon = "dedicatedcontrolplane.png"


class Kuberneteskapsule(_Containers):
    _icon = "kuberneteskapsule.png"


class Kuberneteskosmos(_Containers):
    _icon = "kuberneteskosmos.png"


class Pool(_Containers):
    _icon = "pool.png"


# Aliases
