# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Containers(_Scaleway):
    _type = "containers"
    _icon_dir = "resources/scaleway/containers"


class Kapsule(_Containers):
    _icon = "kapsule.png"


class Kosmos(_Containers):
    _icon = "kosmos.png"


class Registry(_Containers):
    _icon = "registry.png"


# Aliases
