# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Database(_Scaleway):
    _type = "database"
    _icon_dir = "resources/scaleway/database"


class Database(_Database):
    _icon = "database.png"


# Aliases
