# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Databases(_Scaleway):
    _type = "databases"
    _icon_dir = "resources/scaleway/databases"


class Db(_Databases):
    _icon = "db.png"


class Redis(_Databases):
    _icon = "redis.png"


# Aliases
