# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Devtools(_Scaleway):
    _type = "devtools"
    _icon_dir = "resources/scaleway/devtools"


class Api(_Devtools):
    _icon = "api.png"


class CommandLineInterface(_Devtools):
    _icon = "command-line-interface.png"


# Aliases

CLI = CommandLineInterface
