# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Devtools(_Scaleway):
    _type = "devtools"
    _icon_dir = "resources/scaleway/devtools"


class Api(_Devtools):
    _icon = "api.png"


class Cli(_Devtools):
    _icon = "cli.png"


class Console(_Devtools):
    _icon = "console.png"


class Iam(_Devtools):
    _icon = "iam.png"


class Observability(_Devtools):
    _icon = "observability.png"


class Terraform(_Devtools):
    _icon = "terraform.png"


# Aliases
