# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Environmentalfootprint(_Scaleway):
    _type = "environmentalfootprint"
    _icon_dir = "resources/scaleway/environmentalfootprint"


class Environmentalfootprintcalculator(_Environmentalfootprint):
    _icon = "environmentalfootprintcalculator.png"


# Aliases
