# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway

class _Environmental_Footprint(_Scaleway):
    _type = "environmental_footprint"
    _icon_dir = "resources/scaleway/environmental_footprint"


class EnvironmentalFootprintCalculator(_Environmental_Footprint):
    _icon = "environmental-footprint-calculator.png"

# Aliases
