# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _General(_Scaleway):
    _type = "general"
    _icon_dir = "resources/scaleway/general"


class Marketplace(_General):
    _icon = "marketplace.png"


# Aliases
