# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Infrastructure(_Scaleway):
    _type = "infrastructure"
    _icon_dir = "resources/scaleway/infrastructure"


class Distributionsinstantapps(_Infrastructure):
    _icon = "distributionsinstantapps.png"


class Os(_Infrastructure):
    _icon = "os.png"


class Server(_Infrastructure):
    _icon = "server.png"


# Aliases
