# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Iot(_Scaleway):
    _type = "iot"
    _icon_dir = "resources/scaleway/iot"


class Hub(_Iot):
    _icon = "hub.png"


# Aliases
