# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Manageddatabases(_Scaleway):
    _type = "manageddatabases"
    _icon_dir = "resources/scaleway/manageddatabases"


class Databaseforredis(_Manageddatabases):
    _icon = "databaseforredis.png"


class Datawarehouse(_Manageddatabases):
    _icon = "datawarehouse.png"


class Manageddatabase(_Manageddatabases):
    _icon = "manageddatabase.png"


class Managedmongodb(_Manageddatabases):
    _icon = "managedmongodb.png"


class Managedsearchdatabase(_Manageddatabases):
    _icon = "managedsearchdatabase.png"


class Postgresqlmysqldatabase(_Manageddatabases):
    _icon = "postgresqlmysqldatabase.png"


# Aliases
