# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Managedservices(_Scaleway):
    _type = "managedservices"
    _icon_dir = "resources/scaleway/managedservices"


class Devices(_Managedservices):
    _icon = "devices.png"


class Hubnetworks(_Managedservices):
    _icon = "hubnetworks.png"


class Hubroutes(_Managedservices):
    _icon = "hubroutes.png"


class Iothub(_Managedservices):
    _icon = "iothub.png"


class Smtp(_Managedservices):
    _icon = "smtp.png"


class Transactionalemail(_Managedservices):
    _icon = "transactionalemail.png"


class Webhosting(_Managedservices):
    _icon = "webhosting.png"


# Aliases
