# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Misc(_Scaleway):
    _type = "misc"
    _icon_dir = "resources/scaleway/misc"


class AdditionalDisk(_Misc):
    _icon = "additional-disk.png"


class Bandwidth(_Misc):
    _icon = "bandwidth.png"


class BasicSupport(_Misc):
    _icon = "basic-support.png"


class Billing(_Misc):
    _icon = "billing.png"


class CloudInit(_Misc):
    _icon = "cloud-init.png"


class CloudProjects(_Misc):
    _icon = "cloud-projects.png"


class Ddos(_Misc):
    _icon = "ddos.png"


class Dedibackup(_Misc):
    _icon = "dedibackup.png"


class Dedirack(_Misc):
    _icon = "dedirack.png"


class DistributionsInstantapps(_Misc):
    _icon = "distributions-instantapps.png"


class GoldSupport(_Misc):
    _icon = "gold-support.png"


class IpFailover(_Misc):
    _icon = "ip-failover.png"


class Monitoring(_Misc):
    _icon = "monitoring.png"


class MultiUsers(_Misc):
    _icon = "multi-users.png"


class Os(_Misc):
    _icon = "os.png"


class PlatinumSupport(_Misc):
    _icon = "platinum-support.png"


class RpnSan(_Misc):
    _icon = "rpn-san.png"


class RpnV1(_Misc):
    _icon = "rpn-v1.png"


class RpnV2(_Misc):
    _icon = "rpn-v2.png"


class Rpn(_Misc):
    _icon = "rpn.png"


class SdkGo(_Misc):
    _icon = "sdk-go.png"


class SdkPython(_Misc):
    _icon = "sdk-python.png"


class ServiceLevel(_Misc):
    _icon = "service-level.png"


class SilverSupport(_Misc):
    _icon = "silver-support.png"


class Sms(_Misc):
    _icon = "sms.png"


class Smtp(_Misc):
    _icon = "smtp.png"


# Aliases
