# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Ml(_Scaleway):
    _type = "ml"
    _icon_dir = "resources/scaleway/ml"


class DeepLearningImages(_Ml):
    _icon = "deep-learning-images.png"


# Aliases
