# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Network(_Scaleway):
    _type = "network"
    _icon_dir = "resources/scaleway/network"


class Backends(_Network):
    _icon = "backends.png"


class Cdn(_Network):
    _icon = "cdn.png"


class Ddos(_Network):
    _icon = "ddos.png"


class Domainsanddns(_Network):
    _icon = "domainsanddns.png"


class Edgeservices(_Network):
    _icon = "edgeservices.png"


class Flexibleip(_Network):
    _icon = "flexibleip.png"


class Frontends(_Network):
    _icon = "frontends.png"


class Interlink(_Network):
    _icon = "interlink.png"


class Ipam(_Network):
    _icon = "ipam.png"


class Loadbalancers(_Network):
    _icon = "loadbalancers.png"


class Networkacls(_Network):
    _icon = "networkacls.png"


class Privateip(_Network):
    _icon = "privateip.png"


class Privatenetworks(_Network):
    _icon = "privatenetworks.png"


class Publicgateway(_Network):
    _icon = "publicgateway.png"


class Router(_Network):
    _icon = "router.png"


class Sslcertificates(_Network):
    _icon = "sslcertificates.png"


class Vpc(_Network):
    _icon = "vpc.png"


class Vpn(_Network):
    _icon = "vpn.png"


class Zone(_Network):
    _icon = "zone.png"


# Aliases
