# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Networking(_Scaleway):
    _type = "networking"
    _icon_dir = "resources/scaleway/networking"


class Bandwidth(_Networking):
    _icon = "bandwidth.png"


# Aliases
