# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Observability(_Scaleway):
    _type = "observability"
    _icon_dir = "resources/scaleway/observability"


class Cockpit(_Observability):
    _icon = "cockpit.png"


class Monitoring(_Observability):
    _icon = "monitoring.png"


# Aliases
