# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Orchestrationtools(_Scaleway):
    _type = "orchestrationtools"
    _icon_dir = "resources/scaleway/orchestrationtools"


class Api(_Orchestrationtools):
    _icon = "api.png"


class Cli(_Orchestrationtools):
    _icon = "cli.png"


class Console(_Orchestrationtools):
    _icon = "console.png"


class Terraform(_Orchestrationtools):
    _icon = "terraform.png"


class Webplatform(_Orchestrationtools):
    _icon = "webplatform.png"


# Aliases
