# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Scalewaylabs(_Scaleway):
    _type = "scalewaylabs"
    _icon_dir = "resources/scaleway/scalewaylabs"


class Ipfsnaming(_Scalewaylabs):
    _icon = "ipfsnaming.png"


class Ipfspinning(_Scalewaylabs):
    _icon = "ipfspinning.png"


class Qaas(_Scalewaylabs):
    _icon = "qaas.png"


class Quantumapplication(_Scalewaylabs):
    _icon = "quantumapplication.png"


# Aliases
