# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway

class _Scaleway_Labs(_Scaleway):
    _type = "scaleway_labs"
    _icon_dir = "resources/scaleway/scaleway_labs"


class IpfsNaming(_Scaleway_Labs):
    _icon = "ipfs-naming.png"
class IpfsPinning(_Scaleway_Labs):
    _icon = "ipfs-pinning.png"
class Qaas(_Scaleway_Labs):
    _icon = "qaas.png"
class QuantumApplication(_Scaleway_Labs):
    _icon = "quantum-application.png"

# Aliases
