# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Securityandidentity(_Scaleway):
    _type = "securityandidentity"
    _icon_dir = "resources/scaleway/securityandidentity"


class Apikey(_Securityandidentity):
    _icon = "apikey.png"


class Application(_Securityandidentity):
    _icon = "application.png"


class Audittrail(_Securityandidentity):
    _icon = "audittrail.png"


class Iam(_Securityandidentity):
    _icon = "iam.png"


class Keymanager(_Securityandidentity):
    _icon = "keymanager.png"


class Multiusers(_Securityandidentity):
    _icon = "multiusers.png"


class Policy(_Securityandidentity):
    _icon = "policy.png"


class Secretmanager(_Securityandidentity):
    _icon = "secretmanager.png"


class User(_Securityandidentity):
    _icon = "user.png"


# Aliases
