# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Serverless(_Scaleway):
    _type = "serverless"
    _icon_dir = "resources/scaleway/serverless"


class Containers(_Serverless):
    _icon = "containers.png"


class Functions(_Serverless):
    _icon = "functions.png"


class Messaging(_Serverless):
    _icon = "messaging.png"


# Aliases
