# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway

class _Serverless(_Scaleway):
    _type = "serverless"
    _icon_dir = "resources/scaleway/serverless"


class ApiGateway(_Serverless):
    _icon = "api-gateway.png"
class ManagedRabbitmq(_Serverless):
    _icon = "managed-rabbitmq.png"
class Nats(_Serverless):
    _icon = "nats.png"
class Queues(_Serverless):
    _icon = "queues.png"
class Queuing(_Serverless):
    _icon = "queuing.png"
class ServerlessContainers(_Serverless):
    _icon = "serverless-containers.png"
class ServerlessDb(_Serverless):
    _icon = "serverless-db.png"
class ServerlessFunctions(_Serverless):
    _icon = "serverless-functions.png"
class ServerlessJobs(_Serverless):
    _icon = "serverless-jobs.png"
class TopicsAndEvents(_Serverless):
    _icon = "topics-and-events.png"

# Aliases
