# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Storage(_Scaleway):
    _type = "storage"
    _icon_dir = "resources/scaleway/storage"


class BlockStorage(_Storage):
    _icon = "block-storage.png"


class ColdStorage(_Storage):
    _icon = "cold-storage.png"


class ContainerRegistry(_Storage):
    _icon = "container-registry.png"


class ObjectStorage(_Storage):
    _icon = "object-storage.png"


# Aliases
