# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Storage(_Scaleway):
    _type = "storage"
    _icon_dir = "resources/scaleway/storage"


class Cold(_Storage):
    _icon = "cold.png"


class Object(_Storage):
    _icon = "object.png"


# Aliases
