# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Storage(_Scaleway):
    _type = "storage"
    _icon_dir = "resources/scaleway/storage"


class Blockstorage(_Storage):
    _icon = "blockstorage.png"


class Coldstorage(_Storage):
    _icon = "coldstorage.png"


class Filestorage(_Storage):
    _icon = "filestorage.png"


class Lifecyclerules(_Storage):
    _icon = "lifecyclerules.png"


class Objectstorage(_Storage):
    _icon = "objectstorage.png"


# Aliases
