# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scaleway


class _Support(_Scaleway):
    _type = "support"
    _icon_dir = "resources/scaleway/support"


class Abuse(_Support):
    _icon = "abuse.png"


class Basicsupport(_Support):
    _icon = "basicsupport.png"


class Goldsupport(_Support):
    _icon = "goldsupport.png"


class Platinumsupport(_Support):
    _icon = "platinumsupport.png"


class Servicelevel(_Support):
    _icon = "servicelevel.png"


class Silversupport(_Support):
    _icon = "silversupport.png"


class Support(_Support):
    _icon = "support.png"


# Aliases
