# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Generic


class _Generic(_Generic):
    _type = "generic"
    _icon_dir = "resources/generic/generic"


class Generic(_Generic):
    _icon = "generic.png"


# Aliases
