name: Publish
on:
  push:
    branches: [master, "@cbrown/743-mkdocs-site"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Install round
        run: |
          go install github.com/mingrammer/round@latest

      - name: Install inkscape
        run: |
          sudo apt-get update && sudo apt-get install inkscape

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build
        run: |
          cp -r resources docs/img/resources && mkdocs build -c -f mkdocs.yml
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site